// ── ZELO — Catálogo CID-10 partilhado (códigos comuns no hospital) ──
// Usado no Bloco Operatório (diagnóstico com CID opcional). O Controlo de
// Pacientes tem o seu próprio catálogo (zelo_cp_relatorio.js), igual a este
// na parte comum.
window.ZELO_CID = window.ZELO_CID || [
    ['A09', 'Diarreia e gastroenterite de origem infecciosa presumível'], ['A01.0', 'Febre tifoide'],
    ['A16', 'Tuberculose respiratória sem confirmação bacteriológica'], ['A15', 'Tuberculose respiratória com confirmação bacteriológica'],
    ['A41.9', 'Sepsis não especificada'], ['A35', 'Tétano'], ['A06', 'Amebíase'], ['A00', 'Cólera'],
    ['B50.9', 'Malária por Plasmodium falciparum'], ['B54', 'Malária não especificada'], ['B20', 'Doença pelo VIH'], ['B05', 'Sarampo'],
    ['D50', 'Anemia por deficiência de ferro'], ['D57.0', 'Anemia falciforme com crise'], ['D64.9', 'Anemia não especificada'],
    ['E11', 'Diabetes mellitus tipo 2'], ['E10', 'Diabetes mellitus tipo 1'], ['E14', 'Diabetes mellitus não especificada'],
    ['E43', 'Desnutrição proteico-calórica grave'], ['E86', 'Desidratação'],
    ['G40', 'Epilepsia'], ['G41', 'Estado de mal epiléptico'], ['G03.9', 'Meningite não especificada'], ['G93.4', 'Encefalopatia não especificada'],
    ['G06.0', 'Abscesso intracraniano'], ['G91', 'Hidrocefalia'],
    ['I10', 'Hipertensão arterial essencial'], ['I11', 'Cardiopatia hipertensiva'], ['I50', 'Insuficiência cardíaca'],
    ['I21', 'Enfarte agudo do miocárdio'], ['I26', 'Embolia pulmonar'], ['I48', 'Fibrilhação auricular'],
    ['I60', 'Hemorragia subaracnoideia'], ['I61', 'Hemorragia intracerebral'], ['I63', 'Enfarte cerebral (AVC isquémico)'],
    ['I64', 'AVC não especificado como hemorrágico ou isquémico'], ['I80', 'Flebite e tromboflebite'], ['I83', 'Varizes dos membros inferiores'],
    ['J06.9', 'Infecção aguda das vias aéreas superiores'], ['J18', 'Pneumonia, organismo não especificado'], ['J15', 'Pneumonia bacteriana'],
    ['J20', 'Bronquite aguda'], ['J44', 'Doença pulmonar obstrutiva crónica (DPOC)'], ['J45', 'Asma'],
    ['J90', 'Derrame pleural'], ['J93', 'Pneumotórax'], ['J96', 'Insuficiência respiratória'],
    ['K04', 'Doença da polpa e dos tecidos periapicais'], ['K12.2', 'Celulite e abscesso da boca'],
    ['K25', 'Úlcera gástrica'], ['K26', 'Úlcera duodenal'], ['K35', 'Apendicite aguda'], ['K40', 'Hérnia inguinal'],
    ['K42', 'Hérnia umbilical'], ['K43', 'Hérnia ventral'], ['K56', 'Obstrução intestinal'], ['K61', 'Abscesso anal e rectal'],
    ['K65', 'Peritonite'], ['K70', 'Doença alcoólica do fígado'], ['K74', 'Fibrose e cirrose hepática'], ['K80', 'Colelitíase'],
    ['K81', 'Colecistite'], ['K85', 'Pancreatite aguda'], ['K92.2', 'Hemorragia gastrointestinal não especificada'],
    ['L02', 'Abscesso cutâneo, furúnculo e antraz'], ['L03', 'Celulite'], ['L89', 'Úlcera de pressão'], ['L97', 'Úlcera do membro inferior'],
    ['M00', 'Artrite piogénica'], ['M10', 'Gota'], ['M16', 'Coxartrose'], ['M17', 'Gonartrose'], ['M50', 'Hérnia discal cervical'],
    ['M51', 'Hérnia discal lombar / torácica'], ['M54.5', 'Lombalgia'], ['M86', 'Osteomielite'],
    ['N04', 'Síndrome nefrótica'], ['N10', 'Pielonefrite aguda'], ['N17', 'Insuficiência renal aguda'], ['N18', 'Doença renal crónica'],
    ['N19', 'Insuficiência renal não especificada'], ['N20', 'Litíase renal e ureteral'], ['N39.0', 'Infecção do trato urinário'],
    ['N40', 'Hiperplasia da próstata'], ['N45', 'Orquite e epididimite'],
    ['C16', 'Neoplasia maligna do estômago'], ['C18', 'Neoplasia maligna do cólon'], ['C22', 'Neoplasia maligna do fígado'],
    ['C50', 'Neoplasia maligna da mama'], ['C53', 'Neoplasia maligna do colo do útero'], ['C61', 'Neoplasia maligna da próstata'],
    ['C71', 'Neoplasia maligna do encéfalo'], ['D33', 'Neoplasia benigna do encéfalo'],
    ['S00', 'Traumatismo superficial da cabeça'], ['S02', 'Fractura do crânio e dos ossos da face'], ['S02.4', 'Fractura do malar e do maxilar'],
    ['S02.6', 'Fractura da mandíbula'], ['S06.0', 'Concussão cerebral'], ['S06.5', 'Hemorragia subdural traumática'],
    ['S06.9', 'Traumatismo crânio-encefálico (TCE)'], ['S12', 'Fractura da coluna cervical'], ['S14', 'Traumatismo da medula cervical'],
    ['S22', 'Fractura das costelas, esterno e coluna torácica'], ['S24', 'Traumatismo da medula torácica'], ['S27', 'Traumatismo de órgãos intratorácicos'],
    ['S32', 'Fractura da coluna lombar e da pelve'], ['S34', 'Traumatismo da medula lombar'], ['S36', 'Traumatismo de órgãos intra-abdominais'],
    ['S42.0', 'Fractura da clavícula'], ['S42.3', 'Fractura da diáfise do úmero'], ['S42', 'Fractura do ombro e do braço'],
    ['S43.0', 'Luxação do ombro'], ['S52.5', 'Fractura da extremidade distal do rádio'], ['S52', 'Fractura do antebraço'],
    ['S62', 'Fractura do punho e da mão'], ['S72.0', 'Fractura do colo do fémur'], ['S72.3', 'Fractura da diáfise do fémur'],
    ['S72', 'Fractura do fémur'], ['S73', 'Luxação da anca'], ['S82.2', 'Fractura da diáfise da tíbia'], ['S82', 'Fractura da perna, incluindo o tornozelo'],
    ['S83', 'Luxação do joelho'], ['S92', 'Fractura do pé'], ['T07', 'Traumatismos múltiplos'], ['T14', 'Traumatismo de região não especificada'],
    ['T30', 'Queimadura'], ['T31', 'Queimaduras segundo a extensão da superfície corporal'], ['T63.0', 'Mordedura de serpente (veneno)'],
    ['T79.3', 'Infecção pós-traumática de ferida'], ['T81.4', 'Infecção após procedimento'], ['T84', 'Complicação de dispositivo ortopédico'],
    ['R10', 'Dor abdominal'], ['R40.2', 'Coma'], ['R50.9', 'Febre de origem desconhecida'], ['R56', 'Convulsões'], ['R57', 'Choque'],
    ['K36', 'Outras formas de apendicite'], ['K37', 'Apendicite não especificada'], ['K41', 'Hérnia femoral'], ['K44', 'Hérnia diafragmática'],
    ['K57', 'Doença diverticular do intestino'], ['K60', 'Fissura e fístula anal'], ['K64', 'Hemorroidas'], ['K66.0', 'Aderências peritoneais'],
    ['N13', 'Uropatia obstrutiva'], ['N43', 'Hidrocelo'], ['N47', 'Fimose'], ['N35', 'Estenose uretral'],
    ['H25', 'Catarata senil'], ['H26', 'Outras cataratas'], ['J34.2', 'Desvio do septo nasal'], ['J35', 'Doenças crónicas das amígdalas e adenoides'],
    ['E04', 'Bócio não tóxico'], ['D17', 'Lipoma'], ['L72', 'Quisto da pele e do tecido subcutâneo'], ['D25', 'Leiomioma do útero'],
    ['C20', 'Neoplasia maligna do reto'], ['C73', 'Neoplasia maligna da tiroide'], ['T81.0', 'Hemorragia e hematoma após procedimento'],
    ['S01', 'Ferida aberta da cabeça'], ['S61', 'Ferida aberta do punho e da mão'], ['S81', 'Ferida aberta da perna'], ['S31', 'Ferida aberta do abdómen']
];
