"""Explicações detalhadas do quiz (parte 2: OSI, TCP/IP, cabos, binário/hex, Ethernet, ARP)."""

ENTRADAS = [
    ("Que camada transforma os dados em sinais no cabo?",
     "A <b>camada física (1)</b> converte os bits em sinais: impulsos elétricos no cobre, luz na fibra ou ondas de rádio no Wi-Fi. Também define conectores, cabos e velocidades.",
     {"Física": "Certo: camada 1, bits em sinais elétricos, luminosos ou de rádio.",
      "Transporte": "A camada 4 trata de portas, segmentação e fiabilidade (TCP/UDP), não de sinais.",
      "Aplicação": "A camada 7 é onde estão os protocolos que o utilizador usa (HTTP, DNS).",
      "Sessão": "A camada 5 gere o diálogo entre aplicações, longe do cabo."}),
    ("Em que camada OSI trabalha o router?",
     "O router trabalha na <b>camada 3 (Rede)</b>: lê o IP de destino de cada pacote, consulta a tabela de routing e escolhe a interface de saída. Truque: hub = 1, switch = 2, router = 3.",
     {"3": "Certo: camada de rede — endereços IP e encaminhamento.",
      "2": "Na camada 2 trabalha o switch, com endereços MAC.",
      "4": "A camada 4 é o transporte (TCP/UDP, portas); o router normal não decide por portas.",
      "7": "A camada 7 é a aplicação (HTTP, DNS…)."}),
    ("A PDU da camada de ligação de dados chama-se…",
     "Cada camada dá um nome à sua unidade de dados (PDU): camada 4 <b>segmento</b> (TCP) ou datagrama (UDP), camada 3 <b>pacote</b>, camada 2 <b>trama</b> (frame), camada 1 <b>bits</b>.",
     {"Trama": "Certo: na camada 2 os dados viajam em tramas (frames) com MAC de origem/destino.",
      "Segmento": "Segmento é a PDU da camada 4 (transporte).",
      "Pacote": "Pacote é a PDU da camada 3 (rede).",
      "Bit": "Bits são a PDU da camada 1 (física)."}),
    ("TCP e UDP pertencem à camada…",
     "<b>TCP</b> e <b>UDP</b> são os protocolos da <b>camada 4 (Transporte)</b>: identificam as aplicações por portas; o TCP também garante entrega ordenada e fiável, o UDP é mais simples e rápido.",
     {"Transporte": "Certo: camada 4 — portas, segmentação, fiabilidade.",
      "Rede": "Na camada de rede estão o IP e o ICMP.",
      "Sessão": "A sessão (5) gere diálogos, não define TCP/UDP.",
      "Aplicação": "Na aplicação estão HTTP, DNS, SMTP — que usam TCP ou UDP por baixo."}),
    ("A cifra de dados (por ex. TLS) é associada à camada de Apresentação no modelo OSI.",
     "Verdadeiro. A camada 6 (Apresentação) trata do <b>formato</b> dos dados: codificação (UTF-8), compressão e cifra. Confusão comum: no TCP/IP real o TLS fica “entre” o TCP e a aplicação, mas para o modelo OSI a resposta de exame é a camada 6."),
    ("Um cabo partido é um problema de que camada?",
     "Um cabo partido, um conector mal cravado ou uma porta sem luz são problemas da <b>camada 1 (Física)</b>. No diagnóstico começa-se por baixo: se a camada 1 falha, nada acima funciona.",
     {"1": "Certo: camada física — cabos, conectores, sinais.",
      "2": "A camada 2 trata de tramas e MAC; um erro aí seria, por exemplo, VLAN errada.",
      "3": "A camada 3 trata de IPs e routing (ex.: máscara ou gateway errados).",
      "7": "A camada 7 é a das aplicações (ex.: DNS a falhar)."}),
    ("Qual é a PDU da camada 2?",
     "Na camada 2 (Ligação de dados) a PDU é a <b>trama</b>: cabeçalho com MAC de destino e origem, tipo, os dados (o pacote IP) e o FCS no fim para detetar erros.",
     {"Trama": "Certo: camada 2 = trama (frame).",
      "Pacote": "Pacote é a PDU da camada 3.",
      "Segmento": "Segmento é a PDU da camada 4.",
      "Bits": "Bits são a PDU da camada 1."}),
    ("Em que camada trabalha um router?",
     "O router encaminha <b>pacotes</b> com base no endereço IP de destino, por isso trabalha na <b>camada 3</b>. Também “toca” na camada 2 (cria uma trama nova em cada salto), mas a decisão é de camada 3.",
     {"3": "Certo: camada de rede — decide pelo IP.",
      "1": "Na camada 1 trabalham hubs e repetidores (só sinal).",
      "2": "Na camada 2 trabalha o switch (MAC).",
      "7": "Camada 7 seria um proxy ou servidor de aplicação."}),
    ("Qual é o número da camada de Transporte no OSI?",
     "De baixo para cima: 1 Física, 2 Ligação de dados, 3 Rede, <b>4 Transporte</b>, 5 Sessão, 6 Apresentação, 7 Aplicação. Mnemónica (de cima para baixo, em inglês): “All People Seem To Need Data Processing”."),
    ("A cifra TLS e a codificação UTF-8 pertencem a que camada?",
     "A camada 6 (<b>Apresentação</b>) garante que os dados chegam num formato que o outro lado entende: codificação de caracteres (UTF-8, ASCII), compressão e cifra (TLS, no modelo OSI).",
     {"Apresentação": "Certo: formato, cifra e compressão são da camada 6.",
      "Sessão": "A sessão (5) abre, mantém e fecha diálogos; não codifica dados.",
      "Transporte": "O transporte (4) trata de portas e fiabilidade.",
      "Rede": "A rede (3) trata de endereços IP e encaminhamento."}),
    ("Quando um pacote atravessa um router, os endereços MAC da trama são substituídos.",
     "Verdadeiro. O router retira a trama que recebeu e cria uma <b>nova trama</b> para o próximo salto: MAC de origem = o da sua interface de saída, MAC de destino = o do próximo router ou do host. Os IPs mantêm-se (sem NAT). Confusão comum: pensar que o IP é que muda a cada salto."),
    ("O ping a 8.8.8.8 funciona, mas www.exemplo.ao não abre. Qual é a suspeita mais provável?",
     "Se o ping a um IP público funciona, as camadas 1 a 3 (cabo, VLAN, IP, gateway) estão bem. O que falha é traduzir o nome em IP: o <b>DNS</b>. Teste com <code>nslookup www.exemplo.ao</code> e verifique o servidor DNS configurado.",
     {"DNS (camada 7)": "Certo: há conectividade IP, falha a resolução de nomes.",
      "Cabo partido": "Com o cabo partido o ping a 8.8.8.8 também falhava.",
      "VLAN errada": "Numa VLAN errada não chegava ao gateway e o ping falhava.",
      "Máscara errada": "Uma máscara errada costuma impedir chegar ao gateway; o ping funciona, logo não é isso."}),
    ("Que equipamento trabalha principalmente na camada 2?",
     "O <b>switch</b> lê o MAC de destino de cada trama e envia-a só pela porta certa, usando a tabela MAC — trabalho de camada 2. Hubs e repetidores só repetem sinal (camada 1); routers decidem por IP (camada 3).",
     {"Switch": "Certo: encaminha tramas pelo endereço MAC.",
      "Hub": "O hub só repete os bits por todas as portas: camada 1.",
      "Router": "O router decide pelo IP: camada 3.",
      "Repetidor": "Regenera o sinal: camada 1."}),
    ("No encapsulamento, os dados descem da camada 7 para a 1 e cada camada acrescenta o seu cabeçalho.",
     "Verdadeiro. Ao enviar, cada camada embrulha os dados da camada de cima: o TCP junta portas (segmento), o IP junta endereços IP (pacote), a Ethernet junta MACs e FCS (trama), e a camada 1 envia bits. No destino faz-se o <b>desencapsulamento</b>, de baixo para cima."),
    ("Quantas camadas tem o modelo OSI?",
     "O modelo OSI tem <b>7 camadas</b>: 1 Física, 2 Ligação de dados, 3 Rede, 4 Transporte, 5 Sessão, 6 Apresentação, 7 Aplicação. O TCP/IP original tem só 4 — não as confunda."),
    ("Quantas camadas tem o modelo TCP/IP original?",
     "O modelo TCP/IP original (RFC 1122) tem <b>4 camadas</b>: Acesso à rede, Internet, Transporte e Aplicação. Alguns livros usam uma versão “atualizada” de 5 camadas (separando Física e Ligação de dados), mas a original tem 4.",
     {"4": "Certo: Acesso à rede, Internet, Transporte, Aplicação.",
      "5": "5 é o modelo TCP/IP “atualizado” de alguns livros, não o original.",
      "6": "Nenhum dos modelos de referência tem 6 camadas.",
      "7": "7 é o modelo OSI."}),
    ("O endereço IP de destino muda em cada router do caminho (sem NAT).",
     "Falso. Sem NAT, o IP de origem e o de destino ficam iguais de ponta a ponta. O que muda em cada salto são os <b>endereços MAC</b> (cada router cria uma trama nova) e o TTL (diminui 1). Confusão comum: trocar o papel do IP (destino final) com o do MAC (próximo salto)."),
    ("Que informação é acrescentada na camada de transporte?",
     "Na camada de transporte, TCP ou UDP acrescentam as <b>portas de origem e destino</b>, que identificam a aplicação (ex.: 443 para HTTPS). O TCP junta ainda números de sequência e confirmação.",
     {"Portas": "Certo: as portas identificam as aplicações em cada extremidade.",
      "Endereços MAC": "Os MAC são acrescentados na camada 2.",
      "Endereços IP": "Os IP são acrescentados na camada 3.",
      "FCS": "O FCS é o código de deteção de erros no fim da trama (camada 2)."}),
    ("O processo de retirar cabeçalhos no destino chama-se…",
     "No destino, cada camada lê e retira o seu cabeçalho e passa o resto à camada de cima: é o <b>desencapsulamento</b>. O processo inverso, na origem, é o encapsulamento.",
     {"Desencapsulamento": "Certo: retirar os cabeçalhos, de baixo para cima.",
      "Encapsulamento": "É o contrário: acrescentar cabeçalhos ao enviar.",
      "Fragmentação": "Fragmentar é partir um pacote grande em pedaços mais pequenos.",
      "Multiplexagem": "Multiplexar é várias conversas partilharem a mesma ligação (ex.: com portas diferentes)."}),
    ("Cada router diminui o TTL do pacote IP em 1.",
     "Verdadeiro. O TTL (Time To Live) é um contador no cabeçalho IP; cada router subtrai 1. Quando chega a 0, o pacote é descartado e o router envia um ICMP Time Exceeded à origem — evita pacotes a circular para sempre num loop. O traceroute usa isto para descobrir os saltos."),
    ("A camada Internet do TCP/IP corresponde a que camada OSI?",
     "A camada <b>Internet</b> do TCP/IP corresponde à <b>camada 3 (Rede)</b> do OSI: aí estão o IP, o ICMP e o encaminhamento entre redes.",
     {"3": "Certo: Internet = Rede (IP, ICMP).",
      "2": "A camada 2 OSI corresponde (com a 1) ao Acesso à rede do TCP/IP.",
      "4": "A 4 OSI é o Transporte, que tem o mesmo nome no TCP/IP.",
      "7": "A 7 OSI está dentro da Aplicação do TCP/IP."}),
    ("Que protocolo descobre o MAC do gateway a partir do seu IP?",
     "O <b>ARP</b> (Address Resolution Protocol) pergunta em broadcast “quem tem o IP 192.168.1.1? diga o seu MAC” e o dono responde em unicast. O PC guarda a resposta na tabela ARP (<code>arp -a</code>).",
     {"ARP": "Certo: traduz IP → MAC na rede local.",
      "DNS": "O DNS traduz nomes em IPs, não IPs em MACs.",
      "DHCP": "O DHCP atribui IP, máscara, gateway e DNS.",
      "ICMP": "O ICMP serve para mensagens de controlo e erro (ping, traceroute)."}),
    ("Quantos bytes tem o cabeçalho UDP?",
     "O cabeçalho UDP tem sempre <b>8 bytes</b>: porta de origem (2), porta de destino (2), comprimento (2) e checksum (2). É tão pequeno porque o UDP não faz confirmações nem controlo de fluxo — compare com os 20 bytes mínimos do TCP."),
    ("1000 bytes de dados por TCP/IPv4 sobre Ethernet: quantos bytes tem a trama (cabeçalho 14 + FCS 4)?",
     "Some as camadas de dentro para fora: dados 1000 + cabeçalho TCP 20 + cabeçalho IPv4 20 + cabeçalho Ethernet 14 + FCS 4 = <b>1058 bytes</b>. Cada camada acrescenta o seu cabeçalho (encapsulamento)."),
    ("Qual é a ordem correta do three-way handshake?",
     "O TCP abre uma ligação em três passos: o cliente envia <b>SYN</b> (“quero ligar, o meu n.º de sequência é X”), o servidor responde <b>SYN-ACK</b> (“aceito, recebi X, o meu é Y”) e o cliente termina com <b>ACK</b> (“recebi Y”).",
     {"SYN, SYN-ACK, ACK": "Certo: pedido, aceitação com confirmação, confirmação final.",
      "ACK, SYN, SYN-ACK": "Não se confirma (ACK) antes de haver pedido (SYN).",
      "SYN, ACK, SYN-ACK": "O servidor responde com SYN-ACK logo a seguir ao SYN; o ACK simples é o último.",
      "SYN-ACK, SYN, ACK": "O SYN-ACK é uma resposta, não pode ser a primeira mensagem."}),
    ("No modelo TCP/IP, as funções das camadas Sessão e Apresentação do OSI ficam na camada de Aplicação.",
     "Verdadeiro. A camada de Aplicação do TCP/IP junta as camadas 5, 6 e 7 do OSI: cada aplicação/protocolo (HTTP, TLS, SMTP) trata do seu diálogo e formato. Confusão comum: pensar que o TCP/IP “não tem” essas funções — tem, mas dentro da Aplicação."),
    ("O que é um socket?",
     "Um <b>socket</b> é a combinação <b>IP + protocolo de transporte + porta</b> que identifica uma ponta de uma comunicação, ex.: 192.168.1.23:50123/TCP. Um par de sockets (cliente e servidor) identifica uma ligação única.",
     {"A combinação IP + protocolo + porta": "Certo: ex.: 192.168.1.23:50123 em TCP.",
      "Um tipo de cabo": "“Socket” em inglês também é tomada, mas em redes é o ponto de comunicação lógico.",
      "O endereço MAC": "O MAC identifica a placa de rede na camada 2; não inclui porta.",
      "Uma VLAN": "Uma VLAN é uma rede local lógica num switch."}),
    ("Qual é a porta bem conhecida do HTTPS?",
     "O HTTPS (HTTP com TLS) usa a porta TCP <b>443</b>; o HTTP sem cifra usa a 80. Outras para o exame: SSH 22, Telnet 23, DNS 53, DHCP 67/68, SMTP 25."),
    ("Qual é o MSS típico do TCP numa Ethernet com MTU de 1500 bytes?",
     "O <b>MSS</b> (Maximum Segment Size) é o máximo de <i>dados</i> num segmento TCP. Numa Ethernet com MTU 1500: 1500 − 20 (cabeçalho IP) − 20 (cabeçalho TCP) = <b>1460 bytes</b>.",
     {"1460": "Certo: 1500 − 20 − 20 = 1460.",
      "1500": "1500 é o MTU (todo o pacote IP), não só os dados TCP.",
      "1480": "Retirou só o cabeçalho IP; falta retirar os 20 do TCP.",
      "1440": "Retirou 60 bytes; os cabeçalhos mínimos somam 40."}),
    ("Um PC envia um pacote para um servidor noutra rede. Qual o MAC de destino na trama que sai do PC?",
     "Quando o destino está <b>noutra rede</b>, o PC envia a trama para o <b>gateway</b>: MAC de destino = MAC do router, mas IP de destino = IP do servidor. O router recebe, decide o caminho e cria uma trama nova.",
     {"MAC do gateway (router)": "Certo: a trama vai até ao router; o IP continua a ser o do servidor.",
      "MAC do servidor": "O PC nem consegue saber esse MAC: o ARP só funciona na rede local.",
      "FFFF.FFFF.FFFF": "É o MAC de broadcast; dados normais não vão em broadcast.",
      "MAC do switch": "O switch é transparente: não é o destino das tramas, apenas as reencaminha."}),
    ("Qual o tamanho mínimo do cabeçalho TCP?",
     "O cabeçalho TCP tem no mínimo <b>20 bytes</b> (portas, n.º de sequência, n.º de confirmação, flags, janela, checksum…) e pode crescer até 60 com opções. O UDP tem só 8.",
     {"20 bytes": "Certo: 20 bytes sem opções.",
      "8 bytes": "8 bytes é o cabeçalho UDP.",
      "40 bytes": "40 bytes é a soma IP (20) + TCP (20), ou o cabeçalho IPv6.",
      "64 bytes": "64 bytes é o tamanho mínimo de uma trama Ethernet."}),
    ("O FCS de uma trama Ethernet serve para corrigir os erros detetados.",
     "Falso. O <b>FCS</b> (Frame Check Sequence, um CRC de 4 bytes) só <b>deteta</b> erros: se o cálculo não bater certo, a trama é descartada. A retransmissão fica a cargo das camadas superiores (o TCP). Confusão comum: confundir deteção com correção de erros."),
    ("Que equipamento decide o encaminhamento com base no endereço IP?",
     "O <b>router</b> lê o IP de destino, procura a rota mais específica na tabela de routing e envia o pacote pela interface certa — é a função de camada 3.",
     {"Router": "Certo: camada 3, tabela de routing com redes IP.",
      "Switch L2": "Um switch de camada 2 decide pelo MAC, não pelo IP.",
      "Hub": "O hub não decide nada: repete os bits por todas as portas.",
      "Access Point": "O AP liga clientes sem fios à rede com cabo (camada 2)."}),
    ("O switch aprende e usa qual endereço?",
     "O switch aprende o <b>MAC de origem</b> de cada trama e guarda-o na tabela MAC (MAC → porta). Depois usa o MAC de destino para enviar a trama só pela porta certa.",
     {"MAC": "Certo: tabela de endereços MAC (camada 2).",
      "IP": "Os IPs são usados pelos routers (camada 3).",
      "Porta TCP": "As portas TCP são da camada 4 e identificam aplicações.",
      "URL": "O URL é um endereço de aplicação (web), camada 7."}),
    ("Que equipamento gere muitos APs de forma centralizada?",
     "O <b>WLC</b> (Wireless LAN Controller) gere APs leves (lightweight) de forma central: configura SSIDs, segurança, canais e potência, e os APs falam com ele por túneis CAPWAP.",
     {"WLC": "Certo: Wireless LAN Controller, gere APs lightweight.",
      "NGFW": "Uma NGFW é uma firewall de nova geração, não gere APs.",
      "Hub": "Um hub é um repetidor antigo de camada 1.",
      "Modem": "O modem converte sinais para a linha do operador."}),
    ("Um switch multicamada consegue encaminhar tráfego entre redes IP.",
     "Verdadeiro. Um switch multicamada (L3) faz comutação de camada 2 <b>e</b> routing de camada 3 — por exemplo, routing entre VLANs com SVIs e <code>ip routing</code>. Confusão comum: pensar que todos os switches são só L2."),
    ("Em equipamentos reais as portas de um switch Cisco ficam verdes imediatamente ao ligar um PC.",
     "Falso. Com STP normal, a porta passa por <b>listening</b> e <b>learning</b> (15 s + 15 s) antes de chegar a <b>forwarding</b>; durante esse tempo o LED fica âmbar. Com <code>spanning-tree portfast</code> a porta de acesso passa logo a forwarding. No Packet Tracer pode parecer imediato."),
    ("Qual a distância máxima típica de um cabo UTP Ethernet?",
     "As normas 10BASE-T, 100BASE-TX e 1000BASE-T definem <b>100 metros</b> por segmento de cobre (90 m de cabo fixo + 10 m de cabos de ligação). Para mais, use fibra ou um switch intermédio.",
     {"100 m": "Certo: 100 m por segmento UTP.",
      "10 m": "É muito menos do que o limite; 10 m é um cabo de bastidor.",
      "55 m": "55 m é o alcance do 10GBASE-T em Cat 6, um caso especial.",
      "2 km": "2 km é alcance de fibra multimodo antiga, não de UTP."}),
    ("Para ligar dois switches antigos sem Auto-MDIX deve usar…",
     "Equipamentos do <b>mesmo tipo</b> (switch–switch, PC–PC, router–router) transmitem nos mesmos pinos, por isso precisam de <b>cabo cruzado</b> (T568A numa ponta, T568B na outra). Equipamentos diferentes (PC–switch) usam cabo direto. Com Auto-MDIX, tanto faz.",
     {"Cabo cruzado": "Certo: iguais com iguais → cruzado.",
      "Cabo direto": "O direto liga equipamentos diferentes (PC–switch); entre dois switches sem Auto-MDIX não funciona.",
      "Cabo de consola": "O cabo de consola liga um PC à porta de gestão, não transporta tráfego de rede.",
      "Cabo serial": "O cabo serial liga interfaces WAN série entre routers."}),
    ("Que fibra é usada para ligar edifícios a vários km de distância?",
     "A fibra <b>monomodo</b> tem um núcleo muito fino (~9 µm) e usa laser: a luz segue quase em linha reta e alcança dezenas de km. A <b>multimodo</b> (núcleo 50/62,5 µm, LEDs/VCSEL) é mais barata mas fica-se pelas centenas de metros.",
     {"Monomodo": "Certo: núcleo fino, laser, longas distâncias.",
      "Multimodo": "Multimodo serve para distâncias curtas (dentro do edifício, até ~550 m).",
      "UTP Cat 6": "UTP só chega a 100 m.",
      "Coaxial": "O coaxial é usado em TV por cabo, não para ligar edifícios por km em redes de dados."}),
    ("Configuração padrão da porta de consola Cisco:",
     "A consola Cisco usa por defeito <b>9600 bit/s, 8 bits de dados, sem paridade, 1 stop bit (8N1)</b> e sem controlo de fluxo. É o que se configura no PuTTY ou no Tera Term.",
     {"9600 8N1": "Certo: 9600 bit/s, 8 dados, sem paridade, 1 stop.",
      "115200 8N1": "115200 é usado por alguns equipamentos modernos, mas não é o padrão Cisco.",
      "9600 7E1": "7 bits com paridade par não é o padrão; o terminal mostraria lixo.",
      "57600 8N2": "Velocidade e stop bits errados."}),
    ("Auto-MDIX permite usar cabo direto entre dois switches.",
     "Verdadeiro. Com <b>Auto-MDIX</b> a porta deteta o tipo de cabo e troca internamente os pares de transmissão e receção, por isso tanto o direto como o cruzado funcionam. Confusão comum: em equipamentos antigos sem Auto-MDIX continua a ser preciso o cruzado."),
    ("Que conector se usa num cabo de rede UTP?",
     "O cabo UTP de rede usa o conector <b>RJ45</b> (8P8C: 8 posições, 8 contactos). O RJ11, mais pequeno e com 4–6 contactos, é de telefone.",
     {"RJ45": "Certo: 8 contactos para os 4 pares do UTP.",
      "RJ11": "RJ11 é o conector de telefone, mais estreito.",
      "SC": "SC é um conector de fibra ótica.",
      "BNC": "BNC é um conector de cabo coaxial."}),
    ("Que conector de fibra é usado nos módulos SFP?",
     "Os módulos <b>SFP</b> de fibra usam quase sempre conectores <b>LC duplex</b>: pequenos, com patilha, um para transmitir e outro para receber.",
     {"LC": "Certo: LC duplex, pequeno, ideal para SFP.",
      "ST": "ST é um conector de baioneta antigo, grande demais para SFP.",
      "F": "O conector F é coaxial (TV, satélite).",
      "RJ45": "RJ45 é para cobre (existe SFP de cobre, mas não é fibra)."}),
    ("Que ferramenta liga os fios a uma tomada keystone?",
     "Nas tomadas <b>keystone</b> e nos patch panels os fios são empurrados para contactos IDC com a <b>ferramenta de impacto (punch-down)</b>, que também corta o excesso de fio. O alicate de crimpar serve para os conectores RJ45 macho.",
     {"Ferramenta de impacto (punch-down)": "Certo: encaixa e corta os fios nos contactos IDC.",
      "Alicate de crimpar": "Serve para cravar conectores RJ45 na ponta do cabo.",
      "Testador": "O testador verifica o cabo depois de feito; não liga fios.",
      "Descarnador": "Tira o revestimento exterior do cabo; não liga os fios."}),
    ("Um conector RJ11 serve para ligar um PC a um switch.",
     "Falso. O <b>RJ11</b> é o conector de telefone (4–6 contactos, normalmente 2–4 fios). Ethernet em cobre usa <b>RJ45</b> com 8 contactos. Confusão comum: são parecidos, mas o RJ11 é mais estreito e nem encaixa bem na porta de rede."),
    ("Qual é a cor do pino 1 em T568B?",
     "Em <b>T568B</b> a ordem é: 1 branco-laranja, 2 laranja, 3 branco-verde, 4 azul, 5 branco-azul, 6 verde, 7 branco-castanho, 8 castanho. Em T568A trocam-se os pares laranja e verde (pino 1 branco-verde).",
     {"Branco-laranja": "Certo: T568B começa por branco-laranja.",
      "Branco-verde": "Branco-verde é o pino 1 em T568A.",
      "Laranja": "Laranja é o pino 2 em T568B.",
      "Azul": "Azul é o pino 4 nas duas normas."}),
    ("Um cabo com T568A numa ponta e T568B na outra é…",
     "Normas diferentes nas duas pontas trocam os pares laranja e verde (pinos 1-2 com 3-6): é um <b>cabo cruzado</b>. Mesma norma nas duas pontas (B–B ou A–A) = cabo direto.",
     {"Cruzado": "Certo: A numa ponta e B na outra = cruzado.",
      "Direto": "Direto tem a mesma norma nas duas pontas.",
      "De consola": "O cabo de consola (rollover) inverte todos os pinos (1↔8, 2↔7…).",
      "Coaxial": "Coaxial é outro tipo de cabo, sem pares trançados."}),
    ("Quanto deve ficar de fio destrançado dentro do conector?",
     "Deve-se destrançar o <b>mínimo possível</b>, cerca de <b>1,2 a 1,5 cm</b>. O entrançado é o que protege contra interferências (diafonia); destrançar demais faz o cabo falhar na certificação ou perder velocidade.",
     {"Cerca de 1,2 a 1,5 cm": "Certo: o mínimo necessário para entrar no conector.",
      "5 cm": "Demasiado: aumenta a diafonia (crosstalk) e os erros.",
      "Nenhum": "É preciso destrançar um pouco para alinhar os fios pela ordem certa.",
      "10 cm": "Muito excessivo: o cabo deixaria de cumprir a norma."}),
    ("Os pinos 4 e 5 são azul e branco-azul nas duas normas.",
     "Verdadeiro. Em T568A e T568B o <b>par azul</b> fica no meio (4 azul, 5 branco-azul) e o castanho no fim (7–8). Só mudam os pares laranja e verde. Confusão comum: pensar que as normas são totalmente diferentes."),
    ("No testador, a luz 3 de uma ponta acende com a 6 da outra. O que se passa?",
     "Num cabo direto as luzes acendem 1-1, 2-2, 3-3…; se a <b>3 acende com a 6</b> (e a 1 com a 3, a 2 com a 6), os pares laranja e verde estão trocados: é um <b>cabo cruzado</b> ou houve fios trocados ao cravar.",
     {"Cabo cruzado (ou fios trocados)": "Certo: 3↔6 indica pares trocados, como num cruzado.",
      "Cabo perfeito": "Num cabo direto perfeito a 3 acendia com a 3.",
      "Falta de energia": "Sem energia não acendia luz nenhuma.",
      "Cabo de fibra": "O testador de cobre nem liga a fibra ótica."}),
    ("Um portátil está a 140 m do switch mais próximo, num armazém. Qual a melhor solução cabeada?",
     "UTP só garante <b>100 m</b> por segmento. A 140 m usa-se <b>fibra</b> (multimodo chega a centenas de metros) ou coloca-se um <b>switch intermédio</b> a meio caminho, criando dois segmentos de menos de 100 m.",
     {"Fibra multimodo ou um switch intermédio": "Certo: fibra ou um switch a partir o troço em dois.",
      "UTP Cat 6 direto": "Cat 6 também está limitado a 100 m em Ethernet.",
      "Cabo de consola": "O cabo de consola é para gestão de equipamentos e tem poucos metros.",
      "UTP Cat 5e cruzado": "Cruzar o cabo não aumenta a distância; continua limitado a 100 m."}),
    ("Uma firewall de próxima geração (NGFW) pode identificar aplicações e funcionar como IPS.",
     "Verdadeiro. Uma <b>NGFW</b> vai além de filtrar por IP e porta: reconhece aplicações (ex.: distingue Facebook de outro tráfego HTTPS), integra <b>IPS</b>, filtragem de URLs e proteção contra malware. Confusão comum: achar que é só uma ACL mais rápida."),
    ("Qual destes é um exemplo de SaaS?",
     "Na cloud: <b>SaaS</b> (Software as a Service) é software pronto a usar pelo browser (Office 365, Gmail); <b>PaaS</b> dá uma plataforma para fazer deploy de código; <b>IaaS</b> dá máquinas virtuais, redes e discos.",
     {"Office 365 / Gmail": "Certo: software pronto a usar, gerido pelo fornecedor.",
      "Uma VM numa cloud pública": "Uma VM é IaaS (infraestrutura).",
      "Uma plataforma para fazer deploy de código": "Isso é PaaS (plataforma).",
      "Um switch físico": "É hardware local, não um serviço de cloud."}),
    ("Quanto é 01000001 em decimal?",
     "Bits ligados nas posições de valor <b>64</b> e <b>1</b>: 64 + 1 = <b>65</b>. (Curiosidade: 65 é a letra “A” em ASCII.)",
     {"65": "Certo: 64 + 1 = 65.",
      "63": "63 seria 00111111.",
      "129": "129 seria 10000001 (128 + 1) — confundiu a posição do primeiro bit.",
      "33": "33 seria 00100001 (32 + 1)."}),
    ("Quanto é 0xA8 em decimal?",
     "Em hexadecimal cada dígito vale 16 vezes o da direita. A = 10, por isso 0xA8 = 10 × 16 + 8 = 160 + 8 = <b>168</b> (como em 192.168).",
     {"168": "Certo: 10 × 16 + 8 = 168.",
      "158": "Errou a conta: 10 × 16 = 160, não 150.",
      "178": "Usou A = 11 (11 × 16 = 176…) ou somou mal.",
      "108": "Tratou o A como se valesse 10 em decimal (10 × 10 + 8)."}),
    ("Quantos bits representa um dígito hexadecimal?",
     "Um dígito hexadecimal tem 16 valores possíveis (0–F), e 2⁴ = 16, por isso representa <b>4 bits</b> (um nibble). É por isso que um byte se escreve com 2 dígitos hex (ex.: FF).",
     {"4": "Certo: 16 valores = 2⁴ → 4 bits.",
      "2": "2 bits só dão 4 valores (0–3).",
      "8": "8 bits são um byte inteiro = 2 dígitos hex.",
      "16": "16 é o número de valores do dígito, não o número de bits."}),
    ("255 em hexadecimal é FF.",
     "Verdadeiro. F = 15, por isso FF = 15 × 16 + 15 = 255, que é 11111111 em binário. Confusão comum: pensar que FF é 1515 ou que o maior byte é 256."),
    ("10101100.00010000.00000001.11111110 em decimal é…",
     "Converta octeto a octeto: 10101100 = 128+32+8+4 = <b>172</b>; 00010000 = <b>16</b>; 00000001 = <b>1</b>; 11111110 = 255 − 1 = <b>254</b>. Resultado: <b>172.16.1.254</b>.",
     {"172.16.1.254": "Certo: 172 . 16 . 1 . 254.",
      "172.16.1.255": "O último octeto tem o bit de 1 a zero: é 254, não 255.",
      "171.16.1.254": "O primeiro octeto é 172 (128+32+8+4), não 171.",
      "172.32.1.254": "O segundo octeto 00010000 é 16; 32 seria 00100000."}),
    ("Quanto vale 0xFF em decimal?",
     "F = 15. 0xFF = 15 × 16 + 15 = 240 + 15 = <b>255</b> — o maior valor de um byte (11111111). Aparece nas máscaras e no MAC de broadcast FFFF.FFFF.FFFF."),
    ("Quanto vale 0xA8 em decimal?",
     "A = 10, logo 0xA8 = 10 × 16 + 8 = <b>168</b>. Truque: o dígito da esquerda conta “dezasseis”, o da direita conta unidades."),
    ("Escreva 192 em hexadecimal (2 dígitos).",
     "Passe por binário e divida em grupos de 4 bits: 192 = 1100 0000 → 1100 = 12 = <b>C</b>, 0000 = <b>0</b> → <b>C0</b>. Verificação: 12 × 16 + 0 = 192."),
    ("Qual é a forma comprimida correta de 2001:0db8:0000:0000:0000:ff00:0042:8329?",
     "Duas regras do IPv6: (1) tiram-se os <b>zeros à esquerda</b> de cada hexteto (0db8 → db8, 0042 → 42); (2) <b>uma única</b> sequência de hextetos só com zeros pode virar <code>::</code>. Os zeros à direita (ff00) nunca se tiram. Resultado: 2001:db8::ff00:42:8329.",
     {"2001:db8::ff00:42:8329": "Certo: zeros à esquerda removidos e os três 0000 viram ::.",
      "2001:db8::ff:42:8329": "Tirou os zeros à direita de ff00 — isso muda o valor (ff00 ≠ 00ff).",
      "2001:db8:0::ff00:0042:8329:0": "Acrescentou hextetos e não comprimiu 0042; o endereço muda.",
      "2001::db8::ff00:42:8329": "O :: aparece duas vezes, o que é proibido (seria ambíguo)."}),
    ("Num endereço IPv6 o :: pode aparecer duas vezes se houver duas sequências de zeros.",
     "Falso. O <code>::</code> só pode aparecer <b>uma vez</b>; com dois seria impossível saber quantos hextetos de zeros há em cada lado. Se houver duas sequências, comprime-se a mais longa (ou a primeira, em empate) e a outra fica como 0."),
    ("Num MAC 00:1A:2B:3C:4D:5E, o que identificam os 3 primeiros bytes?",
     "Os primeiros 24 bits (3 bytes) do MAC são o <b>OUI</b> (Organizationally Unique Identifier), atribuído pelo IEEE a cada fabricante. Os últimos 3 bytes são o número de série dado pelo fabricante.",
     {"O fabricante (OUI)": "Certo: OUI = identificador do fabricante, atribuído pelo IEEE.",
      "A VLAN": "A VLAN não faz parte do MAC; vai numa etiqueta 802.1Q separada.",
      "O número da porta do switch": "O MAC é da placa de rede, não da porta onde está ligada.",
      "A rede IP": "O MAC não tem relação com a rede IP (camada 3)."}),
    ("Quanto é 3E8 hexadecimal em decimal?",
     "Posições hex: 256, 16, 1. 3E8 = 3 × 256 + E(14) × 16 + 8 = 768 + 224 + 8 = <b>1000</b>."),
    ("Quantos bits tem um endereço IPv6?",
     "Um endereço IPv6 tem <b>128 bits</b>, escritos como 8 grupos (hextetos) de 4 dígitos hex, ex.: 2001:0db8:0000:0000:0000:0000:0000:0001. Compare: IPv4 tem 32 bits e o MAC 48.",
     {"128": "Certo: 8 hextetos × 16 bits = 128.",
      "32": "32 bits é o IPv4.",
      "48": "48 bits é o endereço MAC.",
      "64": "64 bits é a parte de interface (ou o prefixo típico /64), metade do endereço."}),
    ("Quanto vale 0x2F em decimal?",
     "2 × 16 + F(15) = 32 + 15 = <b>47</b>. Em binário: 0010 1111."),
    ("Que subcamada trata dos endereços físicos?",
     "A camada 2 divide-se em duas subcamadas: <b>LLC</b> (802.2, fala com a camada 3 e identifica o protocolo) e <b>MAC</b> (802.3, endereços físicos, acesso ao meio e enquadramento das tramas).",
     {"MAC": "Certo: a subcamada MAC trata dos endereços físicos e do acesso ao meio.",
      "LLC": "A LLC liga a camada 2 à camada 3; não trata dos endereços.",
      "IP": "O IP é camada 3, não uma subcamada da 2.",
      "TCP": "O TCP é camada 4."}),
    ("Que método de acesso usa o Wi-Fi?",
     "O Wi-Fi usa <b>CSMA/CA</b> (Collision Avoidance): antes de transmitir, ouve o canal e espera um tempo aleatório para <i>evitar</i> colisões, porque um rádio não consegue detetá-las enquanto transmite. A Ethernet antiga (half-duplex) usava CSMA/CD.",
     {"CSMA/CA": "Certo: evita colisões, porque no rádio não se consegue detetá-las.",
      "CSMA/CD": "CSMA/CD (deteção) era da Ethernet half-duplex com hubs.",
      "Token": "A passagem de testemunho era do Token Ring, já em desuso.",
      "Nenhum": "Num meio partilhado como o ar é sempre preciso um método de acesso."}),
    ("O FCS corrige as tramas com erros.",
     "Falso. O FCS só <b>deteta</b> erros: o recetor recalcula o CRC e, se não coincidir, descarta a trama. Quem recupera a perda é o TCP, retransmitindo. Confusão comum: confundir deteção com correção."),
    ("Comunicação em que os dois lados falam ao mesmo tempo é…",
     "<b>Full-duplex</b>: os dois lados transmitem e recebem em simultâneo (como um telefone). <b>Half-duplex</b>: um de cada vez (como um walkie-talkie). <b>Simplex</b>: só num sentido (como a rádio FM).",
     {"Full-duplex": "Certo: transmitir e receber ao mesmo tempo.",
      "Half-duplex": "Em half-duplex fala um de cada vez.",
      "Simplex": "Simplex é só num sentido.",
      "Broadcast": "Broadcast é enviar para todos, não um modo de duplex."}),
    ("Quantos bits tem um endereço MAC?",
     "O endereço MAC tem <b>48 bits</b> (6 bytes), escritos em 12 dígitos hex: 24 bits de OUI (fabricante) + 24 bits do fabricante.",
     {"48": "Certo: 6 bytes = 48 bits.",
      "32": "32 bits é o IPv4.",
      "64": "64 bits é o EUI-64 usado no IPv6.",
      "128": "128 bits é o IPv6."}),
    ("O MAC de broadcast é…",
     "O MAC de <b>broadcast</b> tem todos os 48 bits a 1: <b>FFFF.FFFF.FFFF</b>. Uma trama com este destino é entregue a todos os equipamentos da mesma VLAN (ex.: ARP Request).",
     {"FFFF.FFFF.FFFF": "Certo: todos os bits a 1 = todos os equipamentos.",
      "0000.0000.0000": "Todos a 0 não é endereço de broadcast (não é usado como destino).",
      "0100.5E00.0001": "Começa por 0100.5E: é um MAC multicast IPv4 (grupo 224.0.0.1).",
      "FF00.0000.0000": "Só o primeiro byte a FF não é broadcast."}),
    ("O ARP Request é enviado em…",
     "O ARP Request vai em <b>broadcast</b> (MAC de destino FFFF.FFFF.FFFF) porque o PC ainda não sabe o MAC do destino: pergunta a todos “quem tem este IP?”. Só o dono responde, em <b>unicast</b> (ARP Reply).",
     {"Broadcast": "Certo: vai para todos, porque o MAC do destino ainda é desconhecido.",
      "Unicast": "Unicast é a resposta (ARP Reply); o pedido não pode ser unicast sem saber o MAC.",
      "Multicast": "O ARP não usa grupos multicast.",
      "Anycast": "Anycast é um conceito de IPv6/routing, não do ARP.",
      "Multicast de grupo": "O ARP não usa multicast; vai para todos em broadcast."}),
    ("Que comando mostra a tabela de endereços MAC num switch Cisco?",
     "<code>show mac address-table</code> (modo EXEC privilegiado) lista VLAN, MAC, tipo (DYNAMIC/STATIC) e porta de cada endereço aprendido. Em IOS antigos escrevia-se <code>show mac-address-table</code>. Útil para descobrir em que porta está um equipamento."),
    ("Os primeiros 24 bits do MAC identificam o fabricante (OUI).",
     "Verdadeiro. O OUI (Organizationally Unique Identifier) são os primeiros 3 bytes, atribuídos pelo IEEE; ex.: 00:1A:2B. Os outros 24 bits são escolhidos pelo fabricante. Confusão comum: pensar que o MAC indica a rede ou a localização."),
    ("O switch aprende endereços a partir do…",
     "Quando uma trama entra numa porta, o switch lê o <b>MAC de origem</b> e regista “este MAC está nesta porta”. O MAC de <i>destino</i> é usado depois, para decidir para onde enviar.",
     {"MAC de origem": "Certo: aprende sempre pela origem (quem enviou e por onde chegou).",
      "MAC de destino": "O destino serve para encaminhar, não para aprender.",
      "IP de origem": "O switch L2 não olha para IPs.",
      "FCS": "O FCS serve para detetar erros, não para aprender endereços."}),
    ("O que faz o switch com uma trama para um MAC desconhecido?",
     "Se o MAC de destino não está na tabela, o switch faz <b>flooding</b> (unknown unicast): envia a trama por todas as portas da mesma VLAN, exceto aquela por onde chegou. Quando o destino responder, o switch aprende onde ele está.",
     {"Inunda pela VLAN": "Certo: unknown unicast flooding em todas as portas da VLAN.",
      "Descarta": "Descartar faria a comunicação falhar; o switch prefere inundar.",
      "Envia ao router": "O switch L2 não decide por router; isso é trabalho da camada 3.",
      "Responde com ARP": "O switch não responde a ARP pelos outros; o ARP é entre hosts."}),
    ("Quantos domínios de broadcast tem um switch de 24 portas, todas na VLAN 1?",
     "Um broadcast chega a todas as portas da mesma VLAN, por isso <b>uma VLAN = um domínio de broadcast</b>. Com as 24 portas na VLAN 1 há <b>1</b> domínio de broadcast (mas 24 domínios de colisão, um por porta).",
     {"1": "Certo: uma só VLAN = um só domínio de broadcast.",
      "2": "Não há nada que divida o broadcast em dois.",
      "24": "24 é o número de domínios de colisão (um por porta), não de broadcast.",
      "48": "Não há base para 48."}),
    ("O tempo padrão de envelhecimento da tabela MAC nos switches Cisco é 300 segundos.",
     "Verdadeiro. Se um MAC não enviar tramas durante <b>300 s (5 min)</b>, a entrada dinâmica é apagada da tabela. Altera-se com <code>mac address-table aging-time</code>. Confusão comum: trocar com o cache ARP (4 horas nos routers Cisco)."),
    ("Um PC 192.168.1.10/24 envia para 10.0.0.5. Para onde vai o pacote?",
     "O PC faz a conta com a sua máscara: a sua rede é 192.168.1.0/24 e 10.0.0.5 <b>não pertence</b> a ela. Destino remoto → o pacote vai para o <b>gateway por defeito</b>, que trata de o encaminhar.",
     {"Para o gateway por defeito": "Certo: destino noutra rede → gateway.",
      "Diretamente para 10.0.0.5": "Só envia diretamente se o destino estiver na mesma rede.",
      "Para o switch": "O switch não é destino; ele só transporta a trama até ao gateway.",
      "É descartado": "Com gateway configurado o pacote não é descartado."}),
    ("O IP garante que todos os pacotes chegam.",
     "Falso. O IP é de <b>melhor esforço</b> (best effort): tenta entregar, mas não confirma nem retransmite. A fiabilidade é dada pelo <b>TCP</b> (confirmações e retransmissões). Confusão comum: atribuir ao IP funções do TCP."),
    ("O que acontece quando o TTL chega a 0?",
     "O router que põe o TTL a 0 <b>descarta o pacote</b> e envia à origem um <b>ICMP Time Exceeded</b>. Isto evita pacotes eternos em loops — e é o truque que o traceroute usa para descobrir cada salto.",
     {"O pacote é descartado e é enviado ICMP Time Exceeded": "Certo: descarta e avisa a origem.",
      "O pacote acelera": "O TTL não tem a ver com velocidade.",
      "O router guarda-o": "Os routers não guardam pacotes expirados.",
      "Nada": "Se nada acontecesse, um loop de routing faria o pacote circular para sempre."}),
    ("Na tabela de um router, a letra L significa…",
     "Em <code>show ip route</code>, <b>C</b> é a rede ligada diretamente (ex.: 192.168.1.0/24) e <b>L</b> é a rota <b>local</b> /32 com o IP da própria interface (ex.: 192.168.1.1/32).",
     {"Local: o IP da própria interface": "Certo: rota /32 do IP configurado na interface.",
      "Loop": "Não existe código de “loop” na tabela de routing.",
      "LAN": "As redes LAN ligadas aparecem com C (connected).",
      "Link-state": "Os protocolos link-state aparecem com o seu código (O para OSPF)."}),
    ("O PC quer falar com 8.8.8.8. De quem pede o MAC por ARP?",
     "8.8.8.8 está fora da rede local, por isso a trama tem de ir para o <b>gateway</b>. O PC pede por ARP o MAC do gateway (não o de 8.8.8.8, que nunca responderia a um broadcast local).",
     {"Do gateway": "Certo: destino remoto → precisa do MAC do gateway.",
      "De 8.8.8.8": "O ARP só funciona dentro da rede local; 8.8.8.8 está na Internet.",
      "Do switch": "O switch não é o destino da trama.",
      "De ninguém": "Sem o MAC do gateway não consegue construir a trama."}),
    ("Que mensagem IPv6 substitui o ARP Request?",
     "No IPv6 não há ARP: o protocolo <b>NDP</b> (sobre ICMPv6) usa <b>Neighbor Solicitation</b> (enviado para um multicast solicited-node) para perguntar o MAC, e <b>Neighbor Advertisement</b> para responder.",
     {"Neighbor Solicitation": "Certo: NS pergunta o MAC de um IPv6 vizinho.",
      "Router Advertisement": "O RA anuncia o router e o prefixo (para SLAAC).",
      "Echo Request": "Echo Request é o ping.",
      "DHCP Discover": "É do DHCPv4, para obter configuração IP."}),
    ("Que comando mostra a tabela ARP de um router Cisco?",
     "<code>show ip arp</code> (ou <code>show arp</code>) no modo EXEC privilegiado lista IP, idade, MAC e interface de cada vizinho. Num PC Windows o equivalente é <code>arp -a</code>."),
]
