"""Explicações detalhadas do quiz (parte 4: serviços, segurança básica, verificação, switching, VLAN, STP, EtherChannel, DHCP, FHRP, Wi-Fi)."""

ENTRADAS = [
    ("Que serviço permite que toda a casa use um único IP público?",
     "O <b>NAT</b> (na variante PAT/overload) troca os IPs privados dos equipamentos de casa pelo único IP público do router, distinguindo as ligações pela porta de origem. É por isso que dezenas de aparelhos navegam com um só IP público.",
     {"NAT": "Certo: NAT com overload (PAT) partilha um IP público por muitos privados.",
      "DNS": "O DNS traduz nomes em IPs; não partilha endereços.",
      "Syslog": "O Syslog envia mensagens de registo para um servidor.",
      "QoS": "A QoS dá prioridade a tráfego (ex.: voz); não traduz endereços."}),
    ("O NTP serve para sincronizar a hora.",
     "Verdadeiro. O <b>NTP</b> (Network Time Protocol, UDP 123) acerta o relógio dos equipamentos com uma fonte fiável. É essencial para que os logs tenham a hora certa, para certificados e autenticação. Confusão comum: confundir com SNMP (gestão) ou Syslog (registos)."),
    ("Que registo DNS indica o servidor de correio?",
     "Tipos de registo DNS: <b>A</b> (nome → IPv4), <b>AAAA</b> (nome → IPv6), <b>MX</b> (servidor de correio do domínio), <b>CNAME</b> (alias para outro nome), <b>PTR</b> (IP → nome, DNS inverso).",
     {"MX": "Certo: Mail Exchanger, indica para onde vai o e-mail do domínio.",
      "A": "O registo A dá o IPv4 de um nome.",
      "CNAME": "O CNAME é um nome alternativo (alias).",
      "PTR": "O PTR faz a resolução inversa (IP → nome)."}),
    ("Que protocolo mantém o e-mail no servidor e sincroniza vários dispositivos?",
     "O <b>IMAP</b> (porta 143, ou 993 com TLS) deixa as mensagens no servidor e sincroniza pastas e “lido/não lido” entre telemóvel e PC. O <b>POP3</b> descarrega e normalmente apaga do servidor. O <b>SMTP</b> serve para <i>enviar</i>.",
     {"IMAP": "Certo: mantém o correio no servidor e sincroniza vários dispositivos.",
      "POP3": "O POP3 descarrega para um dispositivo; não sincroniza bem entre vários.",
      "SMTP": "O SMTP envia e-mail entre servidores; não serve para ler a caixa.",
      "FTP": "O FTP transfere ficheiros, não e-mail."}),
    ("Porta do HTTPS?",
     "O <b>HTTPS</b> usa <b>TCP 443</b>; o HTTP sem cifra usa a 80.",
     {"443": "Certo: HTTPS = TCP 443.",
      "80": "80 é o HTTP sem cifra.",
      "21": "21 é o FTP (controlo).",
      "53": "53 é o DNS."}),
    ("No modelo P2P um equipamento pode ser cliente e servidor ao mesmo tempo.",
     "Verdadeiro. No modelo <b>peer-to-peer</b> cada equipamento partilha recursos e também os pede (ex.: partilha de pastas num grupo de trabalho Windows, BitTorrent). Confusão comum: achar que só o modelo cliente-servidor tem servidores."),
    ("Na comparação com uma casa, a firewall é…",
     "A <b>firewall</b> é o <b>porteiro</b>: verifica cada ligação e decide, segundo regras, quem pode entrar e sair. Por defeito, só deixa entrar respostas a ligações pedidas de dentro.",
     {"O porteiro": "Certo: decide quem entra e quem sai segundo regras.",
      "O cofre": "O cofre seria mais parecido com a cifra ou o armazenamento protegido dos dados.",
      "A janela": "Uma janela aberta seria uma vulnerabilidade, não a proteção.",
      "O carteiro": "O carteiro é o router: transporta e entrega."}),
    ("Um SMS falso que pede para clicar num link é…",
     "<b>Phishing</b> é enganar alguém para revelar dados ou clicar num link malicioso, fingindo ser uma entidade de confiança. Por SMS chama-se <b>smishing</b>; por telefone, <b>vishing</b>.",
     {"Phishing": "Certo: engenharia social por mensagem falsa (por SMS: smishing).",
      "DHCP": "O DHCP é um serviço que atribui IPs.",
      "VLAN": "Uma VLAN é uma rede lógica num switch.",
      "Backup": "Backup é uma cópia de segurança — uma defesa, não um ataque."}),
    ("Cifrar dados protege-os mesmo que alguém os intercete.",
     "Verdadeiro. A cifra transforma os dados num formato ilegível sem a <b>chave</b>: quem os interceta (ex.: num Wi-Fi público) vê apenas lixo. É por isso que se usa SSH em vez de Telnet e HTTPS em vez de HTTP. Confusão comum: a cifra protege a confidencialidade, não impede a interceção em si."),
    ("Que ataque procura portas abertas num servidor?",
     "Um <b>ataque de reconhecimento</b> recolhe informação antes do ataque a sério: varrimento de pings, <b>varrimento de portas</b> (ex.: com nmap), consultas DNS/whois. Serve para descobrir serviços vulneráveis.",
     {"Reconhecimento": "Certo: o varrimento de portas é a fase de reconhecimento.",
      "DoS": "Um DoS tenta deitar o serviço abaixo com excesso de tráfego.",
      "Ransomware": "Ransomware cifra os ficheiros da vítima e pede resgate.",
      "Phishing": "Phishing engana pessoas por mensagens falsas."}),
    ("Que comando obriga palavras-passe com pelo menos 10 caracteres?",
     "<code>security passwords min-length 10</code>, no modo de configuração global, faz o IOS recusar novas palavras-passe (enable, username, linhas) com menos de 10 caracteres. Não altera as que já existem."),
    ("Defesa em profundidade significa usar várias camadas de proteção.",
     "Verdadeiro. Nenhuma medida sozinha chega: combina-se firewall, ACLs, port security, palavras-passe fortes, SSH, atualizações, backups e formação dos utilizadores. Se uma camada falhar, outra trava o ataque."),
    ("Porque se desliga o Telnet?",
     "O <b>Telnet</b> (TCP 23) envia tudo — incluindo utilizador e palavra-passe — em <b>texto claro</b>; qualquer pessoa com o Wireshark no caminho lê-os. O SSH (TCP 22) cifra a sessão. Por isso usa-se <code>transport input ssh</code>.",
     {"Envia palavras-passe em texto claro": "Certo: sem cifra, as credenciais podem ser capturadas.",
      "É lento": "A velocidade não é o problema; é a falta de cifra.",
      "Não funciona em IPv6": "O Telnet funciona em IPv6.",
      "É caro": "É gratuito; o custo é a falta de segurança."}),
    ("Uma interface mostra 'administratively down'. O que fazer?",
     "<b>administratively down</b> significa que a interface foi desligada por configuração (<code>shutdown</code>) — não é avaria física. Resolve-se com <code>no shutdown</code> no modo de interface.",
     {"Executar no shutdown": "Certo: está desligada por configuração; no shutdown liga-a.",
      "Trocar o cabo": "Um problema de cabo mostraria “down/down”, não “administratively down”.",
      "Mudar o duplex": "O duplex não desliga a interface administrativamente.",
      "Reiniciar": "Reiniciar não resolve: a interface voltaria em shutdown se a config estiver guardada assim."}),
    ("Muitos 'late collisions' indicam normalmente…",
     "<b>Late collisions</b> (colisões depois dos primeiros 64 bytes) aparecem quando um lado está em <b>half-duplex</b> e o outro em <b>full-duplex</b> — duplex mismatch. Em full-duplex não deveria haver colisões nenhumas.",
     {"Duplex mismatch": "Certo: um lado half, o outro full.",
      "Cabo cruzado": "Um cabo errado normalmente impede o link de subir, não gera late collisions.",
      "VLAN errada": "Uma VLAN errada não gera colisões; só isola o tráfego.",
      "Falta de rota": "A falta de rota é um problema de camada 3, sem colisões."}),
    ("Que comando mostra os vizinhos Cisco diretamente ligados?",
     "<code>show cdp neighbors</code> lista os vizinhos Cisco ligados diretamente: nome, interface local, modelo e porta remota. Com <code>detail</code> mostra também o IP e a versão do IOS. Útil para mapear a rede sem plantas."),
    ("LLDP é um protocolo proprietário da Cisco.",
     "Falso. O <b>LLDP</b> é norma aberta <b>IEEE 802.1AB</b> e funciona entre marcas diferentes. O proprietário da Cisco é o <b>CDP</b>. Ativa-se com <code>lldp run</code>."),
    ("No resultado de um ping Cisco, '.' significa…",
     "No ping do IOS: <b>!</b> resposta recebida, <b>.</b> <b>timeout</b> (nenhuma resposta dentro do tempo), <b>U</b> destino inalcançável. O primeiro “.” costuma ser o tempo do ARP — normal.",
     {"Timeout": "Certo: o pacote não teve resposta dentro do tempo limite.",
      "Sucesso": "Sucesso é “!”.",
      "Destino inalcançável": "Inalcançável é “U”.",
      "TTL expirado": "TTL expirado aparece como “&amp;”."}),
    ("Onde fica guardado normalmente o ficheiro do IOS?",
     "Memórias de um router Cisco: <b>flash</b> (imagem do IOS), <b>NVRAM</b> (startup-config), <b>RAM</b> (running-config, tabelas) e <b>ROM</b> (bootstrap, POST, ROMMON).",
     {"Flash": "Certo: a imagem do IOS fica na flash (dir flash:).",
      "NVRAM": "Na NVRAM fica a startup-config.",
      "RAM": "O IOS é copiado para a RAM ao arrancar, mas fica guardado na flash.",
      "ROM": "Na ROM fica o bootstrap e o ROMMON."}),
    ("Que valor do configuration register ignora a startup-config?",
     "O <b>configuration register</b> controla o arranque. <b>0x2102</b> é o normal (carrega a startup-config); <b>0x2142</b> arranca <b>sem ler a startup-config</b> — usado na recuperação de palavras-passe. Depois volta-se a pôr 0x2102.",
     {"0x2142": "Certo: ignora a NVRAM; usado na recuperação de palavra-passe.",
      "0x2102": "0x2102 é o valor normal, que carrega a startup-config.",
      "0x2100": "0x2100 arranca no modo ROMMON.",
      "0x0000": "Não é o valor para ignorar a configuração."}),
    ("Que comando mostra a versão do IOS, uptime e o configuration register?",
     "<code>show version</code> mostra a versão do IOS, o tempo ligado (uptime), o modelo, a memória, as interfaces e, na última linha, o configuration register (ex.: 0x2102)."),
    ("O Packet Tracer usa as imagens IOS reais da Cisco.",
     "Falso. O Packet Tracer é um <b>simulador</b>: reproduz o comportamento do IOS, com comandos limitados. Para imagens reais usa-se um <b>emulador</b> como o Cisco CML ou o GNS3/EVE-NG com imagens legítimas."),
    ("Para limpar a configuração de um switch usado deve…",
     "A configuração está na startup-config (NVRAM), mas as VLANs ficam no ficheiro <b>vlan.dat</b> na flash. Para deixar o switch “de fábrica”: <code>write erase</code> (ou erase startup-config), <code>delete flash:vlan.dat</code> e <code>reload</code> sem guardar.",
     {"write erase, delete vlan.dat e reload": "Certo: apaga a config, as VLANs e reinicia.",
      "Só reload": "Reiniciar volta a carregar a startup-config antiga.",
      "copy run start": "Isso guarda a configuração atual — o contrário de limpar.",
      "no shutdown": "Só liga interfaces; não limpa nada."}),
    ("Um técnico configura 'transport input ssh' mas o SSH não funciona. A causa mais provável é…",
     "O servidor SSH só arranca quando existem <b>chaves RSA</b>, e estas exigem <code>hostname</code> e <code>ip domain-name</code> antes de <code>crypto key generate rsa</code>. Também é preciso <code>login local</code> e um utilizador.",
     {"Faltam as chaves RSA": "Certo: sem chaves RSA o servidor SSH não arranca.",
      "Falta o comando no shutdown na vty": "As linhas vty não têm shutdown/no shutdown.",
      "O CDP está ativo": "O CDP não interfere com o SSH.",
      "A consola tem palavra-passe": "A palavra-passe da consola não afeta o acesso remoto."}),
    ("Interface up/down numa ligação serial. Suspeita principal?",
     "<b>up/down</b> = camada 1 OK (há sinal), camada 2 falha. Numa serial, a causa típica é <b>encapsulamento diferente</b> nas pontas (HDLC num lado, PPP no outro) ou falta de keepalives/clock.",
     {"Encapsulamento diferente nas pontas": "Certo: camada 1 sobe, mas a camada 2 não se entende.",
      "Cabo desligado": "Com o cabo desligado ficava down/down.",
      "Falta no shutdown": "Sem no shutdown ficava administratively down.",
      "IP duplicado": "Um IP duplicado é camada 3; o protocolo de linha ficava up."}),
    ("Escreva o comando para gerar chaves RSA de 2048 bits.",
     "<code>crypto key generate rsa modulus 2048</code>, no modo de configuração global, gera o par de chaves para o SSH. Sem <code>modulus</code>, o IOS pergunta o tamanho. Para SSH versão 2 são precisos pelo menos 768 bits; hoje recomenda-se 2048."),
    ("Muitos CRC numa porta indicam normalmente…",
     "Erros <b>CRC</b> são tramas que chegam corrompidas (o FCS não bate certo). A causa habitual é <b>física</b>: cabo danificado, mal cravado, demasiado longo ou interferência elétrica.",
     {"Problema físico (cabo/interferência)": "Certo: CRC indica corrupção dos bits na camada 1.",
      "Falta de VLAN": "Uma VLAN errada não corrompe tramas.",
      "Senha errada": "Senhas não têm nada a ver com erros de trama.",
      "DHCP": "O DHCP é camada 7; não causa CRC."}),
    ("Late collisions indicam normalmente…",
     "As <b>late collisions</b> surgem quando um lado está em half-duplex e o outro em full-duplex (<b>duplex mismatch</b>). Confirme com <code>show interfaces</code> e ponha os dois lados em auto ou ambos em full.",
     {"Duplex mismatch": "Certo: um lado half, outro full.",
      "VLAN errada": "VLAN errada isola tráfego, não gera colisões.",
      "Falta de rota": "Falta de rota é camada 3.",
      "Senha errada": "Nada a ver com colisões."}),
    ("Que filtro mostra só as linhas que contêm uma palavra?",
     "No IOS, o filtro <code>| include palavra</code> depois de um show mostra só as linhas que contêm essa palavra. Outros: <code>| exclude</code>, <code>| begin</code>, <code>| section</code>. Ex.: <code>show running-config | include hostname</code>."),
    ("A gestão remota do switch usa uma SVI.",
     "Verdadeiro. Um switch L2 recebe o IP de gestão numa <b>SVI</b> (ex.: <code>interface vlan 99</code>), mais <code>ip default-gateway</code> para ser alcançado de outras redes. Boa prática: usar uma VLAN de gestão própria, não a VLAN 1."),
    ("Quantos domínios de broadcast tem um switch com 3 VLANs?",
     "Cada VLAN é um <b>domínio de broadcast</b> separado: um broadcast na VLAN 10 não chega à 20. Com 3 VLANs há <b>3</b> domínios de broadcast.",
     {"3": "Certo: uma VLAN = um domínio de broadcast.",
      "1": "Seria 1 só se todas as portas estivessem na mesma VLAN.",
      "24": "24 seria o número de domínios de colisão num switch de 24 portas.",
      "0": "Há sempre pelo menos um domínio de broadcast."}),
    ("Que método verifica o FCS antes de encaminhar?",
     "No <b>store-and-forward</b> o switch recebe a trama inteira, verifica o FCS e só então encaminha (descarta as corrompidas). O <b>cut-through</b> começa a enviar logo após ler o MAC de destino; o <b>fragment-free</b> espera pelos primeiros 64 bytes.",
     {"Store-and-forward": "Certo: guarda a trama inteira e verifica o FCS.",
      "Cut-through": "Encaminha logo após o MAC de destino, sem verificar o FCS.",
      "Fragment-free": "Só verifica os primeiros 64 bytes (zona das colisões), não o FCS.",
      "Flooding": "Flooding é inundar portas, não um método de verificação."}),
    ("Quantos domínios de colisão tem um hub de 8 portas?",
     "Um <b>hub</b> repete os bits por todas as portas: todas partilham o mesmo meio, por isso há <b>1</b> domínio de colisão (e 1 de broadcast). Um switch de 8 portas teria 8 domínios de colisão.",
     {"1": "Certo: todas as portas do hub partilham o meio.",
      "8": "8 seria num switch (uma por porta).",
      "16": "Não há base para 16.",
      "0": "Num hub há sempre colisões possíveis: 1 domínio."}),
    ("Cada porta de um switch é um domínio de colisão separado.",
     "Verdadeiro. O switch isola cada porta: só o equipamento ligado nela pode colidir com o switch. E em <b>full-duplex</b> nem isso acontece — não há colisões. Confusão comum: confundir domínio de colisão (por porta) com domínio de broadcast (por VLAN)."),
    ("O que faz o switch com uma mensagem para um equipamento que conhece?",
     "Se o MAC de destino está na tabela, o switch envia a trama <b>só pela porta</b> desse equipamento (forwarding) — é isto que o torna mais eficiente e seguro do que um hub.",
     {"Envia só para a porta desse equipamento": "Certo: consulta a tabela MAC e encaminha só para lá.",
      "Envia para todas as portas": "Isso é o que faz com destinos desconhecidos ou broadcast.",
      "Apaga-a": "Só descarta em casos especiais (ex.: destino na mesma porta de origem).",
      "Envia para a Internet": "O switch não decide caminhos para a Internet; isso é o router."}),
    ("Para que serve uma VLAN?",
     "Uma <b>VLAN</b> divide um switch físico em várias redes lógicas separadas: cada VLAN é um domínio de broadcast próprio. Ex.: VLAN 10 Contabilidade, VLAN 20 Convidados — no mesmo switch, sem se verem.",
     {"Separar redes no mesmo switch": "Certo: cria redes lógicas separadas no mesmo equipamento.",
      "Aumentar o Wi-Fi": "O alcance do Wi-Fi depende dos APs, não das VLANs.",
      "Carregar telemóveis": "Nada a ver com VLANs.",
      "Substituir o router": "Para comunicar entre VLANs continua a ser preciso um router ou switch L3."}),
    ("Equipamentos em VLANs diferentes comunicam diretamente sem router.",
     "Falso. VLANs diferentes são redes diferentes (normalmente sub-redes IP diferentes). Para comunicarem é preciso <b>routing entre VLANs</b>: router-on-a-stick ou switch multicamada com SVIs."),
    ("Que comando atribui a porta à VLAN 10 (no modo interface)?",
     "<code>switchport access vlan 10</code>, no modo de interface, coloca a porta de acesso na VLAN 10. Deve vir acompanhado de <code>switchport mode access</code>. Se a VLAN não existir, o IOS cria-a."),
    ("Quantos bits tem o VLAN ID na etiqueta 802.1Q?",
     "A etiqueta 802.1Q tem 4 bytes; dentro dela o <b>VLAN ID</b> ocupa <b>12 bits</b> → 4096 valores (0 e 4095 reservados, 1–4094 utilizáveis). Os 3 bits PCP servem para prioridade (QoS).",
     {"12": "Certo: 2¹² = 4096 valores.",
      "8": "8 bits só dariam 256 VLANs.",
      "10": "10 bits dariam 1024; não é o tamanho do campo.",
      "16": "16 bits é o TPID (0x8100), não o VLAN ID."}),
    ("Dois switches com 'dynamic auto' nas duas pontas formam…",
     "O DTP com <b>dynamic auto</b> aceita formar trunk se o outro <i>pedir</i>, mas não pede. Dois “auto” ficam à espera um do outro → a ligação fica em <b>access</b>. Com desirable num dos lados formava trunk.",
     {"Access": "Certo: nenhum dos lados toma a iniciativa.",
      "Trunk": "Precisaria de pelo menos um lado em desirable ou trunk.",
      "EtherChannel": "EtherChannel é configurado com channel-group, não pelo DTP.",
      "Erro": "Não há erro: simplesmente fica em access."}),
    ("O tráfego da VLAN nativa atravessa o trunk sem etiqueta.",
     "Verdadeiro. No 802.1Q, as tramas da <b>VLAN nativa</b> (por defeito VLAN 1) vão <b>sem etiqueta</b>. Se as duas pontas tiverem nativas diferentes, o tráfego mistura-se e aparece o aviso “native VLAN mismatch” do CDP."),
    ("Que comando mostra as VLANs e as portas atribuídas?",
     "<code>show vlan brief</code> lista cada VLAN (número, nome, estado) e as portas de acesso que lhe pertencem. As portas trunk não aparecem aqui — veja-as com <code>show interfaces trunk</code>."),
    ("Para adicionar a VLAN 30 a um trunk sem remover as outras:",
     "<code>switchport trunk allowed vlan 30</code> <b>substitui</b> a lista inteira (ficava só a 30!). Para acrescentar usa-se <code>switchport trunk allowed vlan add 30</code>; para retirar, <code>remove</code>.",
     {"switchport trunk allowed vlan add 30": "Certo: o “add” acrescenta à lista existente.",
      "switchport trunk allowed vlan 30": "Substitui a lista: o trunk passava a levar só a VLAN 30 (erro clássico que corta a rede).",
      "vlan 30 trunk": "Não é um comando válido.",
      "switchport access vlan 30": "Configura uma porta de acesso, não a lista do trunk."}),
    ("Que comando associa uma subinterface à VLAN 30?",
     "<code>encapsulation dot1Q 30</code>, dentro de uma subinterface (ex.: <code>interface g0/0.30</code>), diz ao router que essa subinterface recebe e envia tramas com etiqueta 802.1Q da VLAN 30. Depois configura-se o IP (gateway da VLAN). É a base do router-on-a-stick."),
    ("Que comando ativa o encaminhamento IP num switch multicamada?",
     "<code>ip routing</code>, no modo de configuração global, liga o routing IPv4 num switch L3 (desligado por defeito). Sem ele, as SVIs têm IP mas o switch não encaminha entre VLANs."),
    ("Uma SVI pode ficar up/up mesmo sem nenhuma porta ativa na sua VLAN.",
     "Falso. A SVI só fica <b>up/up</b> se a VLAN existir e houver <b>pelo menos uma porta ativa</b> (access ou trunk que a permita) nessa VLAN, além do <code>no shutdown</code>."),
    ("No router-on-a-stick, a porta do switch ligada ao router deve estar em modo…",
     "No <b>router-on-a-stick</b> um único cabo leva todas as VLANs até ao router, que tem uma subinterface por VLAN. Por isso a porta do switch tem de ser <b>trunk</b> (802.1Q).",
     {"trunk": "Certo: transporta várias VLANs com etiquetas 802.1Q.",
      "access": "Uma porta access só leva uma VLAN.",
      "routed": "Uma porta routed (no switchport) é de camada 3, não leva VLANs.",
      "voice": "A VLAN de voz é para telefones IP em portas de acesso."}),
    ("Que comando transforma uma porta de switch L3 numa porta roteada?",
     "<code>no switchport</code>, no modo de interface de um switch multicamada, transforma a porta numa <b>porta roteada</b> (camada 3), que aceita <code>ip address</code> como uma interface de router."),
    ("Que switch se torna root bridge?",
     "Ganha o switch com o <b>menor Bridge ID</b> = prioridade (por defeito 32768 + VLAN) seguida do MAC. Com prioridades iguais, ganha o MAC mais baixo. Para escolher a root, baixa-se a prioridade (<code>spanning-tree vlan 1 root primary</code>).",
     {"O de menor Bridge ID": "Certo: menor prioridade e, em empate, menor MAC.",
      "O de maior MAC": "É o contrário: em empate ganha o menor MAC.",
      "O mais rápido": "A velocidade influencia o custo dos caminhos, não a eleição da root.",
      "O que tem mais portas": "O número de portas não conta."}),
    ("Qual o custo STP de uma ligação de 1 Gbit/s?",
     "Custos STP (curtos, 802.1D): 10 Mbit/s = 100, 100 Mbit/s = <b>19</b>, <b>1 Gbit/s = 4</b>, 10 Gbit/s = 2. O caminho para a root com menor custo total ganha.",
     {"4": "Certo: 1 Gbit/s custa 4.",
      "19": "19 é o custo de 100 Mbit/s.",
      "2": "2 é o custo de 10 Gbit/s.",
      "100": "100 é o custo de 10 Mbit/s."}),
    ("Que funcionalidade desliga uma porta PortFast que recebe uma BPDU?",
     "O <b>BPDU Guard</b> põe em <b>err-disabled</b> uma porta de acesso que receba BPDUs (sinal de que alguém ligou um switch onde devia estar um PC). Usa-se com PortFast: <code>spanning-tree bpduguard enable</code>.",
     {"BPDU Guard": "Certo: BPDU recebida → porta em err-disabled.",
      "Root Guard": "O Root Guard impede que um switch se torne root por aquela porta, mas não a desliga por qualquer BPDU.",
      "Loop Guard": "O Loop Guard protege contra a falta de BPDUs em portas bloqueadas.",
      "Port Security": "O port security limita MACs, não reage a BPDUs."}),
    ("A prioridade STP tem de ser um múltiplo de 4096.",
     "Verdadeiro. Dos 16 bits da prioridade, os 12 de baixo são o <b>extended system ID</b> (n.º da VLAN). Só sobram 4 bits configuráveis, por isso a prioridade sobe em passos de <b>4096</b> (0, 4096, 8192 … 61440)."),
    ("Em quanto tempo converge normalmente o RSTP?",
     "O <b>RSTP</b> (802.1w) negocia ativamente com os vizinhos (proposal/agreement) e tem portas alternativas prontas, convergindo em <b>1–2 s ou menos</b>. O STP clássico demorava 30 a 50 s.",
     {"1–2 s": "Certo: o RSTP converge em poucos segundos ou menos.",
      "50 s": "50 s é o pior caso do STP clássico (20 s max age + 15 + 15).",
      "30 s": "30 s é o listening + learning do STP clássico.",
      "5 min": "5 min é o envelhecimento da tabela MAC, não o STP."}),
    ("Que comando ativa PortFast numa interface?",
     "<code>spanning-tree portfast</code>, no modo de interface, faz uma porta de acesso passar logo para forwarding, sem esperar 30 s. Usa-se só em portas ligadas a PCs/servidores, nunca entre switches."),
    ("PCs na VLAN 10 de SW1 não falam com PCs na VLAN 10 de SW2. As VLANs existem nos dois. Verificação a fazer primeiro?",
     "Se as VLANs existem nos dois, o próximo suspeito é a ligação entre eles: <code>show interfaces trunk</code> mostra se o trunk está ativo, a VLAN nativa e se a <b>VLAN 10 está permitida</b> e em forwarding.",
     {"show interfaces trunk": "Certo: confirma se o trunk está up e leva a VLAN 10.",
      "show ip route": "É um problema de camada 2 na mesma VLAN; a tabela de routing não ajuda.",
      "show cdp neighbors": "Mostra que o vizinho existe, mas não se o trunk leva a VLAN 10.",
      "show version": "Mostra a versão do IOS, irrelevante aqui."}),
    ("Que estado STP existe no 802.1D mas não no RSTP?",
     "Estados 802.1D: blocking, <b>listening</b>, learning, forwarding, disabled. O RSTP simplificou para <b>discarding</b>, learning e forwarding — o listening desapareceu.",
     {"Listening": "Certo: o RSTP juntou blocking, listening e disabled em discarding.",
      "Forwarding": "Forwarding existe nos dois.",
      "Learning": "Learning existe nos dois.",
      "Discarding": "Discarding é do RSTP, não do 802.1D."}),
    ("PAgP e LACP podem ser misturados no mesmo EtherChannel.",
     "Falso. As duas pontas têm de usar o <b>mesmo protocolo</b>: PAgP (Cisco, auto/desirable) ou LACP (aberto, active/passive). Um lado em desirable e o outro em active não formam canal."),
    ("Root bridge da VLAN 1 tem prioridade 32769. Que prioridade configurada tem?",
     "A prioridade mostrada = prioridade configurada + <b>extended system ID</b> (n.º da VLAN). 32769 − 1 (VLAN 1) = <b>32768</b>, o valor por defeito.",
     {"32768": "Certo: 32768 + 1 (VLAN) = 32769.",
      "32769": "Esse é o valor mostrado, que já inclui o ID da VLAN.",
      "4096": "4096 é o passo da prioridade, não o valor configurado.",
      "1": "1 é o número da VLAN, não a prioridade."}),
    ("Que combinação LACP NÃO forma EtherChannel?",
     "No LACP, <b>active</b> envia propostas e <b>passive</b> só responde. Active/active e active/passive formam canal; <b>passive/passive</b> não, porque nenhum toma a iniciativa.",
     {"passive / passive": "Certo: os dois esperam e ninguém começa.",
      "active / active": "Forma: os dois negociam.",
      "active / passive": "Forma: o active propõe e o passive responde.",
      "Todas formam": "Passive/passive não forma."}),
    ("Qual o protocolo aberto de agregação?",
     "O <b>LACP</b> (IEEE 802.3ad, hoje 802.1AX) é a norma aberta para agregar ligações e funciona entre fabricantes. O <b>PAgP</b> é proprietário da Cisco.",
     {"LACP": "Certo: norma IEEE, funciona entre marcas.",
      "PAgP": "O PAgP é proprietário da Cisco.",
      "DTP": "O DTP negoceia trunks, não agrega ligações.",
      "VTP": "O VTP propaga VLANs entre switches."}),
    ("Que comando mostra o estado dos EtherChannels?",
     "<code>show etherchannel summary</code> mostra cada Port-channel, o protocolo (LACP/PAgP) e o estado das portas membro: (P) agregada, (I) individual, (s) suspensa, (SU) canal de camada 2 em uso."),
    ("Com EtherChannel o STP trata as ligações agregadas como uma só.",
     "Verdadeiro. O STP vê o <b>Port-channel</b> como uma única ligação lógica, por isso nenhuma das ligações físicas do grupo é bloqueada e soma-se a largura de banda. Se uma ligação física cair, o canal continua sem recalcular o STP."),
    ("Qual a ordem do DHCP?",
     "O DHCP segue <b>DORA</b>: o cliente envia <b>Discover</b> (broadcast), o servidor responde com <b>Offer</b>, o cliente pede com <b>Request</b> e o servidor confirma com <b>Acknowledge</b>.",
     {"Discover, Offer, Request, Ack": "Certo: D-O-R-A.",
      "Discover, Request, Offer, Ack": "O cliente só pede (Request) depois de receber uma oferta.",
      "Offer, Discover, Ack, Request": "O servidor não oferece antes de o cliente se anunciar.",
      "Request, Offer, Discover, Ack": "Começa sempre pelo Discover."}),
    ("Que comando de interface encaminha pedidos DHCP para 10.0.0.10?",
     "<code>ip helper-address 10.0.0.10</code>, na interface do router que recebe os clientes (gateway da VLAN), transforma os broadcasts DHCP em unicast dirigido ao servidor noutra rede — o router torna-se <b>DHCP relay</b>."),
    ("Que registo DNS devolve um endereço IPv6?",
     "O registo <b>AAAA</b> (“quad-A”) associa um nome a um endereço IPv6. O <b>A</b> faz o mesmo para IPv4.",
     {"AAAA": "Certo: nome → IPv6.",
      "A": "O registo A devolve IPv4.",
      "MX": "O MX indica o servidor de correio.",
      "PTR": "O PTR faz resolução inversa."}),
    ("O comando 'ip dhcp excluded-address' é configurado dentro do pool.",
     "Falso. <code>ip dhcp excluded-address</code> é um comando de <b>configuração global</b>, escrito fora do <code>ip dhcp pool</code>. Reserva endereços (gateway, servidores, impressoras) que o servidor DHCP nunca entregará."),
    ("Que flag do RA indica DHCPv6 stateful?",
     "No Router Advertisement: flag <b>M</b> (Managed) = 1 → usar <b>DHCPv6 stateful</b> para o endereço; flag <b>O</b> (Other) = 1 → obter só outras informações (DNS) por DHCPv6 stateless; flag <b>A</b> no prefixo → pode usar SLAAC.",
     {"M": "Certo: Managed address configuration = DHCPv6 stateful.",
      "A": "A flag A (autonomous) autoriza SLAAC no prefixo.",
      "O": "A flag O indica DHCPv6 stateless (só outras informações).",
      "R": "R não é a flag que indica DHCPv6 stateful."}),
    ("No DHCPv6 stateful, de onde vem o gateway?",
     "No IPv6 o gateway vem <b>sempre do Router Advertisement</b>: o cliente usa o endereço link-local do router que enviou o RA. O DHCPv6 não tem opção de gateway.",
     {"Do Router Advertisement": "Certo: o gateway é o link-local do router que anuncia o RA.",
      "Do servidor DHCPv6": "O DHCPv6 não entrega gateway — diferença importante para o DHCPv4.",
      "Do DNS": "O DNS só resolve nomes.",
      "Manual": "Pode configurar-se à mão, mas no DHCPv6 stateful vem do RA."}),
    ("Em SLAAC + stateless, o DNS vem de…",
     "No <b>SLAAC + DHCPv6 stateless</b> (flag O = 1), o PC cria o endereço sozinho a partir do prefixo do RA e pede ao <b>servidor DHCPv6</b> só as “outras informações”, como o DNS.",
     {"Um servidor DHCPv6": "Certo: stateless = o DHCPv6 só entrega DNS e afins.",
      "O PC inventa": "O PC não pode adivinhar o servidor DNS.",
      "O switch": "O switch não fornece configuração IP.",
      "ARP": "O ARP nem existe no IPv6."}),
    ("Com SLAAC o PC cria o seu próprio endereço a partir do prefixo anunciado.",
     "Verdadeiro. No <b>SLAAC</b> o router anuncia o prefixo /64 no RA e o PC junta-lhe um ID de interface de 64 bits (EUI-64 ou aleatório). Não há servidor a registar quem tem que endereço."),
    ("Qual a prioridade HSRP por defeito?",
     "No HSRP a prioridade vai de 0 a 255 e por defeito é <b>100</b>. Ganha o papel de Active o router com maior prioridade (em empate, o maior IP).",
     {"100": "Certo: 100 por defeito.",
      "0": "0 não é o valor por defeito.",
      "50": "50 não é o valor por defeito.",
      "255": "255 é o máximo, não o valor por defeito."}),
    ("Qual FHRP é uma norma aberta?",
     "Os FHRP dão um gateway virtual redundante. <b>VRRP</b> é norma aberta (RFC 5798); <b>HSRP</b> e <b>GLBP</b> são proprietários da Cisco.",
     {"VRRP": "Certo: norma IETF (RFC 5798).",
      "HSRP": "HSRP é proprietário da Cisco.",
      "GLBP": "GLBP é proprietário da Cisco.",
      "CDP": "CDP é um protocolo de descoberta, não um FHRP."}),
    ("Sem 'preempt', um router HSRP com maior prioridade que arranca depois não toma o papel de Active.",
     "Verdadeiro. A <b>preempção</b> está desligada por defeito no HSRP: quem já é Active continua, mesmo que apareça um router com prioridade maior. Para ele assumir é preciso <code>standby 1 preempt</code>. (No VRRP a preempção vem ligada.)"),
    ("O que configuram os PCs como gateway?",
     "Os PCs usam como gateway o <b>IP virtual</b> do grupo HSRP/VRRP, que pertence a quem for Active. Se o router Active falhar, o Standby assume o mesmo IP (e MAC virtual) e os PCs nem notam.",
     {"IP virtual do grupo": "Certo: o IP virtual passa de router para router sem mexer nos PCs.",
      "IP real do router Active": "Se esse router falhasse, os PCs ficavam sem gateway.",
      "IP do switch": "O switch não é o gateway da rede.",
      "Nada": "Sem gateway os PCs não saíam da sua rede."}),
    ("Que protocolo AAA usa TCP 49 e cifra todo o pacote?",
     "O <b>TACACS+</b> (Cisco) usa <b>TCP 49</b>, cifra o pacote inteiro e separa autenticação, autorização e accounting — ideal para gerir administradores de equipamentos. O <b>RADIUS</b> usa UDP 1812/1813 e só cifra a palavra-passe.",
     {"TACACS+": "Certo: TCP 49, cifra todo o pacote.",
      "RADIUS": "O RADIUS usa UDP e cifra apenas a palavra-passe.",
      "Kerberos": "Kerberos é um sistema de autenticação com bilhetes (Active Directory), não usa TCP 49.",
      "LDAP": "O LDAP é um diretório (TCP 389), não um protocolo AAA de equipamentos."}),
    ("No 802.1X, o switch tem o papel de…",
     "No 802.1X há três papéis: <b>suplicante</b> (o PC), <b>autenticador</b> (o switch ou AP, que bloqueia a porta até haver autorização) e <b>servidor de autenticação</b> (normalmente RADIUS).",
     {"Autenticador": "Certo: o switch controla o acesso à porta.",
      "Suplicante": "O suplicante é o cliente (PC) que pede acesso.",
      "Servidor de autenticação": "É o servidor RADIUS que valida as credenciais.",
      "NMS": "NMS é um sistema de gestão de rede (SNMP)."}),
    ("Um e-mail falso dirigido especificamente ao diretor financeiro é…",
     "<b>Whaling</b> (“caçar baleias”) é phishing dirigido a executivos de topo. <b>Spear phishing</b> visa uma pessoa ou grupo específico; <b>vishing</b> é por voz; <b>smishing</b> por SMS.",
     {"Whaling": "Certo: phishing dirigido a um executivo (“peixe graúdo”).",
      "Vishing": "Vishing é por chamada telefónica.",
      "Smishing": "Smishing é por SMS.",
      "Spam": "Spam é publicidade em massa, não dirigida."}),
    ("Accounting regista o que o utilizador fez.",
     "Verdadeiro. AAA = <b>Authentication</b> (quem é), <b>Authorization</b> (o que pode fazer) e <b>Accounting</b> (o que fez: comandos, horas de entrada/saída). O accounting serve para auditoria e faturação."),
    ("Qual o modo de violação padrão do port security?",
     "Modos de violação: <b>protect</b> (descarta em silêncio), <b>restrict</b> (descarta, regista e conta) e <b>shutdown</b> (por defeito: põe a porta em <b>err-disabled</b>).",
     {"shutdown": "Certo: por defeito a porta vai para err-disabled.",
      "protect": "Protect só descarta, sem alertas; não é o padrão.",
      "restrict": "Restrict descarta e regista; não é o padrão.",
      "drop": "Não existe modo “drop” no port security."}),
    ("No DHCP snooping, as portas para o servidor DHCP legítimo devem ser…",
     "Com DHCP snooping todas as portas são <b>untrusted</b> por defeito e as respostas DHCP (Offer/Ack) que chegam por elas são descartadas. As portas para o servidor legítimo (ou uplinks) configuram-se como <b>trusted</b>: <code>ip dhcp snooping trust</code>.",
     {"trusted": "Certo: só por portas trusted podem chegar respostas de servidor DHCP.",
      "untrusted": "Em untrusted as respostas do servidor seriam bloqueadas.",
      "err-disabled": "Err-disabled é uma porta desligada por violação.",
      "trunk obrigatoriamente": "Pode ser access ou trunk; o que interessa é ser trusted."}),
    ("O DAI protege contra…",
     "O <b>DAI</b> (Dynamic ARP Inspection) verifica cada mensagem ARP contra a tabela do DHCP snooping e descarta as falsas, travando o <b>ARP spoofing</b> (ataques man-in-the-middle).",
     {"ARP spoofing": "Certo: valida as mensagens ARP.",
      "Servidores DHCP falsos": "Isso é o DHCP snooping.",
      "Loops STP": "Loops são tratados pelo STP e BPDU Guard.",
      "VLAN hopping": "VLAN hopping evita-se desligando o DTP e mudando a VLAN nativa."}),
    ("Que comando faz o switch aprender e gravar os MACs na porta?",
     "<code>switchport port-security mac-address sticky</code>, no modo de interface (com port security ativo), faz o switch aprender os MACs ligados e escrevê-los na running-config como estáticos. Guarde com <code>copy run start</code> para sobreviverem a um reinício."),
    ("No modo restrict a porta fica em err-disabled.",
     "Falso. Em <b>restrict</b> a porta continua ativa: descarta as tramas dos MACs não autorizados, envia uma mensagem de log/SNMP e incrementa o contador de violações. Só o modo <b>shutdown</b> põe a porta em err-disabled."),
    ("Quais os canais de 2,4 GHz que não se sobrepõem?",
     "Na banda de 2,4 GHz cada canal tem ~22 MHz e os canais estão a 5 MHz uns dos outros; só <b>1, 6 e 11</b> não se sobrepõem. Por isso APs vizinhos devem usar estes três.",
     {"1, 6, 11": "Certo: os únicos três sem sobreposição (na maioria dos países).",
      "1, 5, 9": "Ficam a 20 MHz: ainda se sobrepõem parcialmente.",
      "2, 7, 12": "O 12 não é permitido em todos os países e não é a combinação de referência.",
      "1, 7, 13": "O 13 não é universal; a combinação padrão é 1, 6 e 11."}),
    ("Que protocolo liga APs leves à WLC?",
     "O <b>CAPWAP</b> cria túneis entre os APs leves e a WLC: UDP 5246 para controlo (cifrado) e UDP 5247 para dados. Substituiu o antigo LWAPP.",
     {"CAPWAP": "Certo: UDP 5246 (controlo) e 5247 (dados).",
      "LWAPP antigo apenas": "O LWAPP foi o antecessor; hoje usa-se CAPWAP.",
      "CDP": "O CDP descobre vizinhos, não cria túneis.",
      "SNMP": "O SNMP serve para monitorizar, não para ligar APs à WLC."}),
    ("Qual a opção de segurança mais forte?",
     "Ordem de segurança Wi-Fi: WEP (quebrado) &lt; WPA-TKIP (obsoleto) &lt; WPA2-AES &lt; <b>WPA3-SAE</b>. O WPA3 substitui o PSK pelo SAE, que resiste a ataques de dicionário offline.",
     {"WPA3-SAE": "Certo: o mais recente e robusto.",
      "WEP": "O WEP quebra-se em minutos.",
      "WPA-TKIP": "O TKIP está obsoleto e tem vulnerabilidades.",
      "WPA2-AES": "É bom, mas o WPA3 é mais forte."}),
    ("A porta do switch ligada a um AP leve (modo local) é normalmente access.",
     "Verdadeiro. No modo local o tráfego de todos os SSIDs viaja dentro do túnel CAPWAP até à WLC, por isso a porta do AP só precisa de uma VLAN (access). Confusão comum: em FlexConnect ou APs autónomos a porta costuma ser trunk."),
    ("Vários APs com o mesmo SSID formam um…",
     "Um AP com os seus clientes forma um <b>BSS</b> (identificado pelo BSSID, o MAC do rádio). Vários APs com o <b>mesmo SSID</b> ligados à mesma rede formam um <b>ESS</b>, que permite roaming. IBSS é ad hoc, sem AP.",
     {"ESS": "Certo: Extended Service Set, permite roaming entre APs.",
      "BSS": "BSS é um só AP e os seus clientes.",
      "IBSS": "IBSS é uma rede ad hoc sem AP.",
      "BSSID": "O BSSID é o identificador (MAC) de um BSS."}),
    ("Qual a primeira coisa a mudar num router Wi-Fi novo?",
     "A <b>palavra-passe de administração</b> de fábrica (ex.: admin/admin) está publicada nos manuais na Internet. Se não a mudar, qualquer pessoa ligada pode reconfigurar o router.",
     {"A palavra-passe de administração": "Certo: a de fábrica é pública.",
      "O canal": "Escolher o canal ajuda o desempenho, mas não é a prioridade de segurança.",
      "A cor dos LEDs": "Não tem impacto na segurança.",
      "O DNS": "Mudar o DNS é opcional."}),
    ("Que segurança escolher num router doméstico atual?",
     "Escolha <b>WPA2 ou WPA3 com AES</b> (WPA3 se todos os equipamentos suportarem; modo misto WPA2/WPA3 se não). WEP e TKIP são inseguros; rede aberta deixa todos entrar.",
     {"WPA2/WPA3 com AES": "Certo: cifra forte e atual.",
      "WEP": "O WEP quebra-se em minutos.",
      "WPA-TKIP": "TKIP está obsoleto.",
      "Aberta": "Sem palavra-passe qualquer vizinho entra e pode espiar o tráfego."}),
]
