"""Explicações detalhadas do quiz (parte 6: automação, cablagem estruturada, Linux, Wireshark, segurança, IPv6, partilhas, projeto final)."""

ENTRADAS = [
    ("Que código indica falta de autenticação?",
     "Códigos HTTP: 2xx sucesso (<b>200</b> OK, 201 Created), 4xx erro do cliente (<b>401</b> Unauthorized — falta autenticação ou token inválido, 403 Forbidden, <b>404</b> Not Found), 5xx erro do servidor (<b>500</b>).",
     {"401": "Certo: 401 Unauthorized — credenciais em falta ou inválidas.",
      "200": "200 é sucesso (OK).",
      "404": "404 é recurso não encontrado.",
      "500": "500 é erro interno do servidor."}),
    ("Qual destes é JSON válido?",
     "No <b>JSON</b> as chaves e as strings vão sempre entre <b>aspas duplas</b> e usa-se dois pontos entre chave e valor: <code>{\"a\": 1}</code>. Aspas simples, = ou etiquetas &lt;&gt; não são JSON.",
     {"{\"a\": 1}": "Certo: chave com aspas duplas, dois pontos e valor numérico.",
      "{'a': 1}": "Aspas simples são válidas em Python, mas não em JSON.",
      "{a = 1}": "Falta aspas na chave e usa = em vez de :.",
      "<a>1</a>": "Isto é XML, não JSON."}),
    ("As APIs REST são sem estado (stateless).",
     "Verdadeiro. Em REST cada pedido leva toda a informação necessária (incluindo o token de autenticação); o servidor <b>não guarda contexto</b> entre pedidos. Isso simplifica e torna os servidores mais escaláveis."),
    ("Qual destas ferramentas não precisa de agente nos equipamentos?",
     "O <b>Ansible</b> é <b>agentless</b>: liga-se aos equipamentos por SSH ou APIs e envia as tarefas. <b>Puppet</b> e <b>Chef</b> precisam normalmente de um agente instalado em cada equipamento gerido.",
     {"Ansible": "Certo: usa SSH/APIs, sem agente.",
      "Puppet": "O Puppet usa um agente (modelo pull).",
      "Chef": "O Chef usa um agente (chef-client).",
      "Todas precisam": "O Ansible não precisa."}),
    ("Em que formato se escrevem os playbooks Ansible?",
     "Os playbooks Ansible escrevem-se em <b>YAML</b>: texto legível, com indentação por espaços e listas com hífen.",
     {"YAML": "Certo: playbooks em YAML.",
      "JSON": "O Ansible lê JSON noutros contextos, mas os playbooks são YAML.",
      "XML": "XML é usado pelo NETCONF, não pelos playbooks.",
      "Ruby": "Ruby é a linguagem do Chef (e do Puppet, em parte)."}),
    ("Que porta usa o NETCONF sobre SSH?",
     "O <b>NETCONF</b> corre sobre SSH na porta <b>TCP 830</b> e troca dados em XML, modelados em YANG. O RESTCONF usa HTTPS (443).",
     {"830": "Certo: NETCONF/SSH = TCP 830.",
      "22": "22 é o SSH normal da CLI.",
      "443": "443 é HTTPS, usado pelo RESTCONF.",
      "8080": "8080 é uma porta HTTP alternativa comum."}),
    ("YANG é um protocolo de transporte como o HTTP.",
     "Falso. <b>YANG</b> é uma <b>linguagem de modelação de dados</b>: descreve a estrutura da configuração e do estado (interfaces, VLANs…). Os protocolos que transportam esses dados são o NETCONF e o RESTCONF."),
    ("No Netmiko, que método envia uma lista de comandos de configuração?",
     "No Netmiko, <code>send_config_set([...])</code> entra no modo de configuração, envia a lista de comandos e sai. <code>send_command()</code> envia um único comando (normalmente um show) e devolve a saída.",
     {"send_config_set": "Certo: envia uma lista de comandos de configuração.",
      "send_command": "Envia um comando de consulta (show), não uma lista de configuração.",
      "push_config": "Não é um método do Netmiko.",
      "configure": "Não é o método usado para enviar a lista."}),
    ("Um script recebe 404 ao chamar a API. Significa…",
     "<b>404 Not Found</b>: o URL/recurso pedido não existe (ex.: caminho mal escrito ou ID inexistente). A autenticação falhada seria 401; erro do servidor 500; sucesso sem conteúdo 204.",
     {"Recurso/URL inexistente": "Certo: 404 Not Found.",
      "Sem autenticação": "Seria 401 Unauthorized.",
      "Erro do servidor": "Seria 500.",
      "Sucesso sem conteúdo": "Seria 204 No Content."}),
    ("Qual protocolo southbound usa HTTPS e JSON?",
     "O <b>RESTCONF</b> expõe os modelos YANG através de uma API REST sobre <b>HTTPS</b>, com dados em <b>JSON</b> ou XML. O NETCONF usa SSH e XML.",
     {"RESTCONF": "Certo: HTTPS + JSON/XML, modelos YANG.",
      "NETCONF": "O NETCONF usa SSH (830) e XML.",
      "OpenFlow": "O OpenFlow programa tabelas de fluxo, com protocolo próprio.",
      "SNMP": "O SNMP usa UDP e MIBs."}),
    ("Num controlador SDN, a northbound API normalmente é REST.",
     "Verdadeiro. As aplicações e scripts falam com o controlador (ex.: Cisco DNA Center) por uma <b>API REST</b> sobre HTTPS com JSON. A southbound usa NETCONF, RESTCONF, OpenFlow ou CLI."),
    ("Comprimento máximo do cabo horizontal permanente?",
     "Na cablagem estruturada (TIA-568), o canal tem 100 m: até <b>90 m</b> de cabo horizontal permanente (do patch panel à tomada) + até 10 m de cordões nas duas pontas.",
     {"90 m": "Certo: 90 m fixos + 10 m de cordões = 100 m.",
      "50 m": "Fica muito abaixo do limite.",
      "100 m": "100 m é o canal completo, incluindo cordões.",
      "300 m": "Muito acima do permitido para cobre."}),
    ("Que norma define a identificação e etiquetagem?",
     "A <b>TIA-606</b> define como identificar e etiquetar cabos, tomadas, patch panels e bastidores — essencial para encontrar rapidamente uma ligação numa avaria.",
     {"TIA-606": "Certo: norma de administração e etiquetagem.",
      "802.11": "802.11 é o Wi-Fi.",
      "RFC 1918": "A RFC 1918 define os endereços IPv4 privados.",
      "802.3at": "802.3at é o PoE+."}),
    ("Potência do PoE+ (802.3at)?",
     "PoE: <b>802.3af</b> até 15,4 W; <b>802.3at (PoE+)</b> até <b>30 W</b>; 802.3bt (PoE++) até 60/90 W.",
     {"30 W": "Certo: PoE+ fornece até 30 W por porta.",
      "15,4 W": "15,4 W é o PoE original (802.3af).",
      "90 W": "90 W é o 802.3bt tipo 4.",
      "5 W": "Muito abaixo de qualquer norma PoE."}),
    ("O backbone entre pisos usa normalmente fibra ótica.",
     "Verdadeiro. O <b>backbone</b> (cablagem vertical) liga o bastidor principal aos bastidores de cada piso e precisa de muita largura de banda e, às vezes, mais de 100 m — daí a fibra."),
    ("Quantos centímetros tem 1 U num bastidor?",
     "1 U (rack unit) = <b>1,75 polegadas = 4,45 cm</b> de altura. Um switch típico ocupa 1 U; um bastidor de 42 U tem cerca de 2 m de altura útil.",
     {"4,45 cm": "Certo: 1,75 polegadas.",
      "1 cm": "Muito pequeno.",
      "10 cm": "Seria mais do dobro.",
      "19 cm": "19 é a largura do bastidor em polegadas, não a altura de 1 U."}),
    ("Que comando mostra os IPs das interfaces no Linux?",
     "No Linux moderno usa-se <code>ip addr show</code> (abreviado <code>ip a</code>), que mostra cada interface com IPv4/IPv6 e MAC. O antigo <code>ifconfig</code> ainda existe em muitas distribuições. Equivale ao <code>ipconfig</code> do Windows."),
    ("Que comando mostra as portas abertas?",
     "<code>ss -tulpn</code> lista sockets <b>T</b>CP e <b>U</b>DP em escuta (<b>l</b>isten), com o <b>p</b>rocesso e endereços <b>n</b>uméricos — mostra que serviços aceitam ligações.",
     {"ss -tulpn": "Certo: lista portas TCP/UDP em escuta e os processos.",
      "ls -l": "Lista ficheiros de uma pasta.",
      "cd /": "Muda para a pasta raiz.",
      "pwd": "Mostra a pasta atual."}),
    ("Que comando liga a firewall ufw?",
     "<code>sudo ufw enable</code> ativa a firewall UFW do Ubuntu (e no arranque). Antes, permita o SSH (<code>sudo ufw allow ssh</code>) se estiver a trabalhar remotamente.",
     {"sudo ufw enable": "Certo: ativa a firewall com privilégios de administrador.",
      "ufw start": "Não é a sintaxe do ufw (e faltaria o sudo).",
      "firewall on": "Não é um comando Linux.",
      "ip ufw": "O comando ip não gere a firewall."}),
    ("sudo executa um comando com privilégios de administrador.",
     "Verdadeiro. <code>sudo</code> (“superuser do”) corre o comando seguinte como root, depois de pedir a palavra-passe do utilizador (que tem de estar no grupo sudo)."),
    ("Que filtro mostra só o DHCP?",
     "No Wireshark, o filtro de visualização <code>dhcp</code> (em versões antigas <code>bootp</code>) mostra só Discover, Offer, Request e Ack.",
     {"dhcp": "Certo: mostra só as mensagens DHCP.",
      "ip": "Mostra todo o tráfego IP.",
      "tcp": "O DHCP usa UDP; este filtro nem o mostra.",
      "arp": "Mostra só ARP."}),
    ("Para capturar o tráfego de outro PC num switch usa-se…",
     "O switch só envia a cada porta o tráfego destinado a ela. Para analisar o tráfego de outro PC configura-se <b>SPAN</b> (port mirroring): <code>monitor session 1 source interface …</code> e <code>destination interface …</code>.",
     {"SPAN (port mirroring)": "Certo: copia o tráfego de uma porta para a porta do analisador.",
      "VLAN 1": "Estar na VLAN 1 não faz ver o tráfego unicast dos outros.",
      "NAT": "O NAT traduz endereços.",
      "STP": "O STP evita loops."}),
    ("O filtro tcp.analysis.retransmission ajuda a encontrar problemas de rede.",
     "Verdadeiro. Retransmissões TCP indicam pacotes perdidos ou atrasados (congestionamento, erros físicos, duplex mismatch). Este filtro do Wireshark mostra-as rapidamente."),
    ("Diferença entre IDS e IPS?",
     "O <b>IDS</b> recebe uma cópia do tráfego (fora do caminho) e só <b>alerta</b>. O <b>IPS</b> está <b>no caminho</b> do tráfego (inline) e pode <b>bloquear</b> em tempo real.",
     {"O IDS alerta, o IPS bloqueia": "Certo: IDS deteta e avisa, IPS previne.",
      "O IDS bloqueia, o IPS só alerta": "Está trocado.",
      "São iguais": "Diferem na posição (fora/no caminho) e na ação.",
      "Nenhum vê tráfego": "Ambos analisam tráfego."}),
    ("O que diz a regra 3-2-1?",
     "Regra <b>3-2-1</b> dos backups: <b>3</b> cópias dos dados, em <b>2</b> suportes diferentes, com <b>1</b> fora do local (offsite/cloud). Protege contra avarias, incêndios e ransomware.",
     {"3 cópias, 2 suportes, 1 fora do local": "Certo: é a regra dos backups.",
      "3 firewalls, 2 routers, 1 switch": "Não é uma regra de backups.",
      "3 senhas por pessoa": "Não tem a ver com senhas.",
      "Nada": "É uma regra conhecida de cópias de segurança."}),
    ("Primeira ação ao detetar um PC com ransomware?",
     "A prioridade é a <b>contenção</b>: <b>isolar o PC da rede</b> (desligar o cabo/Wi-Fi) para o ransomware não cifrar partilhas e outros PCs. Depois investiga-se e recupera-se dos backups.",
     {"Isolar o PC da rede": "Certo: contenção primeiro, para não alastrar.",
      "Pagar": "Pagar não garante a recuperação e financia o crime.",
      "Reiniciar o servidor": "Não trava o ransomware e pode destruir provas.",
      "Apagar os logs": "Os logs são essenciais para a investigação."}),
    ("Uma firewall stateful lembra-se das ligações iniciadas.",
     "Verdadeiro. Uma firewall <b>stateful</b> guarda uma tabela de ligações: quando um PC interno abre uma ligação, as respostas são automaticamente permitidas, sem regras extra para o tráfego de volta."),
    ("Que tamanho de prefixo se dá a cada VLAN em IPv6?",
     "Em IPv6 cada rede local (VLAN) recebe um <b>/64</b>: 64 bits de rede + 64 bits de ID de interface, necessários para o SLAAC. A empresa costuma receber um /48 e divide-o em /64.",
     {"/64": "Certo: /64 por segmento, exigido pelo SLAAC.",
      "/48": "/48 é o bloco típico atribuído a um local/empresa.",
      "/56": "/56 é o típico de um cliente residencial.",
      "/128": "/128 é um único endereço (ex.: loopback)."}),
    ("Como se aplica uma ACL IPv6 a uma interface?",
     "Em IPv6 as ACLs são sempre com nome e aplicam-se com <code>ipv6 traffic-filter NOME in|out</code> no modo de interface (em IPv4 é ip access-group).",
     {"ipv6 traffic-filter": "Certo: ipv6 traffic-filter NOME in/out.",
      "ip access-group": "É o comando das ACLs IPv4.",
      "access-class": "Aplica ACLs às linhas vty (em IPv6: ipv6 access-class).",
      "ipv6 acl": "Não é um comando válido."}),
    ("No OSPFv3 ativa-se o protocolo na interface.",
     "Verdadeiro. No OSPFv3 não há comando network: ativa-se em cada interface com <code>ipv6 ospf 1 area 0</code>, depois de <code>ipv6 router ospf 1</code> (com router-id configurado)."),
    ("O que bloqueia o RA Guard?",
     "O <b>RA Guard</b> bloqueia <b>Router Advertisements</b> que cheguem por portas de utilizadores, impedindo que um equipamento falso se anuncie como router IPv6 (ataque man-in-the-middle).",
     {"Router Advertisements falsos": "Certo: só portas autorizadas podem enviar RAs.",
      "ARP": "O ARP é protegido pelo DAI (e nem existe em IPv6).",
      "DNS": "O RA Guard não filtra DNS.",
      "HTTP": "O RA Guard não filtra HTTP."}),
    ("O que faz um ABR no OSPF?",
     "Um <b>ABR</b> (Area Border Router) tem interfaces na área 0 e noutra área; liga essa área ao backbone e resume as rotas entre elas.",
     {"Liga áreas à área 0": "Certo: Area Border Router.",
      "Atribui IPs": "Isso é o DHCP.",
      "Bloqueia BPDUs": "Isso é o BPDU Guard (camada 2).",
      "Cria VLANs": "VLANs criam-se nos switches."}),
    ("Que protocolo liga uma empresa a dois operadores na Internet?",
     "Para ligar a dois operadores com o mesmo bloco de IPs e escolher caminhos usa-se <b>BGP</b>, o protocolo de routing entre sistemas autónomos (multihoming).",
     {"BGP": "Certo: routing entre sistemas autónomos.",
      "RIP": "O RIP é um IGP antigo, para dentro da empresa.",
      "STP": "O STP é de camada 2.",
      "HSRP": "O HSRP dá redundância de gateway na LAN."}),
    ("Que algoritmo usa o EIGRP?",
     "O EIGRP usa o <b>DUAL</b> (Diffusing Update Algorithm), que calcula o sucessor e sucessores viáveis (rotas de reserva sem loops), convergindo muito depressa.",
     {"DUAL": "Certo: Diffusing Update Algorithm.",
      "SPF": "O SPF (Dijkstra) é do OSPF.",
      "STP": "O STP é de camada 2.",
      "Bellman-Ford puro": "O RIP usa Bellman-Ford; o EIGRP evoluiu para o DUAL."}),
    ("O BGP é o protocolo de encaminhamento entre sistemas autónomos da Internet.",
     "Verdadeiro. O <b>BGP</b> é o EGP (Exterior Gateway Protocol) da Internet: os operadores trocam rotas entre sistemas autónomos (AS) com ele. Dentro da empresa usam-se IGPs como OSPF."),
    ("Que porta usa o SMB moderno?",
     "O <b>SMB 2/3</b> (partilhas Windows) corre diretamente sobre <b>TCP 445</b>. A 139 era do SMB sobre NetBIOS; 137 é o serviço de nomes NetBIOS; 2049 é do NFS.",
     {"TCP 445": "Certo: SMB direto sobre TCP.",
      "TCP 139": "139 era do SMB sobre NetBIOS (antigo).",
      "UDP 137": "137 é o serviço de nomes NetBIOS.",
      "TCP 2049": "2049 é o NFS."}),
    ("No caminho \\\\192.168.1.10\\Documentos, o que é «Documentos»?",
     "Num caminho UNC <code>\\\\servidor\\partilha</code>, primeiro vem o servidor (nome ou IP) e depois o <b>nome da partilha</b> — que pode ser diferente do nome real da pasta no disco.",
     {"O nome da partilha": "Certo: é o nome com que a pasta é publicada na rede.",
      "O nome do servidor": "O servidor é 192.168.1.10.",
      "A letra da unidade": "A letra (ex.: Z:) só aparece quando se mapeia a partilha.",
      "O grupo de trabalho": "O grupo de trabalho não aparece no caminho UNC."}),
    ("A partilha dá Controlo total a Todos e o NTFS dá apenas Ler à Ana. O que pode a Ana fazer pela rede?",
     "Pela rede aplicam-se as <b>duas</b> permissões (partilha e NTFS) e ganha a <b>mais restritiva</b>. Partilha = controlo total, NTFS = ler → a Ana só pode <b>ler</b>.",
     {"Apenas ler": "Certo: a mais restritiva das duas é Ler.",
      "Tudo": "O NTFS limita-a a leitura.",
      "Alterar ficheiros mas não apagar": "Isso exigiria permissão de modificação no NTFS.",
      "Nada": "Ler é permitido pelas duas."}),
    ("Qual destes protocolos é o mais usado para partilhas entre servidores Linux?",
     "O <b>NFS</b> (Network File System, porta 2049) é o protocolo nativo de partilha de ficheiros em Linux/Unix. Para partilhar com Windows usa-se SMB (Samba).",
     {"NFS": "Certo: protocolo nativo de partilha em Linux/Unix.",
      "RDP": "O RDP é ambiente de trabalho remoto.",
      "SMTP": "O SMTP envia e-mail.",
      "SNMP": "O SNMP monitoriza equipamentos."}),
    ("Com o perfil de rede Público o Windows esconde o PC e bloqueia a partilha de ficheiros por omissão.",
     "Verdadeiro. O perfil <b>Público</b> é para redes não confiáveis (café, aeroporto): desliga a deteção de rede e a partilha. Numa rede de escritório de confiança usa-se o perfil <b>Privado</b> (ou Domínio)."),
    ("Num grupo de trabalho, as contas de utilizador estão centralizadas num controlador de domínio.",
     "Falso. Num <b>grupo de trabalho</b> cada PC tem as suas próprias contas locais. Contas centralizadas num controlador são característica de um <b>domínio</b> (Active Directory)."),
    ("Abre-se \\\\192.168.1.10 mas \\\\FS01 dá erro. Qual é a causa mais provável?",
     "Pelo IP funciona, logo rede, firewall (porta 445) e partilha estão bem. O que falha é traduzir o nome FS01 em IP: <b>resolução de nomes</b> (DNS, NetBIOS ou ficheiro hosts).",
     {"Falha na resolução de nomes": "Certo: pelo IP funciona, pelo nome não.",
      "Firewall a bloquear a porta 445": "Se a 445 estivesse bloqueada, pelo IP também falhava.",
      "Cabo desligado": "Com cabo desligado nada funcionava.",
      "Permissões NTFS": "Permissões dariam “acesso negado” nos dois casos."}),
    ("Que porta TCP usa o NFS?",
     "O <b>NFS</b> usa a porta <b>2049</b> (TCP, e também UDP em versões antigas). No NFSv4 é a única porta necessária."),
    ("O que é um NAS?",
     "Um <b>NAS</b> (Network Attached Storage) é uma caixa com discos, ligada à rede, que partilha ficheiros por SMB/NFS — uma solução simples de armazenamento centralizado para escritórios.",
     {"Um equipamento de armazenamento ligado à rede": "Certo: Network Attached Storage.",
      "Um protocolo de nomes": "Protocolos de nomes são DNS ou NetBIOS.",
      "Um tipo de cabo": "Não é um cabo.",
      "Uma VLAN de servidores": "Uma VLAN é uma rede lógica, não um equipamento."}),
    ("Em que separador das Propriedades da pasta se definem as permissões NTFS?",
     "As permissões <b>NTFS</b> estão no separador <b>Segurança</b>; as permissões de <b>partilha</b> estão em Partilha › Partilha avançada › Permissões.",
     {"Segurança": "Certo: o separador Segurança mostra as permissões NTFS.",
      "Partilha": "Aí definem-se as permissões de partilha, não as NTFS.",
      "Geral": "Mostra tamanho, localização e atributos.",
      "Personalizar": "Muda o aspeto da pasta."}),
    ("Que comando mapeia a pasta Documentos do servidor 192.168.1.10 na letra Z:?",
     "<code>net use Z: \\\\192.168.1.10\\Documentos</code> liga a partilha à letra Z: (na Linha de Comandos do Windows). Acrescente <code>/persistent:yes</code> para voltar a ligar após reiniciar e <code>/user:</code> para indicar outra conta."),
    ("Que comando lista as pastas partilhadas no próprio PC?",
     "<code>net share</code> sem parâmetros lista as partilhas do PC, incluindo as administrativas ocultas (C$, ADMIN$, IPC$). Com <code>nome=caminho</code> cria uma partilha nova."),
    ("Que cmdlet do PowerShell lista as partilhas SMB?",
     "<code>Get-SmbShare</code> (PowerShell) lista nome, caminho e descrição de cada partilha SMB. Para criar usa-se <code>New-SmbShare</code>."),
    ("Que perfil de rede deve ter o servidor numa rede de escritório em grupo de trabalho?",
     "Numa rede de confiança sem domínio usa-se o perfil <b>Privado</b>: ativa a deteção de rede e a partilha de ficheiros e impressoras.",
     {"Privado": "Certo: permite deteção e partilha numa rede de confiança.",
      "Público": "O Público bloqueia a partilha (para redes não confiáveis).",
      "Convidado": "Não é um perfil de rede do Windows.",
      "Visitante": "Não é um perfil de rede do Windows."}),
    ("A opção «Ligar novamente ao iniciar sessão» faz a unidade Z: voltar depois de reiniciar o PC.",
     "Verdadeiro. Essa opção (ao mapear a unidade no Explorador) guarda o mapeamento; equivale a <code>net use Z: … /persistent:yes</code>."),
    ("Qual destas configurações é a mais perigosa?",
     "<b>Todos – Controlo total</b> deixa qualquer utilizador (ou malware, como ransomware) ler, alterar, apagar e mudar permissões. Princípio do menor privilégio: dê a cada grupo só o que precisa.",
     {"Todos – Controlo total": "Certo: qualquer pessoa ou malware pode apagar e cifrar tudo.",
      "Contabilidade – Alteração": "É um grupo concreto com permissões adequadas ao trabalho.",
      "Administradores – Controlo total": "É normal que os administradores tenham controlo total.",
      "Receção – Leitura": "É restritivo e seguro."}),
    ("Que comando desliga a unidade de rede Z:?",
     "<code>net use Z: /delete</code> (ou <code>/d</code>) remove o mapeamento da letra Z:. <code>net use * /delete</code> remove todos."),
    ("Para outros PCs imprimirem numa impressora partilhada, o PC que a partilha tem de estar ligado.",
     "Verdadeiro. O PC que partilha é o servidor de impressão: recebe os trabalhos dos outros e envia-os à impressora. Se estiver desligado, ninguém imprime — por isso em empresas usa-se um servidor ou impressora de rede."),
    ("No comando net share Documentos=C:\\Documentos /grant:Todos,READ, que nível de acesso recebe «Todos»? (palavra em inglês)",
     "<code>/grant:Todos,READ</code> dá ao grupo Todos permissão de <b>READ</b> (leitura) na partilha. Outras opções: <b>CHANGE</b> (alteração) e <b>FULL</b> (controlo total)."),
    ("Que comando cria a palavra-passe Samba para a utilizadora ana?",
     "<code>sudo smbpasswd -a ana</code> adiciona a utilizadora (que já tem de existir no Linux) à base de dados do Samba e define a palavra-passe usada para aceder às partilhas."),
    ("Que comando verifica se o ficheiro smb.conf tem erros?",
     "<code>testparm</code> lê o /etc/samba/smb.conf, indica erros de sintaxe e mostra a configuração efetiva. Corra-o sempre antes de reiniciar o serviço (<code>sudo systemctl restart smbd</code>)."),
    ("Na secção [Documentos] do smb.conf, que linha permite escrever na partilha?",
     "Por defeito as partilhas Samba são só de leitura. <code>read only = no</code> (ou <code>writable = yes</code>) permite escrever — desde que as permissões Linux da pasta também o deixem.",
     {"read only = no": "Certo: torna a partilha de leitura e escrita.",
      "browseable = yes": "Só faz a partilha aparecer na lista; não dá escrita.",
      "valid users = ana": "Define quem pode entrar, não se pode escrever.",
      "path = /srv": "Define a pasta partilhada."}),
    ("No macOS, onde se escreve smb://192.168.1.20/Documentos para ligar a uma partilha?",
     "No macOS liga-se a uma partilha no <b>Finder › Ir › Ligar ao servidor</b> (Cmd + K) e escreve-se o endereço smb://servidor/partilha.",
     {"Finder › Ir › Ligar ao servidor": "Certo: Cmd + K no Finder.",
      "Terminal › ssh": "O SSH é acesso remoto à linha de comandos, não monta partilhas SMB.",
      "Safari › Endereço": "O browser não monta partilhas SMB.",
      "Definições do Sistema › Rede": "Aí configura-se a ligação de rede, não as partilhas."}),
    ("O ping ao servidor funciona mas Test-NetConnection -Port 445 dá False. Causa mais provável?",
     "O ping prova que há ligação IP. Se a porta <b>445</b> não responde, ou uma <b>firewall</b> a bloqueia ou o <b>serviço de partilha</b> (Servidor/LanmanServer ou Samba) está parado.",
     {"Firewall ou serviço de partilha parado": "Certo: há IP, mas a porta 445 não aceita ligações.",
      "Cabo de rede avariado": "Com cabo avariado o ping falhava.",
      "Endereço IP errado": "O ping ao mesmo IP funciona.",
      "DNS em baixo": "Está a usar o IP; o DNS não entra."}),
    ("Que erro aparece normalmente quando a conta não tem permissões suficientes?",
     "<b>Acesso negado</b> significa que se chegou ao servidor e à partilha, mas as permissões (partilha ou NTFS) não deixam. “Caminho não encontrado” ou “tempo esgotado” indicam problemas de rede/nome.",
     {"Acesso negado": "Certo: chegou lá, mas não tem permissão.",
      "O caminho de rede não foi encontrado": "Indica problema de nome, rede ou partilha inexistente.",
      "Tempo limite esgotado": "Indica que o servidor não responde (rede/firewall).",
      "Nome não resolvido": "Indica problema de DNS/NetBIOS."}),
    ("Que cmdlet testa se a porta 445 do servidor 192.168.1.10 está acessível?",
     "<code>Test-NetConnection 192.168.1.10 -Port 445</code> (alias <code>tnc</code>) tenta abrir uma ligação TCP à porta e mostra <b>TcpTestSucceeded: True/False</b>. Distingue problemas de rede de problemas de firewall/serviço."),
    ("O NFS usa as contas e palavras-passe do Samba para decidir o acesso.",
     "Falso. O NFS clássico decide pelo <b>UID/GID</b> do Linux e pelas redes/hosts indicados em <code>/etc/exports</code>. O Samba (SMB) tem a sua própria base de utilizadores (smbpasswd)."),
    ("Que comando aplica as exportações do ficheiro /etc/exports?",
     "<code>sudo exportfs -a</code> exporta todas as pastas listadas em /etc/exports (<code>exportfs -ra</code> recarrega depois de alterações). <code>exportfs -v</code> mostra o que está exportado."),
    ("Porque é que o tráfego da VLAN 10 para o FS01 passa pelo router?",
     "Cada VLAN é uma rede IP diferente. Para ir de uma rede para outra é sempre preciso <b>encaminhamento</b> (router-on-a-stick ou switch L3) — e é aí que se podem aplicar ACLs.",
     {"Porque estão em redes IP diferentes": "Certo: VLANs diferentes = redes diferentes = routing.",
      "Porque o SMB só funciona com routers": "O SMB funciona na mesma rede sem router.",
      "Porque o switch não suporta TCP": "O switch L2 transporta qualquer tráfego; só não encaminha entre redes.",
      "Porque o DNS assim o exige": "O DNS não decide caminhos."}),
    ("Escreva a linha da ACL 110 que permite à rede 192.168.20.0/24 usar SMB no host 192.168.99.10.",
     "<code>access-list 110 permit tcp 192.168.20.0 0.0.0.255 host 192.168.99.10 eq 445</code>: protocolo TCP, origem com wildcard 0.0.0.255 (/24), destino um único host e porta de destino igual a 445 (SMB)."),
    ("Porque se acrescenta permit ip any any no fim da ACL?",
     "Todas as ACLs terminam com um <b>deny any implícito</b>. Sem um <code>permit ip any any</code> no fim, todo o tráfego não referido (DNS, login, ping) seria bloqueado.",
     {"Porque no fim há um deny any implícito": "Certo: sem ele, o resto do tráfego era bloqueado.",
      "Para permitir o SMB": "O SMB já é tratado nas linhas específicas.",
      "Para ativar o log": "O log ativa-se com a palavra log numa linha.",
      "Para criar a VLAN": "As VLANs não se criam com ACLs."}),
    ("Na regra 3-2-1, quantas cópias devem estar fora do edifício?",
     "Regra 3-2-1: 3 cópias, 2 suportes diferentes, <b>1 fora do local</b> (outro edifício ou cloud), para sobreviver a incêndios, roubos ou ransomware."),
    ("A quem se devem atribuir as permissões das pastas?",
     "Atribuem-se permissões a <b>grupos</b> (Receção, Médicos, Administração) e colocam-se as pessoas nos grupos. Quando alguém entra ou sai, só se muda a pertença ao grupo.",
     {"A grupos (Receção, Médicos, Administração)": "Certo: fácil de gerir e de auditar.",
      "A cada pessoa individualmente": "Funciona, mas torna-se ingerível e propenso a erros.",
      "Ao grupo Todos": "Dá acesso a qualquer um — perigoso.",
      "Ao administrador apenas": "Os utilizadores precisam de acesso para trabalhar."}),
    ("Com a ACL do exemplo, um portátil na VLAN 50 (Convidados) consegue abrir \\\\fs01\\Comum.",
     "Falso. Na ACL do exemplo, a linha 40 nega TCP 445 de qualquer outra origem e a linha 50 nega todo o tráfego da rede de convidados para a VLAN 99 dos servidores. Os convidados ficam isolados dos ficheiros."),
    ("Que comando do router mostra as regras da ACL 110 e os seus contadores?",
     "<code>show access-lists 110</code> mostra cada linha da ACL e, entre parênteses, quantos pacotes coincidiram (matches) — ótimo para confirmar se a regra está a ser usada."),
    ("Que tipo de registo DNS faz fs01.clinica.local apontar para 192.168.99.10?",
     "O registo <b>A</b> liga um nome a um endereço IPv4. MX é correio, PTR é inverso (IP → nome) e CNAME é um alias para outro nome.",
     {"A": "Certo: nome → IPv4.",
      "MX": "MX indica o servidor de correio.",
      "PTR": "PTR faz o inverso: IP → nome.",
      "CNAME": "CNAME aponta para outro nome, não para um IP."}),
    ("A ACL foi aplicada com ip access-group 110 out na subinterface da VLAN 99.",
     "Verdadeiro. Aplicada à <b>saída</b> da subinterface .99, a ACL filtra todo o tráfego que vai das outras VLANs para os servidores, num único ponto."),
    ("Que prefixo serve a Urgência (120 hosts)?",
     "Menor h com 2ʰ − 2 ≥ 120: 2⁶ − 2 = 62 (não), <b>2⁷ − 2 = 126</b> (sim) → <b>/25</b>.",
     {"/25": "Certo: 126 hosts, o mais pequeno que chega para 120.",
      "/24": "Dá 254 hosts: funciona mas desperdiça metade.",
      "/26": "Só 62 hosts: não chega.",
      "/27": "Só 30 hosts: não chega."}),
    ("Que protocolo dá redundância de gateway na distribuição?",
     "O <b>HSRP</b> (ou VRRP/GLBP) cria um IP de gateway virtual partilhado por dois switches de distribuição: se um falhar, o outro assume sem mexer nos PCs.",
     {"HSRP": "Certo: gateway virtual redundante.",
      "STP": "O STP evita loops de camada 2.",
      "DTP": "O DTP negoceia trunks.",
      "CDP": "O CDP descobre vizinhos."}),
    ("A rede de visitantes deve ficar isolada numa VLAN própria.",
     "Verdadeiro. Os visitantes ficam numa <b>VLAN própria</b>, com ACLs que só permitem saída para a Internet — nunca acesso a servidores, impressoras ou gestão interna."),
    ("Qual o endereço de rede de 172.16.77.200/21?",
     "/21 → 3.º octeto com máscara 248, bloco <b>8</b>: …64, <b>72</b>, 80. 77 está entre 72 e 79 → rede <b>172.16.72.0</b>.",
     {"172.16.72.0": "Certo: 77 está no bloco 72–79.",
      "172.16.76.0": "76 não é múltiplo de 8 (seria um /22).",
      "172.16.64.0": "Seria a rede com /20 (bloco 16).",
      "172.16.77.0": "Seria a rede com /24."}),
    ("Que domínio tem mais peso no exame?",
     "Pesos do exame 200-301: Network Fundamentals 20%, Network Access 20%, <b>IP Connectivity 25%</b>, IP Services 10%, Security Fundamentals 15%, Automation and Programmability 10%.",
     {"IP Connectivity": "Certo: 25% (routing, OSPF, rotas estáticas).",
      "Network Fundamentals": "Vale 20%.",
      "Automation": "Vale 10%.",
      "IP Services": "Vale 10%."}),
    ("Quantos hosts tem um /29?",
     "/29 → 3 bits de host: 2³ = 8 endereços − 2 = <b>6</b> hosts úteis.",
     {"6": "Certo: 8 − 2 = 6.",
      "8": "8 é o tamanho do bloco; faltou tirar rede e broadcast.",
      "14": "14 hosts é um /28.",
      "30": "30 hosts é um /27."}),
    ("access-class aplica uma ACL às linhas vty.",
     "Verdadeiro. <code>access-class N in</code> (em <code>line vty</code>) limita quem pode abrir SSH/Telnet ao equipamento. Nas interfaces usa-se <code>ip access-group</code>."),
    ("Por quanto tempo é válida a certificação CCNA?",
     "A CCNA é válida durante <b>3 anos</b>. Renova-se repetindo o exame, passando outro exame de nível igual ou superior, ou com créditos de formação contínua (Continuing Education).",
     {"3 anos": "Certo: validade de 3 anos.",
      "1 ano": "É mais longa.",
      "2 anos": "É mais longa: são 3 anos.",
      "Para sempre": "Tem de ser renovada."}),
    ("No exame CCNA pode voltar atrás para mudar respostas.",
     "Falso. No exame Cisco, depois de confirmar uma resposta e avançar, <b>não pode voltar atrás</b>. Leia cada pergunta com calma antes de carregar em Seguinte."),
    ("Quem aplica o exame?",
     "Os exames Cisco são marcados e aplicados pela <b>Pearson VUE</b>, num centro de exames ou online com vigilância remota (OnVUE).",
     {"Pearson VUE": "Certo: entidade que aplica os exames Cisco.",
      "A escola": "A escola pode preparar, mas o exame oficial é na Pearson VUE.",
      "O operador": "O operador de telecomunicações não tem nada a ver.",
      "O Packet Tracer": "O Packet Tracer é um simulador para praticar."}),
]
