"""Explicações detalhadas do quiz (parte 5: Wi-Fi, routing estático, OSPF, segurança, ACL, NAT, WAN, VPN, QoS, gestão, cloud, SDN)."""

ENTRADAS = [
    ("O WPS deve ficar desligado por ser vulnerável.",
     "Verdadeiro. O <b>WPS</b> por PIN usa 8 dígitos verificados em duas metades, o que permite descobri-lo por força bruta em poucas horas (ferramentas como o Reaver) e assim obter a palavra-passe Wi-Fi. Boa prática: desligar o WPS."),
    ("Para WPA2-Enterprise, a WLC precisa de…",
     "O modo <b>Enterprise</b> usa <b>802.1X</b>: cada utilizador autentica-se com as suas credenciais, validadas por um <b>servidor RADIUS</b> (ex.: Cisco ISE). O modo Personal usa uma palavra-passe partilhada (PSK).",
     {"Um servidor RADIUS": "Certo: 802.1X/EAP valida cada utilizador no RADIUS.",
      "Um servidor DNS": "O DNS é útil na rede, mas não autentica utilizadores Wi-Fi.",
      "Um hub": "Um hub não tem nada a ver com autenticação.",
      "IPv6": "O WPA2-Enterprise funciona em IPv4 ou IPv6; não é requisito."}),
    ("Como se chama a lista de rotas de um router?",
     "A <b>tabela de encaminhamento</b> (routing table) lista as redes que o router conhece, como lá chegar (próximo salto/interface) e de onde veio a informação (C, L, S, O…). Vê-se com <code>show ip route</code>.",
     {"Tabela de encaminhamento": "Certo: routing table, vista com show ip route.",
      "Tabela MAC": "A tabela MAC é do switch (camada 2).",
      "Lista de contactos": "Não é um termo de redes.",
      "VLAN": "Uma VLAN é uma rede lógica num switch."}),
    ("Uma rota escrita à mão pelo técnico é…",
     "Uma <b>rota estática</b> é configurada manualmente (<code>ip route …</code>) e não muda sozinha. As <b>dinâmicas</b> são aprendidas por protocolos como OSPF ou EIGRP, que se adaptam a falhas.",
     {"Estática": "Certo: configurada à mão com ip route.",
      "Dinâmica": "As dinâmicas são aprendidas por protocolos de routing.",
      "Automática": "As redes diretamente ligadas aparecem sozinhas, mas uma rota escrita à mão é estática.",
      "Wireless": "Wireless refere-se ao meio sem fios, não ao tipo de rota."}),
    ("A rota por defeito é usada quando não existe uma rota mais específica.",
     "Verdadeiro. A <b>rota por defeito</b> 0.0.0.0/0 coincide com qualquer destino mas tem o prefixo mais curto (/0), por isso só é usada quando nenhuma outra rota serve — o “último recurso”, normalmente para a Internet."),
    ("Qual a distância administrativa do OSPF?",
     "A <b>distância administrativa</b> (AD) mede a confiança na origem da rota (menor = melhor): ligada 0, estática 1, EIGRP 90, <b>OSPF 110</b>, RIP 120.",
     {"110": "Certo: OSPF = 110.",
      "90": "90 é o EIGRP interno.",
      "120": "120 é o RIP.",
      "1": "1 é a rota estática."}),
    ("Que critério é aplicado primeiro na escolha de rota?",
     "O router escolhe sempre primeiro a rota com o <b>prefixo mais longo</b> (mais específica) que coincide com o destino. Só entre rotas com o mesmo prefixo conta a AD (fonte mais confiável) e depois a métrica.",
     {"Prefixo mais longo": "Certo: longest prefix match vem sempre primeiro.",
      "Menor AD": "A AD só desempata rotas para o mesmo prefixo vindas de fontes diferentes.",
      "Menor métrica": "A métrica só compara rotas do mesmo protocolo para o mesmo prefixo.",
      "Rota mais antiga": "A idade da rota não é critério de escolha."}),
    ("Em [120/3], o que significa o 3?",
     "Em <code>show ip route</code>, os parênteses retos mostram <b>[AD/métrica]</b>. Em [120/3], 120 é a AD (RIP) e <b>3 é a métrica</b> (no RIP, 3 saltos).",
     {"Métrica": "Certo: o segundo número é a métrica.",
      "AD": "A AD é o primeiro número (120).",
      "Saltos de TTL": "O TTL não aparece na tabela de routing.",
      "Número de rotas": "Não indica quantas rotas existem."}),
    ("Uma rota com código L é uma rota /32 do próprio IP da interface.",
     "Verdadeiro. Para cada IP configurado numa interface ativa, o IOS cria uma rota <b>C</b> (a rede ligada) e uma <b>L</b> (local, /32 com o IP exato da interface), usada para tráfego destinado ao próprio router."),
    ("Tráfego para 10.2.5.9 com as rotas 10.2.0.0/16 (OSPF) e 10.2.5.0/24 (estática). Qual é usada?",
     "As duas coincidem com 10.2.5.9, mas a <b>/24 é mais específica</b> do que a /16. O prefixo mais longo ganha sempre, antes de olhar para a AD.",
     {"Estática /24, prefixo mais longo": "Certo: o /24 é mais específico.",
      "OSPF, porque é dinâmica": "Ser dinâmica não dá prioridade; ganha o prefixo mais longo.",
      "As duas em balanceamento": "Só há balanceamento entre rotas iguais para o mesmo prefixo.",
      "Nenhuma": "As duas coincidem; usa-se a mais específica."}),
    ("Escreva a rota por defeito via 203.0.113.1.",
     "<code>ip route 0.0.0.0 0.0.0.0 203.0.113.1</code>, no modo de configuração global: rede 0.0.0.0 com máscara 0.0.0.0 (/0) coincide com qualquer destino, enviado para o próximo salto 203.0.113.1 (normalmente o router do operador). Aparece na tabela como S*."),
    ("O que é uma rota estática flutuante?",
     "Uma <b>rota flutuante</b> é uma estática com <b>AD maior</b> do que a rota principal (ex.: <code>ip route 0.0.0.0 0.0.0.0 10.9.9.1 200</code>). Fica escondida enquanto a principal existe e só entra na tabela se esta desaparecer — é uma rota de reserva.",
     {"Rota com AD maior que a principal, usada como reserva": "Certo: só aparece quando a principal cai.",
      "Rota sem máscara": "Todas as rotas têm máscara.",
      "Rota aprendida por OSPF": "Rotas OSPF são dinâmicas, não estáticas flutuantes.",
      "Rota /32": "Uma /32 é uma rota para um host, não necessariamente flutuante."}),
    ("Uma rota estática IPv6 com next hop link-local precisa da interface de saída.",
     "Verdadeiro. Os endereços link-local (FE80::) repetem-se em várias ligações, por isso o router precisa de saber por que interface sair: <code>ipv6 route ::/0 g0/0 FE80::1</code>."),
    ("Qual a AD por defeito de uma rota estática?",
     "As rotas estáticas têm <b>AD 1</b> por defeito (as diretamente ligadas têm 0). Pode alterar-se no fim do comando para criar rotas flutuantes.",
     {"1": "Certo: estática = 1.",
      "0": "0 é das redes diretamente ligadas.",
      "5": "5 é o EIGRP sumário.",
      "110": "110 é o OSPF."}),
    ("Um router aprende 10.10.0.0/16 por OSPF e por RIP. Qual entra na tabela?",
     "Mesmo prefixo, protocolos diferentes → decide a <b>AD</b>: OSPF 110 &lt; RIP 120, por isso entra a rota <b>OSPF</b>. As métricas não se comparam entre protocolos diferentes.",
     {"OSPF, menor AD": "Certo: 110 vence 120.",
      "RIP, menor métrica": "Métricas de protocolos diferentes não são comparáveis (saltos vs custo).",
      "Ambas": "Para o mesmo prefixo só entra a da fonte mais confiável.",
      "A mais recente": "A ordem de chegada não conta."}),
    ("GigabitEthernet e FastEthernet com reference-bandwidth padrão têm custo OSPF…",
     "Custo OSPF = largura de banda de referência (100 Mbit/s por defeito) ÷ largura de banda da interface, com mínimo 1. FastEthernet: 100/100 = 1; Gigabit: 100/1000 = 0,1 → <b>1</b>. Por isso convém subir a referência (<code>auto-cost reference-bandwidth 10000</code>).",
     {"1 e 1": "Certo: ambos ficam no mínimo 1.",
      "1 e 10": "Seria assim com referência de 1000 Mbit/s.",
      "4 e 19": "Esses são custos do STP, não do OSPF.",
      "10 e 100": "Seria com referência de 10 000 Mbit/s."}),
    ("Escreva a rota estática para 10.5.0.0/16 via 172.16.1.2 com AD 200.",
     "<code>ip route 10.5.0.0 255.255.0.0 172.16.1.2 200</code>: rede, máscara, próximo salto e, no fim, a AD. Com AD 200 a rota fica como reserva (flutuante) de uma rota OSPF (110) ou estática normal (1)."),
    ("Entre dois routers DROther numa rede Ethernet a vizinhança fica em 2-WAY.",
     "Verdadeiro. Numa rede multiacesso, os routers só formam adjacência <b>FULL</b> com o DR e o BDR. Entre dois DROther a relação fica em <b>2-WAY</b> — é normal, não é avaria."),
    ("A ida chega mas a resposta não volta. Causa mais provável?",
     "A comunicação tem <b>dois sentidos</b>: o router do destino também precisa de uma rota de regresso para a rede de origem. Se a ida funciona e a volta não, falta normalmente a <b>rota de volta</b> (ou o gateway no host de destino).",
     {"Falta a rota de volta": "Certo: cada router precisa de saber o caminho para a origem.",
      "Cabo errado": "Com cabo errado nem a ida chegaria.",
      "DNS": "O DNS não interfere com pacotes já endereçados por IP.",
      "VLAN": "Uma VLAN errada impediria também a ida."}),
    ("Que comando mostra só as rotas estáticas?",
     "<code>show ip route static</code> filtra a tabela de routing e mostra só as rotas com código S (incluindo a rota por defeito S*)."),
    ("Uma rota estática com next hop inalcançável não entra na tabela.",
     "Verdadeiro. O router só instala a rota estática se conseguir resolver o <b>próximo salto</b> (tem de haver uma rota para ele, normalmente uma rede ligada). Se a interface para o next hop cair, a rota sai da tabela — e uma flutuante pode entrar."),
    ("Que ferramenta mostra em que salto o caminho para?",
     "O <b>traceroute</b> (no Windows <code>tracert</code>) mostra cada router do caminho até ao destino. O último salto que responde indica onde a comunicação para.",
     {"traceroute": "Certo: lista os saltos e mostra onde deixa de haver resposta.",
      "ipconfig": "Mostra a configuração IP do PC, não o caminho.",
      "arp": "Mostra a tabela IP→MAC local.",
      "nslookup": "Consulta o DNS."}),
    ("Que algoritmo calcula os caminhos no OSPF?",
     "O OSPF é um protocolo <b>link-state</b>: cada router tem o mapa completo da área (LSDB) e corre o algoritmo <b>SPF de Dijkstra</b> para calcular o caminho de menor custo para cada rede.",
     {"SPF de Dijkstra": "Certo: Shortest Path First.",
      "Bellman-Ford": "Bellman-Ford é usado por protocolos distance-vector como o RIP.",
      "DUAL": "DUAL é o algoritmo do EIGRP.",
      "STP": "STP é o Spanning Tree Protocol, de camada 2."}),
    ("Em que estado ficam dois DROther entre si?",
     "Dois routers DROther na mesma LAN veem-se nos Hellos mas não trocam LSDB diretamente: ficam em <b>2-Way</b>. A sincronização faz-se através do DR/BDR.",
     {"2-Way": "Certo: só formam Full com o DR e o BDR.",
      "Full": "Full só com DR e BDR.",
      "Init": "Init é um estado transitório (recebi um Hello mas ainda não me vejo nele).",
      "Down": "Down significa que não há Hellos."}),
    ("Custo OSPF de uma interface de 10 Mbit/s (referência 100)?",
     "Custo = 100 Mbit/s ÷ 10 Mbit/s = <b>10</b>.",
     {"10": "Certo: 100 ÷ 10 = 10.",
      "1": "1 é o custo de 100 Mbit/s ou mais.",
      "100": "100 é o custo STP de 10 Mbit/s, não o OSPF.",
      "1000": "Não segue a fórmula."}),
    ("Todos os routers da mesma área têm a mesma LSDB.",
     "Verdadeiro. Dentro de uma área OSPF, todos os routers trocam LSAs até terem a <b>mesma base de dados</b> (LSDB). É isso que garante que todos calculam caminhos coerentes e sem loops."),
    ("Qual o endereço multicast dos Hellos OSPF para todos os routers?",
     "O OSPF envia Hellos para <b>224.0.0.5</b> (todos os routers OSPF). O <b>224.0.0.6</b> é para o DR e o BDR. 224.0.0.10 é EIGRP e 224.0.0.2 todos os routers.",
     {"224.0.0.5": "Certo: AllSPFRouters.",
      "224.0.0.2": "224.0.0.2 é “todos os routers” (usado por exemplo pelo HSRP v1).",
      "224.0.0.6": "224.0.0.6 é só para DR/BDR.",
      "224.0.0.10": "224.0.0.10 é o EIGRP."}),
    ("Qual o wildcard de 255.255.255.248?",
     "Wildcard = 255 − cada octeto: 0.0.0.(255 − 248) = <b>0.0.0.7</b>. Atalho: bloco 8 − 1 = 7.",
     {"0.0.0.7": "Certo: 255 − 248 = 7.",
      "0.0.0.8": "8 é o tamanho do bloco; a wildcard é o bloco − 1.",
      "0.0.0.248": "Não se inverte assim; 248 é o próprio octeto da máscara.",
      "255.255.255.7": "Os primeiros octetos da wildcard são 0, não 255."}),
    ("Como é escolhido o router ID sem configuração manual?",
     "O router ID OSPF escolhe-se por esta ordem: (1) <code>router-id</code> configurado; (2) <b>maior IP de uma loopback ativa</b>; (3) maior IP de uma interface física ativa.",
     {"Maior IP de loopback ativa": "Certo: sem router-id manual, ganha a loopback mais alta.",
      "Menor IP de interface": "É o maior, não o menor.",
      "MAC mais baixo": "O router ID é um valor de 32 bits no formato IP, não um MAC.",
      "Process ID": "O process ID é só local e não define o router ID."}),
    ("O process ID do OSPF tem de coincidir entre vizinhos.",
     "Falso. O <b>process ID</b> (<code>router ospf 1</code>) só tem significado local. O que tem de coincidir entre vizinhos é: área, sub-rede/máscara, timers Hello/Dead, autenticação e MTU."),
    ("Dois routers ficam presos em EXSTART. Causa mais provável?",
     "Em <b>EXSTART/EXCHANGE</b> os routers trocam descrições da base de dados (DBD). Se o <b>MTU</b> for diferente nas duas pontas, os DBD grandes são recusados e a adjacência fica presa aí.",
     {"MTU diferente": "Certo: impede a troca de DBD.",
      "Área diferente": "Com áreas diferentes nem passavam do Hello (não ficavam vizinhos).",
      "Process ID diferente": "O process ID é local; não afeta a adjacência.",
      "Router ID igual a 0": "Um router ID 0.0.0.0 não é o problema típico do EXSTART."}),
    ("Que comando impede o envio de Hellos para a LAN g0/0 mantendo a rede anunciada (dentro de router ospf)?",
     "<code>passive-interface g0/0</code>, dentro de <code>router ospf</code>, deixa de enviar Hellos por essa interface (não há routers na LAN, só PCs) mas continua a anunciar a sua rede aos vizinhos. Melhora a segurança e poupa recursos."),
    ("O que garante integridade?",
     "Um <b>hash</b> (ex.: SHA-256) gera uma “impressão digital” dos dados: se mudar um bit, o hash muda. Comparando hashes, prova-se que os dados não foram alterados — <b>integridade</b>. A cifra garante confidencialidade.",
     {"Hash": "Certo: qualquer alteração muda o hash.",
      "Cifra simétrica": "A cifra protege a confidencialidade, não prova que nada mudou.",
      "NAT": "O NAT traduz endereços.",
      "VLAN": "As VLANs separam redes."}),
    ("Que cifra usa a mesma chave dos dois lados?",
     "Na cifra <b>simétrica</b> (AES, 3DES) a mesma chave cifra e decifra: é rápida, mas é preciso partilhar a chave em segredo. Na <b>assimétrica</b> (RSA) há um par chave pública/privada.",
     {"Simétrica": "Certo: a mesma chave nos dois lados (ex.: AES).",
      "Assimétrica": "Usa duas chaves diferentes (pública e privada).",
      "Hash": "Um hash não usa chave para decifrar; é de sentido único.",
      "PKI": "PKI é a infraestrutura de certificados, baseada em cifra assimétrica."}),
    ("Um SYN flood ataca…",
     "Num <b>SYN flood</b> o atacante envia milhares de SYN (muitas vezes com IP falso) e nunca termina o handshake. O servidor fica com milhares de ligações meio abertas e deixa de aceitar clientes legítimos — um DoS ao <b>handshake TCP</b>.",
     {"O handshake TCP": "Certo: esgota as ligações meio abertas.",
      "O DNS": "Há ataques ao DNS, mas o SYN flood ataca o TCP.",
      "O cabo": "Não é um ataque físico.",
      "O Wi-Fi": "Funciona em qualquer meio; o alvo é o TCP."}),
    ("Os certificados digitais ajudam a provar a identidade de um servidor.",
     "Verdadeiro. Um certificado associa uma chave pública a um nome (ex.: www.banco.pt) e é <b>assinado por uma autoridade de certificação</b> (PKI) em que o browser confia. Assim sabe que fala com o servidor verdadeiro."),
    ("Wildcard para 172.16.32.0/20?",
     "/20 = 255.255.240.0. Wildcard = 255 − cada octeto = <b>0.0.15.255</b>.",
     {"0.0.15.255": "Certo: 255 − 240 = 15; 255 − 0 = 255.",
      "0.0.31.255": "0.0.31.255 corresponde a /19.",
      "255.255.240.0": "Essa é a máscara, não a wildcard.",
      "0.0.0.15": "0.0.0.15 corresponde a /28."}),
    ("Uma ACL só com deny ip host 10.1.1.5 any. O que acontece ao resto do tráfego?",
     "Todas as ACL terminam com um <b>deny any implícito</b> invisível. Uma ACL só com uma linha deny bloqueia esse host <b>e tudo o resto</b>. É preciso acrescentar <code>permit ip any any</code> no fim.",
     {"É bloqueado pelo deny implícito": "Certo: sem um permit, nada passa.",
      "Passa": "Só passaria se houvesse um permit explícito.",
      "É registado": "Só seria registado com a palavra log numa linha explícita.",
      "Vai para o CPU": "O tráfego bloqueado é descartado, não enviado ao CPU."}),
    ("Onde aplicar uma ACL extended?",
     "Uma ACL <b>extended</b> filtra por origem, destino, protocolo e porta, por isso é precisa: aplica-se <b>perto da origem</b>, para o tráfego indesejado ser descartado logo e não gastar largura de banda.",
     {"Perto da origem": "Certo: é precisa, por isso corta o tráfego cedo.",
      "Perto do destino": "Isso é para as standard, que só veem a origem.",
      "Na consola": "A consola não é uma interface de dados.",
      "Em todas as interfaces": "Desnecessário e difícil de gerir."}),
    ("A ordem das regras numa ACL é importante.",
     "Verdadeiro. A ACL é lida <b>de cima para baixo</b> e para na <b>primeira linha que coincide</b>. Uma regra genérica antes de uma específica “tapa” a específica. Coloque as regras mais específicas primeiro."),
    ("Onde deve aplicar uma ACL standard?",
     "Uma ACL <b>standard</b> só olha para o IP de <b>origem</b>. Se fosse aplicada perto da origem, bloquearia esse tráfego para <i>todos</i> os destinos. Por isso aplica-se <b>perto do destino</b>.",
     {"Perto do destino": "Certo: assim só bloqueia o acesso àquele destino.",
      "Perto da origem": "Bloquearia a origem para todos os destinos, não só o pretendido.",
      "Em todas as interfaces": "Seria excessivo e confuso.",
      "Na linha de consola": "A consola não filtra tráfego de rede (para vty usa-se access-class)."}),
    ("O que acontece a um pacote que não coincide com nenhuma linha?",
     "No fim de qualquer ACL há um <b>deny any implícito</b>: um pacote que não coincide com nenhuma linha é <b>descartado</b>.",
     {"É descartado (deny implícito)": "Certo: deny any implícito no fim.",
      "É permitido": "Seria preciso um permit any explícito.",
      "É enviado ao CPU": "Não; é descartado.",
      "É registado e permitido": "Nem é registado (o deny implícito não regista) nem permitido."}),
    ("Qual o wildcard para 172.16.0.0/20?",
     "/20 → máscara 255.255.240.0 → wildcard <b>0.0.15.255</b> (255 − 240 = 15).",
     {"0.0.15.255": "Certo: inverso de 255.255.240.0.",
      "0.0.16.255": "16 é o tamanho do bloco; a wildcard é 16 − 1 = 15.",
      "255.255.240.0": "É a máscara, não a wildcard.",
      "0.0.0.15": "Corresponde a /28."}),
    ("Que comando aplica a ACL 101 na entrada de uma interface?",
     "<code>ip access-group 101 in</code>, no modo de interface, aplica a ACL 101 ao tráfego que <b>entra</b> nessa interface (<code>out</code> para o que sai). Criar a ACL não basta: sem access-group ela não faz nada."),
    ("Pode aplicar duas ACLs IPv4 na mesma interface e no mesmo sentido.",
     "Falso. A regra é <b>uma ACL por interface, por sentido, por protocolo</b>. Se aplicar uma segunda com ip access-group no mesmo sentido, substitui a primeira. Junte todas as regras numa só ACL."),
    ("Que número identifica uma ACL extended?",
     "ACLs numeradas: <b>1–99</b> e 1300–1999 são standard; <b>100–199</b> e 2000–2699 são extended. 150 está entre 100 e 199 → extended.",
     {"150": "Certo: 100–199 = extended.",
      "10": "1–99 = standard.",
      "99": "99 ainda é standard.",
      "1350": "1300–1999 é a gama expandida das standard."}),
    ("Uma ACL extended 'deny tcp any host 10.0.0.10 eq 80' sem mais linhas é aplicada. O que acontece ao resto do tráfego?",
     "A única linha bloqueia HTTP para 10.0.0.10; tudo o resto bate no <b>deny implícito</b> e também é bloqueado. Faltou <code>permit ip any any</code> no fim.",
     {"É bloqueado pelo deny implícito": "Certo: sem permit, nada mais passa.",
      "É permitido": "Só se houvesse um permit explícito.",
      "Só ICMP passa": "O ICMP também bate no deny implícito.",
      "Depende do sentido": "Em qualquer sentido onde for aplicada, o deny implícito bloqueia o resto."}),
    ("Qual ferramenta impede que um utilizador ligue um router doméstico que distribua IPs na rede?",
     "Um router doméstico ligado à rede começa a responder a pedidos DHCP (servidor DHCP falso). O <b>DHCP snooping</b> bloqueia DHCP Offers/Acks que cheguem por portas <b>untrusted</b>.",
     {"DHCP snooping": "Certo: só aceita respostas DHCP por portas trusted.",
      "Port security": "Limita MACs por porta, mas o router falso pode ter um só MAC.",
      "BPDU guard": "Reage a BPDUs de switches, não a DHCP.",
      "CDP": "O CDP descobre vizinhos Cisco."}),
    ("Que comando de linha aplica a ACL 5 ao acesso vty?",
     "<code>access-class 5 in</code>, dentro de <code>line vty 0 4</code>, restringe quem pode abrir SSH/Telnet ao equipamento às origens permitidas na ACL 5. Nas interfaces usa-se ip access-group; nas linhas vty, access-class."),
    ("O IP privado de um PC interno, do ponto de vista da LAN, é o…",
     "Termos do NAT: <b>inside local</b> = IP privado do host interno (ex.: 192.168.1.10); <b>inside global</b> = IP público que o representa na Internet; <b>outside global</b> = IP real do servidor externo.",
     {"Inside local": "Certo: endereço interno visto de dentro.",
      "Inside global": "É o IP público que representa o host interno lá fora.",
      "Outside local": "É como um host externo é visto de dentro (normalmente igual ao outside global).",
      "Outside global": "É o IP real de um host externo."}),
    ("Que palavra-chave ativa o PAT?",
     "No comando <code>ip nat inside source list 1 interface g0/1 <b>overload</b></code>, a palavra <b>overload</b> ativa o PAT: muitos endereços internos partilham um só IP público, distinguidos pelas portas.",
     {"overload": "Certo: overload = PAT.",
      "static": "static cria um mapeamento fixo 1:1.",
      "pool": "pool define um conjunto de IPs públicos para NAT dinâmico.",
      "extendable": "extendable permite vários estáticos com o mesmo IP, não ativa PAT."}),
    ("Que comando mostra as traduções NAT ativas?",
     "<code>show ip nat translations</code> lista as traduções ativas: inside local, inside global, outside local, outside global e, no PAT, as portas. <code>show ip nat statistics</code> mostra contadores."),
    ("Com PAT, vários hosts internos partilham um único IP público, diferenciados pelas portas.",
     "Verdadeiro. No <b>PAT</b> (NAT overload) o router regista cada ligação com o par IP:porta interno e o IP público:porta usado. Assim milhares de ligações partilham um só IP público."),
    ("PCs na VLAN 30 recebem 169.254.x.x. O servidor DHCP está noutra rede. O que falta provavelmente?",
     "O DHCP Discover é um <b>broadcast</b> e os routers não encaminham broadcasts. Com o servidor noutra rede, o gateway da VLAN 30 precisa de <code>ip helper-address</code> (DHCP relay). Sem resposta, os PCs ficam em APIPA (169.254).",
     {"ip helper-address na SVI/subinterface da VLAN 30": "Certo: transforma o broadcast em unicast para o servidor.",
      "ip nat inside": "O NAT não tem nada a ver com a entrega de IPs.",
      "ntp server": "O NTP sincroniza relógios.",
      "Um pool por defeito": "O pool está no servidor; o problema é o pedido não lá chegar."}),
    ("Que tipo de NAT permite que a Internet aceda a um servidor web interno sempre pelo mesmo IP?",
     "O <b>NAT estático</b> cria um mapeamento fixo 1:1 entre um IP privado e um IP público (<code>ip nat inside source static 192.168.1.10 203.0.113.10</code>), por isso de fora o servidor é sempre alcançável pelo mesmo IP.",
     {"NAT estático": "Certo: mapeamento fixo 1:1, permanente.",
      "PAT": "O PAT serve sobretudo ligações iniciadas de dentro para fora.",
      "NAT dinâmico": "O IP público muda conforme o pool; não é fixo.",
      "NAT64": "NAT64 traduz entre IPv6 e IPv4."}),
    ("O SNMP usa a porta UDP 162 para traps.",
     "Verdadeiro. O SNMP usa <b>UDP 161</b> para consultas do gestor aos agentes (get/set) e <b>UDP 162</b> para traps/informs enviados pelos agentes ao gestor."),
    ("Topologia em que as filiais falam através da sede?",
     "No <b>hub-and-spoke</b> (estrela WAN), a sede é o hub e cada filial (spoke) liga-se só a ela; o tráfego filial-filial passa pela sede. É barato mas a sede é ponto central de falha.",
     {"Hub-and-spoke": "Certo: filiais ligadas à sede, que faz de centro.",
      "Malha completa": "Na malha completa todas as filiais se ligam diretamente entre si.",
      "Ponto a ponto": "Ponto a ponto liga apenas dois locais.",
      "Anel": "Num anel cada local liga-se a dois vizinhos."}),
    ("Que tecnologia é uma rede privada do operador com SLA?",
     "O <b>MPLS</b> é uma rede privada do operador que liga as filiais com garantias contratuais (<b>SLA</b>) de largura de banda, latência e disponibilidade, e suporta QoS.",
     {"MPLS": "Certo: WAN privada do operador, com SLA.",
      "Wi-Fi": "Wi-Fi é uma tecnologia de rede local sem fios.",
      "Bluetooth": "Bluetooth é para ligações pessoais de curta distância.",
      "Hub": "Um hub é um repetidor de camada 1."}),
    ("Para uma aldeia sem cabo nem fibra, a opção típica é…",
     "Sem infraestrutura com fios, a ligação faz-se por meios <b>sem fios</b>: <b>satélite</b> (ex.: órbita baixa) ou rede móvel <b>4G/5G</b>.",
     {"Satélite ou 4G/5G": "Certo: não precisam de cabos até ao local.",
      "MPLS": "O MPLS precisa de uma ligação física do operador até ao local.",
      "Cabo coaxial": "Exige cabo instalado, que não existe.",
      "Ethernet": "Ethernet com cabo só chega a 100 m (cobre) ou exige fibra."}),
    ("O SD-WAN pode usar várias ligações e escolher a melhor por aplicação.",
     "Verdadeiro. O <b>SD-WAN</b> combina ligações (MPLS, fibra, 4G) sob controlo centralizado e escolhe dinamicamente o caminho para cada aplicação conforme a latência, perdas e políticas (ex.: voz pelo MPLS, backups pela Internet)."),
    ("Que protocolo IPsec cifra os dados?",
     "No IPsec, o <b>ESP</b> (Encapsulating Security Payload) dá confidencialidade (cifra), integridade e autenticação. O <b>AH</b> só dá integridade e autenticação, sem cifra. O <b>IKE</b> negoceia as chaves.",
     {"ESP": "Certo: ESP cifra o conteúdo.",
      "AH": "O AH autentica mas não cifra.",
      "GRE": "O GRE é um túnel sem cifra.",
      "IKE": "O IKE negoceia chaves e parâmetros, não cifra os dados do utilizador."}),
    ("Que tipo de VPN liga a sede à filial de forma permanente?",
     "Uma VPN <b>site-to-site</b> liga duas redes inteiras (sede e filial) de forma permanente, entre routers ou firewalls; os utilizadores nem precisam de software. A de <b>acesso remoto</b> liga um utilizador individual.",
     {"Site-to-site": "Certo: rede a rede, permanente.",
      "Acesso remoto": "Liga um utilizador (portátil) à rede, quando ele precisa.",
      "Clientless": "Clientless é acesso remoto pelo browser.",
      "SSL web": "VPN SSL web é também acesso remoto de utilizadores."}),
    ("Um túnel GRE sem IPsec cifra o tráfego.",
     "Falso. O <b>GRE</b> só encapsula pacotes (incluindo multicast e protocolos de routing) dentro de outro IP; não cifra. Para confidencialidade usa-se <b>GRE sobre IPsec</b>."),
    ("IKE usa a porta…",
     "O <b>IKE</b> (negociação de chaves do IPsec) usa <b>UDP 500</b>; com NAT pelo meio (NAT-T) passa para UDP 4500.",
     {"UDP 500": "Certo: IKE = UDP 500 (4500 com NAT-T).",
      "TCP 443": "TCP 443 é HTTPS (e VPNs SSL).",
      "TCP 49": "TCP 49 é o TACACS+.",
      "UDP 69": "UDP 69 é o TFTP."}),
    ("Que marcação DSCP se usa para voz?",
     "A voz usa <b>EF</b> (Expedited Forwarding, DSCP 46): fila prioritária, baixa latência. AF41 costuma ser vídeo; CS1 tráfego de baixa prioridade; BE (0) o tráfego normal.",
     {"EF": "Certo: EF = DSCP 46, para voz.",
      "AF41": "AF41 é usado para videoconferência.",
      "CS1": "CS1 é tráfego de baixa prioridade (scavenger).",
      "BE": "BE (best effort) é o tráfego sem prioridade."}),
    ("Qual a diferença entre policing e shaping?",
     "<b>Policing</b> aplica um limite à força: o tráfego em excesso é <b>descartado ou remarcado</b>. <b>Shaping</b> guarda o excesso num <b>buffer</b> e envia-o mais tarde, suavizando o débito (à custa de algum atraso).",
     {"Policing descarta/remarca, shaping atrasa em buffer": "Certo: policing corta, shaping suaviza.",
      "Policing atrasa, shaping descarta": "Está trocado.",
      "São iguais": "Os dois limitam o débito, mas de formas diferentes.",
      "Shaping só funciona em IPv6": "Funciona em IPv4 e IPv6."}),
    ("Qual o atraso máximo recomendado para voz, num sentido?",
     "Para voz com qualidade recomenda-se no máximo <b>150 ms</b> de atraso num sentido, menos de 30 ms de jitter e menos de 1% de perdas.",
     {"150 ms": "Certo: até 150 ms num sentido.",
      "50 ms": "É ótimo, mas não é o limite recomendado.",
      "400 ms": "Com 400 ms a conversa torna-se difícil.",
      "1 s": "Um segundo de atraso tornaria a conversa impossível."}),
    ("O WRED ajuda a evitar a sincronização global do TCP.",
     "Verdadeiro. Quando uma fila enche e descarta tudo de uma vez (tail drop), todas as ligações TCP abrandam e aceleram ao mesmo tempo (sincronização global). O <b>WRED</b> descarta cedo e aleatoriamente alguns pacotes, mantendo o débito estável."),
    ("Que nível Syslog é 'Warning'?",
     "Níveis Syslog (0 = mais grave): 0 Emergency, 1 Alert, 2 Critical, 3 Error, <b>4 Warning</b>, 5 Notification, 6 Informational, 7 Debugging. Mnemónica: “Every Awesome Cisco Engineer Will Need Ice-cream Daily”.",
     {"4": "Certo: 4 = Warning.",
      "2": "2 = Critical.",
      "3": "3 = Error.",
      "5": "5 = Notification."}),
    ("Que versão SNMP oferece cifra?",
     "Só o <b>SNMPv3</b> tem segurança a sério: autenticação de utilizadores e cifra (nível authPriv). O v1 e o v2c usam community strings em texto claro.",
     {"v3": "Certo: autenticação e privacidade (cifra).",
      "v1": "O v1 usa community strings sem cifra.",
      "v2c": "O v2c também usa community strings em texto claro.",
      "Todas": "Só a v3 cifra."}),
    ("TFTP usa…",
     "O <b>TFTP</b> usa <b>UDP 69</b>, sem autenticação nem cifra. Usa-se em redes de gestão para copiar imagens IOS e configurações (<code>copy running-config tftp:</code>).",
     {"UDP 69": "Certo: simples, sem autenticação.",
      "TCP 21": "TCP 21 é o FTP.",
      "TCP 69": "O TFTP é UDP, não TCP.",
      "UDP 161": "UDP 161 é o SNMP."}),
    ("Que comando faz R1 sincronizar com o servidor NTP 10.1.1.1?",
     "<code>ntp server 10.1.1.1</code>, no modo de configuração global, faz o router sincronizar o relógio com esse servidor. Verifique com <code>show ntp status</code> e <code>show ntp associations</code>."),
    ("Uma trap SNMP é confirmada pelo gestor.",
     "Falso. As <b>traps</b> são enviadas sem confirmação (podem perder-se). Os <b>informs</b> (SNMPv2c/v3) são confirmados pelo gestor e retransmitidos se necessário."),
    ("Que camada liga os utilizadores?",
     "Na arquitetura hierárquica, a camada de <b>acesso</b> é onde se ligam PCs, impressoras, telefones IP e APs. A distribuição agrega e aplica políticas; o núcleo transporta rapidamente.",
     {"Acesso": "Certo: é a camada dos utilizadores finais.",
      "Distribuição": "A distribuição agrega os switches de acesso.",
      "Núcleo": "O núcleo é a espinha dorsal de alta velocidade.",
      "WAN": "A WAN liga locais distantes."}),
    ("Onde ficam normalmente as SVIs e o HSRP?",
     "Na camada de <b>distribuição</b>: é aí que terminam as VLANs (SVIs, routing entre VLANs) e se dá redundância de gateway com HSRP/VRRP, além de ACLs e políticas.",
     {"Distribuição": "Certo: routing entre VLANs e gateways redundantes.",
      "Acesso": "O acesso costuma ser só camada 2.",
      "Núcleo": "O núcleo deve ser simples e rápido, sem políticas.",
      "No PC": "O PC só usa o gateway; não o fornece."}),
    ("Entre edifícios usa-se normalmente fibra ótica.",
     "Verdadeiro. Entre edifícios as distâncias passam facilmente os 100 m do UTP, e a fibra não conduz eletricidade: evita problemas de diferenças de terra e trovoadas."),
    ("Que método começa pelo cabo e pela luz da porta?",
     "O método <b>de baixo para cima</b> (bottom-up) começa na camada 1 (cabos, LEDs, interfaces) e sobe pelas camadas. É bom quando se suspeita de problema físico.",
     {"De baixo para cima": "Certo: bottom-up, da camada 1 para cima.",
      "De cima para baixo": "Top-down começa pela aplicação (camada 7).",
      "Comparação": "Comparar com um equipamento que funciona é outro método.",
      "Substituição": "Trocar peças suspeitas é outro método (swap)."}),
    ("O que é a linha de base?",
     "A <b>linha de base</b> (baseline) é o registo do desempenho <b>normal</b> da rede (utilização, latência, erros). Serve para comparar: sem ela não sabe se 70% de CPU é normal ou um problema.",
     {"O desempenho normal da rede": "Certo: a referência para comparar.",
      "O primeiro cabo": "Não é um cabo.",
      "A VLAN 1": "A VLAN 1 é só a VLAN por defeito.",
      "O router principal": "Não é um equipamento."}),
    ("O último passo da resolução é documentar.",
     "Verdadeiro. Depois de resolver e verificar, <b>documenta-se</b> o problema, a causa e a solução: na próxima vez resolve-se mais depressa e a documentação da rede fica atualizada."),
    ("Office online é um exemplo de…",
     "Software usado diretamente pelo browser, gerido pelo fornecedor, é <b>SaaS</b>. PaaS dá uma plataforma para programar; IaaS dá máquinas virtuais.",
     {"SaaS": "Certo: software como serviço, pronto a usar.",
      "IaaS": "IaaS dá infraestrutura (VMs, redes).",
      "PaaS": "PaaS dá plataforma de desenvolvimento.",
      "Hipervisor": "Um hipervisor corre máquinas virtuais."}),
    ("VirtualBox é um hipervisor de tipo…",
     "Hipervisor de <b>tipo 1</b> (bare-metal) corre diretamente no hardware (ESXi, Hyper-V). <b>Tipo 2</b> corre como programa dentro de um sistema operativo (VirtualBox, VMware Workstation).",
     {"2": "Certo: corre sobre um sistema operativo anfitrião.",
      "1": "Tipo 1 corre diretamente no hardware (ex.: ESXi).",
      "3": "Não existe hipervisor de tipo 3.",
      "0": "Não existe hipervisor de tipo 0."}),
    ("Uma cloud híbrida mistura cloud privada e pública.",
     "Verdadeiro. Uma <b>cloud híbrida</b> combina recursos privados (no centro de dados da empresa) com uma cloud pública, com integração entre os dois — ex.: dados sensíveis em casa, picos de carga na cloud pública."),
    ("OSPF pertence a que plano?",
     "Planos de um equipamento: <b>dados</b> (encaminhar pacotes), <b>controlo</b> (decidir caminhos: OSPF, STP, ARP) e <b>gestão</b> (SSH, SNMP). O OSPF calcula rotas → plano de <b>controlo</b>.",
     {"Controlo": "Certo: protocolos de routing decidem o caminho.",
      "Dados": "O plano de dados encaminha os pacotes com base nas tabelas já calculadas.",
      "Gestão": "O plano de gestão serve para administrar (SSH, SNMP).",
      "Aplicação": "Não é um dos planos do equipamento."}),
    ("A API entre um script Python e o controlador é…",
     "No SDN, a <b>northbound API</b> (normalmente REST) liga aplicações e scripts ao controlador; a <b>southbound API</b> liga o controlador aos equipamentos (NETCONF, OpenFlow…).",
     {"Northbound": "Certo: aplicações → controlador.",
      "Southbound": "A southbound liga o controlador aos equipamentos.",
      "Eastbound": "East/westbound liga controladores entre si.",
      "Underlay": "Underlay é a rede física por baixo de um overlay."}),
    ("SSH para gerir um router faz parte do plano de gestão.",
     "Verdadeiro. O <b>plano de gestão</b> inclui tudo o que serve para administrar o equipamento: SSH, SNMP, Syslog, NTP, APIs. O plano de controlo decide caminhos e o de dados encaminha."),
    ("Que tecnologia de overlay usa o SD-Access?",
     "O <b>SD-Access</b> (Cisco DNA Center) usa <b>VXLAN</b> para o overlay (plano de dados) e <b>LISP</b> no plano de controlo, sobre um underlay IP.",
     {"VXLAN": "Certo: VXLAN no plano de dados.",
      "GRE": "GRE é usado noutros túneis, não no SD-Access.",
      "MPLS": "MPLS é tecnologia WAN de operador.",
      "PPP": "PPP é um protocolo de ligação série."}),
    ("Qual a principal vantagem da automação?",
     "A automação faz tarefas repetitivas de forma <b>rápida, consistente e sem erros de escrita</b>: a mesma alteração em 200 switches sai igual em todos, em minutos.",
     {"Fazer tarefas repetitivas de forma rápida e consistente": "Certo: rapidez e consistência.",
      "Gastar mais cabos": "A automação não tem a ver com cabos.",
      "Desligar a firewall": "Pelo contrário, automação pode aplicar políticas de segurança.",
      "Eliminar o IP": "A automação usa o IP para falar com os equipamentos."}),
    ("Python é muito usado na automação de redes.",
     "Verdadeiro. O <b>Python</b> é simples e tem bibliotecas para redes: <b>Netmiko</b> (SSH), <b>NAPALM</b>, <b>Nornir</b>, <b>ncclient</b> (NETCONF) e <b>requests</b> (APIs REST)."),
    ("Com automação, uma alteração em 100 switches…",
     "Um script percorre a lista de equipamentos e aplica a mesma configuração a todos, <b>em minutos</b> e sem erros de escrita — à mão seriam horas.",
     {"Pode ser feita por um script em minutos": "Certo: o script repete a tarefa em todos.",
      "É impossível": "É exatamente o tipo de tarefa que a automação resolve.",
      "Exige trocar os switches": "Funciona com os equipamentos existentes (SSH, APIs).",
      "Só funciona com Wi-Fi": "Não depende do meio físico."}),
    ("Que verbo HTTP corresponde a 'Create'?",
     "CRUD em REST: <b>Create = POST</b>, Read = GET, Update = PUT/PATCH, Delete = DELETE.",
     {"POST": "Certo: POST cria um recurso.",
      "GET": "GET lê (Read).",
      "PUT": "PUT atualiza/substitui (Update).",
      "DELETE": "DELETE apaga."}),
]
