"""Explicações detalhadas do quiz (parte 1: Parte A, fundamentos, primeiros passos no IOS).

Cada entrada: (texto exato da pergunta, explicação longa, {texto da opção: porquê}).
Nas perguntas V/F, de comando ou de valor só há a explicação longa.
O ``conteudo/__init__.py`` junta isto às perguntas como ``explica_longa`` e ``porque``.
"""

ENTRADAS = [
    ("A palavra informática vem de…",
     "“Informática” junta <b>informação</b> + <b>automática</b>: é o tratamento automático da informação por máquinas. O termo nasceu em França (informatique) nos anos 60 e mostra a ideia central: o computador recebe dados, processa-os sozinho e devolve resultados.",
     {"Informação + automática": "Certo: informação tratada de forma automática, sem uma pessoa fazer cada cálculo.",
      "Internet + matemática": "A palavra é mais antiga do que a Internet pública; a matemática está presente, mas não dá nome à palavra.",
      "Informação + prática": "Não há “prática” na origem; o essencial é o tratamento ser automático.",
      "Inteligência + máquina": "Soa bem, mas isso aproxima-se de “inteligência artificial”, outra área."}),
    ("“38,9” sozinho é…",
     "Um <b>dado</b> é um valor bruto, sem contexto. Só passa a <b>informação</b> quando sabemos o que significa (ex.: “temperatura do doente: 38,9 °C”), e a <b>conhecimento</b> quando o usamos para decidir (“tem febre, é preciso tratar”).",
     {"Um dado": "Certo: é apenas um número; não sabemos se é temperatura, preço ou peso.",
      "Conhecimento": "Conhecimento é saber usar a informação para agir; aqui nem sequer há contexto.",
      "Informação": "Seria informação se tivesse contexto (unidade, a que se refere). Sozinho é só um dado.",
      "Um programa": "Um programa é uma sequência de instruções; “38,9” não manda o computador fazer nada."}),
    ("Qual destes NÃO é hardware?",
     "<b>Hardware</b> é tudo o que se pode tocar (peças físicas); <b>software</b> são os programas. O sistema operativo (Windows, Linux, Cisco IOS) é software: é um conjunto de instruções guardado num disco ou numa memória flash.",
     {"Sistema operativo": "Certo: é software — programas que gerem o computador; não se lhe pode tocar.",
      "Teclado": "O teclado é uma peça física de entrada: é hardware.",
      "Impressora": "A impressora é um periférico físico de saída: é hardware.",
      "Cabo de rede": "Um cabo é um objeto físico (meio de transmissão): é hardware."}),
    ("As pessoas fazem parte de um sistema informático.",
     "Verdadeiro. Um sistema informático tem quatro partes: <b>hardware</b>, <b>software</b>, <b>dados</b> e <b>pessoas</b> (utilizadores, técnicos, administradores). Confusão comum: pensar que o sistema é só a máquina — sem quem o configura e usa, não cumpre a sua função."),
    ("Que profissão instala e mantém redes de computadores?",
     "O <b>técnico ou administrador de redes</b> instala cabos e equipamentos, configura routers e switches, resolve avarias e protege a rede. É exatamente o trabalho para que a certificação CCNA prepara.",
     {"Técnico/administrador de redes": "Certo: é quem configura, mantém e repara a rede.",
      "Programador": "O programador escreve software; pode trabalhar com redes, mas não é quem as instala.",
      "Designer": "O designer cria a parte visual (logótipos, páginas), não a infraestrutura de rede.",
      "Contabilista": "Trata das contas da empresa; não tem nada a ver com redes."}),
    ("Quem é considerada a primeira programadora da história?",
     "<b>Ada Lovelace</b> (século XIX) escreveu o primeiro algoritmo pensado para ser executado por uma máquina — a Máquina Analítica de Charles Babbage. Também percebeu que as máquinas podiam tratar símbolos e não só números.",
     {"Ada Lovelace": "Certo: escreveu o primeiro algoritmo para a máquina de Babbage, por volta de 1843.",
      "Marie Curie": "Foi uma cientista pioneira da radioatividade (física e química), não da programação.",
      "Grace Kelly": "Foi atriz e princesa do Mónaco. Talvez se confunda com Grace Hopper, pioneira da programação no século XX.",
      "Rosalind Franklin": "Foi química e contribuiu para descobrir a estrutura do ADN, não para a programação."}),
    ("Que invenção de 1947 substituiu as válvulas?",
     "O <b>transístor</b>, inventado nos Bell Labs em 1947, faz o mesmo papel da válvula (ligar/desligar a corrente, representar 0 e 1) mas é muito mais pequeno, gasta menos energia e avaria menos. Foi o arranque da 2.ª geração de computadores e, mais tarde, dos chips.",
     {"O transístor": "Certo: interruptor eletrónico minúsculo que substituiu as válvulas.",
      "O rato": "O rato é um periférico de entrada (anos 60); não substituiu componentes internos.",
      "O disco rígido": "É armazenamento (IBM, 1956); não substitui as válvulas no processamento.",
      "A fibra ótica": "É um meio de transmissão por luz, muito posterior para uso prático em redes."}),
    ("A 4.ª geração de computadores é marcada pelo…",
     "A 4.ª geração começa em 1971 com o <b>microprocessador</b> (Intel 4004): um processador inteiro num só chip. Foi isto que tornou possíveis os computadores pessoais e, hoje, os routers e telemóveis.",
     {"Microprocessador": "Certo: CPU inteira num único chip, desde 1971.",
      "Ábaco": "O ábaco é uma ferramenta de cálculo com milhares de anos, anterior aos computadores.",
      "Cartão perfurado": "Era usado para dar dados e programas às máquinas antigas (antes e durante a 1.ª geração).",
      "Válvula": "As válvulas marcam a 1.ª geração (anos 40–50)."}),
    ("A Lei de Moore diz que o número de transístores num chip duplica aproximadamente a cada dois anos.",
     "Verdadeiro. Gordon Moore (cofundador da Intel) observou em 1965 que a densidade de transístores crescia exponencialmente; a regra prática ficou “duplica a cada ~2 anos”. Confusão comum: não é uma lei da física, é uma observação/tendência da indústria, que hoje está a abrandar."),
    ("Na arquitetura de von Neumann…",
     "Na arquitetura de <b>von Neumann</b>, as instruções do programa e os dados ficam na <b>mesma memória</b>, e o processador vai buscá-los um a um. É o modelo de quase todos os computadores atuais, incluindo routers e switches.",
     {"Programa e dados ficam na mesma memória": "Certo: é a ideia do “programa armazenado” na mesma memória dos dados.",
      "Não há memória": "Pelo contrário: a memória partilhada é o centro desta arquitetura.",
      "Só existem cartões perfurados": "Os cartões eram uma forma de entrada de dados, não definem a arquitetura.",
      "O computador não tem processador": "A arquitetura inclui sempre uma unidade de processamento (CPU)."}),
    ("Qual a ordem do funcionamento de um computador?",
     "Qualquer computador segue o ciclo <b>entrada → processamento → saída</b> (com armazenamento pelo meio). Exemplo num router: recebe um pacote (entrada), consulta a tabela de routing (processamento) e envia-o pela interface certa (saída).",
     {"Entrada → processamento → saída": "Certo: primeiro recebe os dados, depois trata-os, por fim devolve o resultado.",
      "Saída → entrada → processamento": "Não pode haver saída antes de haver dados para tratar.",
      "Processamento → saída → entrada": "Não se processa nada sem antes receber dados.",
      "Entrada → saída → processamento": "O resultado (saída) só existe depois de processar."}),
    ("Que peça perde o conteúdo quando o computador é desligado?",
     "A <b>RAM</b> é <b>volátil</b>: guarda dados só enquanto tem corrente. É por isso que num router Cisco a running-config (que vive na RAM) se perde se ele reiniciar sem a guardar na NVRAM.",
     {"Memória RAM": "Certo: memória volátil, apaga-se quando falta a energia.",
      "SSD": "O SSD usa memória flash, que não é volátil: mantém os dados sem energia.",
      "Disco rígido": "Guarda os dados magneticamente e mantém-nos sem energia.",
      "Flash": "A flash não é volátil; nos routers Cisco guarda a imagem do IOS."}),
    ("Que peça liga o computador à rede?",
     "A <b>placa de rede (NIC — Network Interface Card)</b> é a peça que liga o computador ao cabo ou ao Wi-Fi. Cada NIC tem um endereço MAC único gravado de fábrica, usado na camada 2.",
     {"Placa de rede (NIC)": "Certo: é a interface física com a rede e tem o endereço MAC.",
      "Fonte de alimentação": "Fornece energia elétrica aos componentes; não comunica com a rede.",
      "Processador": "Executa as instruções, mas precisa da NIC para chegar à rede.",
      "Placa gráfica": "Gera a imagem para o monitor; não liga à rede."}),
    ("Um router é um tipo de computador.",
     "Verdadeiro. Um router tem CPU, RAM, NVRAM, flash, ROM, um sistema operativo (Cisco IOS) e interfaces (as suas “entradas e saídas”). Confusão comum: achar que sem ecrã e teclado não é computador — é um computador especializado (embebido) em encaminhar pacotes."),
    ("Como se chama o sistema operativo dos routers e switches Cisco?",
     "O sistema operativo dos equipamentos Cisco chama-se <b>IOS — Internetwork Operating System</b>. É gerido pela linha de comandos (CLI). Não confundir com o iOS dos iPhones da Apple, que é outro sistema.",
     {"IOS": "Certo: Cisco IOS, o Internetwork Operating System.",
      "Android": "É o sistema dos telemóveis Google/Samsung, não dos equipamentos Cisco.",
      "Windows": "É o sistema da Microsoft para PCs e servidores.",
      "Linux Mint": "É uma distribuição Linux para PCs de secretária."}),
    ("Qual destas tarefas é do sistema operativo?",
     "O <b>sistema operativo</b> gere os recursos: memória, processador, ficheiros, dispositivos e utilizadores. As tarefas do dia a dia (escrever, desenhar) são feitas por <b>aplicações</b> que correm por cima do SO.",
     {"Gerir memória, ficheiros e dispositivos": "Certo: é a função principal do SO, gerir os recursos.",
      "Escrever cartas": "Isso faz-se num processador de texto, que é uma aplicação.",
      "Fazer café": "Não é tarefa de software nenhum (a não ser de uma máquina de café!).",
      "Desenhar logótipos": "É trabalho de uma aplicação de desenho, não do SO."}),
    ("Que extensão indica um documento PDF?",
     "A <b>extensão</b> é o fim do nome do ficheiro e diz ao SO que tipo de ficheiro é e com que programa abri-lo. Documentos PDF terminam em <b>.pdf</b>.",
     {".pdf": "Certo: Portable Document Format.",
      ".exe": "É um programa executável do Windows (atenção: pode ser perigoso abrir .exe desconhecidos).",
      ".jpg": "É uma imagem (fotografia).",
      ".mp3": "É um ficheiro de áudio."}),
    ("O programa que permite ao SO usar uma impressora chama-se…",
     "Um <b>driver</b> (controlador) é um pequeno programa que ensina o sistema operativo a falar com um dispositivo concreto (impressora, placa de rede, placa gráfica). Sem o driver certo, o SO não consegue usar o equipamento.",
     {"Driver": "Certo: é o “tradutor” entre o SO e o hardware.",
      "Vírus": "Um vírus é software malicioso, não ajuda o SO a usar dispositivos.",
      "Pasta": "Uma pasta organiza ficheiros, não controla hardware.",
      "Browser": "O browser serve para navegar na web."}),
    ("Que comando do Windows mostra o endereço IP do computador?",
     "<code>ipconfig</code> (na Linha de Comandos do Windows) mostra, para cada placa de rede, o endereço IPv4/IPv6, a máscara e o gateway predefinido. <code>ipconfig /all</code> mostra ainda o MAC, os servidores DNS e se o IP veio por DHCP. Não confundir com <code>ifconfig</code>/<code>ip a</code> do Linux."),
    ("A linha de comandos permite automatizar tarefas mais facilmente do que a interface gráfica.",
     "Verdadeiro. Comandos são texto: podem ser copiados, repetidos, guardados em scripts e aplicados a 100 equipamentos de uma vez. Confusão comum: achar que a interface gráfica é sempre “mais avançada” — nos routers e switches a CLI é a forma principal de trabalhar."),
    ("Antes das redes, como se levavam dados de um computador para outro?",
     "Antes das redes, os dados eram gravados em <b>fitas, cartões perfurados ou disquetes</b> e levados à mão até outro computador — a brincadeira chamava-lhe “sneakernet” (rede de ténis). Era lento e dava erros, o que motivou a criação das redes.",
     {"Gravando em fita, cartões ou disquetes e levando à mão": "Certo: a chamada sneakernet.",
      "Por Wi-Fi": "O Wi-Fi só apareceu em 1997–1999, muito depois.",
      "Por e-mail": "O e-mail já exige uma rede; não existia antes delas.",
      "Pela cloud": "A cloud é uma ideia recente que depende da Internet."}),
    ("Na comutação de pacotes…",
     "Na <b>comutação de pacotes</b>, a mensagem é partida em pedaços (pacotes) com endereço de destino; cada pacote viaja sozinho e as ligações são partilhadas por muitas comunicações. É como a Internet funciona: aproveita melhor as ligações e contorna avarias.",
     {"A mensagem é dividida em pacotes que partilham as ligações": "Certo: pacotes independentes partilham os mesmos cabos.",
      "Um caminho fica reservado durante toda a comunicação": "Isso é a comutação de circuitos (rede telefónica antiga).",
      "Só pode haver dois computadores": "Pelo contrário, permite milhões de computadores a partilhar a rede.",
      "Não há endereços": "Cada pacote leva endereço de origem e destino; sem isso não chegava."}),
    ("A rede telefónica antiga usava comutação de circuitos.",
     "Verdadeiro. Em cada chamada, as centrais reservavam um circuito fixo de ponta a ponta durante toda a conversa, mesmo nos silêncios. Confusão comum: trocar com comutação de pacotes, em que nada fica reservado e as ligações são partilhadas."),
    ("Qual NÃO é uma vantagem das redes?",
     "As redes permitem <b>partilhar recursos</b> (impressoras, ficheiros, Internet), <b>comunicar</b> e <b>aceder a dados à distância</b>. Copiar ficheiros à mão é precisamente o problema que as redes resolveram.",
     {"Obrigar a copiar ficheiros à mão": "Certo: isto não é vantagem — é o que as redes eliminaram.",
      "Partilhar impressoras": "É uma vantagem clássica: uma impressora serve todo o escritório.",
      "Comunicar por e-mail": "É uma vantagem: o e-mail só existe graças às redes.",
      "Aceder a dados à distância": "É uma vantagem: trabalhar com dados de um servidor noutro local."}),
    ("Que aparelho permitiu aos computadores comunicarem pela linha telefónica?",
     "O <b>modem</b> (MOdulador-DEModulador) transforma os bits digitais em sons/sinais analógicos que passam na linha telefónica, e faz o inverso do outro lado. Hoje ainda se chama “modem” à caixa de fibra ou ADSL.",
     {"Modem": "Certo: modula e desmodula o sinal para passar na linha telefónica.",
      "Ábaco": "Ferramenta antiga de cálculo, sem comunicação.",
      "Telégrafo": "Enviava mensagens em código Morse; não liga computadores.",
      "Monitor": "Mostra a imagem; não comunica com outros computadores."}),
    ("Como se chamava a rede que deu origem à Internet?",
     "A <b>ARPANET</b>, criada em 1969 pela agência ARPA do Departamento de Defesa dos EUA, ligou as primeiras universidades com comutação de pacotes. Adotou o TCP/IP em 1983 e evoluiu para a Internet.",
     {"ARPANET": "Certo: a rede pioneira de 1969.",
      "Ethernet": "Ethernet é uma tecnologia de rede local (1973), não a rede que originou a Internet.",
      "Wi-Fi": "Rede local sem fios, muito posterior.",
      "NSFNET": "Foi uma rede académica posterior (1985) que serviu de espinha dorsal, mas não foi a primeira."}),
    ("Quem criou a World Wide Web?",
     "<b>Tim Berners-Lee</b>, no CERN (1989–1991), criou a Web: páginas HTML ligadas por hiperligações, servidas por HTTP e encontradas por URLs. A Web é um serviço que funciona <i>por cima</i> da Internet — não é a mesma coisa.",
     {"Tim Berners-Lee": "Certo: inventou HTML, HTTP e o primeiro browser no CERN.",
      "Bill Gates": "Fundou a Microsoft; não criou a Web.",
      "Bob Metcalfe": "Inventou a Ethernet, não a Web.",
      "Vint Cerf": "É coautor do TCP/IP (um dos “pais da Internet”), mas não da Web."}),
    ("Que tecnologia de redes locais foi criada por Bob Metcalfe em 1973?",
     "A <b>Ethernet</b> foi criada por Bob Metcalfe na Xerox PARC em 1973. Ainda hoje é a tecnologia das redes locais com cabo: switches, cabos UTP e tramas Ethernet com endereços MAC.",
     {"Ethernet": "Certo: Xerox PARC, 1973 — a base das LAN com cabo.",
      "Wi-Fi": "O Wi-Fi (802.11) é dos anos 90.",
      "Bluetooth": "Bluetooth é de 1994–1999, para ligações curtas entre aparelhos.",
      "Fibra ótica": "A fibra é um meio físico; não foi inventada por Metcalfe."}),
    ("A Internet foi desenhada com um computador central que controla todos os outros.",
     "Falso. A Internet foi desenhada <b>distribuída</b>: não há um computador central, e os pacotes encontram caminhos alternativos se uma parte falhar. Confusão comum: pensar que “a Internet tem um dono/servidor central” — é uma rede de redes, cada uma gerida por quem a possui."),
    ("Em que ano a ARPANET adotou o TCP/IP?",
     "A 1 de janeiro de <b>1983</b> a ARPANET passou toda para TCP/IP (o “flag day”). Muitos consideram esta a data de nascimento da Internet moderna.",
     {"1983": "Certo: 1 de janeiro de 1983.",
      "1969": "É o ano em que a ARPANET nasceu, ainda sem TCP/IP.",
      "1991": "É por volta do ano em que a Web foi aberta ao público.",
      "2007": "É o ano do primeiro iPhone, nada a ver com o TCP/IP."}),
    ("Na analogia do correio, o endereço IP é…",
     "Na analogia do correio, o <b>endereço IP é a morada</b>: diz onde está o destino e permite aos routers (os carteiros e centros de distribuição) decidir por onde enviar o pacote.",
     {"A morada": "Certo: identifica onde está o destinatário na rede.",
      "O selo": "O selo seria mais parecido com o pagamento do serviço; não identifica o destino.",
      "O carteiro": "O carteiro corresponde aos routers/switches que transportam.",
      "A lista telefónica": "A lista telefónica é a analogia do DNS (nome → número)."}),
    ("Que serviço traduz nomes como google.com em endereços IP?",
     "O <b>DNS (Domain Name System)</b> traduz nomes em endereços IP, como uma lista telefónica: escreve-se “google.com” e o DNS devolve, por exemplo, 142.250.184.14. Sem DNS teríamos de decorar números.",
     {"DNS": "Certo: traduz nomes de domínio em endereços IP.",
      "DHCP": "O DHCP dá automaticamente IP, máscara, gateway e DNS aos equipamentos; não traduz nomes.",
      "Wi-Fi": "É uma tecnologia de ligação sem fios, não um serviço de nomes.",
      "MAC": "O MAC é o endereço físico da placa de rede."}),
    ("Que equipamento envia os pacotes para outras redes?",
     "O <b>router</b> liga redes diferentes e escolhe o caminho dos pacotes com base no endereço IP de destino e na sua tabela de routing. O switch, pelo contrário, liga equipamentos dentro da mesma rede local.",
     {"Router": "Certo: encaminha pacotes entre redes (camada 3).",
      "Switch": "O switch encaminha tramas dentro da mesma rede local, pelo MAC.",
      "Cabo": "O cabo só transporta sinais; não toma decisões.",
      "Impressora": "É um dispositivo final, não encaminha tráfego."}),
    ("Uma foto grande é enviada pela rede num único pacote.",
     "Falso. Os dados são partidos em muitos pacotes pequenos (em Ethernet, cada um leva no máximo cerca de 1500 bytes de dados — o MTU). No destino, o TCP volta a juntá-los pela ordem certa. Confusão comum: pensar que um ficheiro viaja “inteiro”."),
    ("O que é o gateway?",
     "O <b>gateway predefinido</b> é o router da rede local que dá saída para outras redes (incluindo a Internet). Quando um PC quer falar com um IP fora da sua rede, envia o pacote para o gateway. Ex.: em casa, normalmente 192.168.1.1.",
     {"O router que dá saída para fora da rede local": "Certo: é a “porta de saída” da rede local.",
      "O nome do Wi-Fi": "O nome do Wi-Fi é o SSID.",
      "O cabo de rede": "O cabo é o meio físico, não um endereço de saída.",
      "A palavra-passe do Wi-Fi": "A palavra-passe protege o acesso, não encaminha tráfego."}),
    ("Quantos bits tem um byte?",
     "Um <b>byte</b> tem <b>8 bits</b>. Um bit é um 0 ou um 1. Em redes, cada parte de um endereço IPv4 (octeto) também tem 8 bits, por isso vai de 0 a 255.",
     {"8": "Certo: 1 byte = 8 bits.",
      "4": "4 bits são meio byte (um nibble), que é um dígito hexadecimal.",
      "16": "16 bits são 2 bytes.",
      "32": "32 bits são 4 bytes — o tamanho de um endereço IPv4 completo."}),
    ("Quanto é 00001010 em decimal?",
     "Cada posição de um octeto vale, da direita para a esquerda, 1, 2, 4, 8, 16, 32, 64, 128. Em <b>00001010</b> estão ligados os bits de valor <b>8</b> e <b>2</b>: 8 + 2 = <b>10</b>.",
     {"10": "Certo: 8 + 2 = 10.",
      "8": "Contou só o bit de 8 e esqueceu o bit de 2.",
      "12": "12 seria 00001100 (8 + 4).",
      "20": "20 seria 00010100 (16 + 4)."}),
    ("Qual o maior valor que cabe em 8 bits?",
     "Com 8 bits todos a 1 (11111111) temos 128+64+32+16+8+4+2+1 = <b>255</b>. Há 256 combinações possíveis, mas como a primeira é o 0, o maior valor é 255 — por isso nenhum octeto de um IP passa de 255.",
     {"255": "Certo: 11111111 = 255.",
      "128": "128 é só o bit mais à esquerda (10000000).",
      "200": "200 cabe em 8 bits, mas não é o maior.",
      "256": "256 é o número de combinações (0 a 255); o valor 256 já precisa de 9 bits."}),
    ("Quanto vale F em hexadecimal?",
     "O hexadecimal (base 16) usa 0–9 e depois A=10, B=11, C=12, D=13, E=14, <b>F=15</b>. Cada dígito hex representa 4 bits; F = 1111. Usa-se nos MAC e no IPv6.",
     {"15": "Certo: F é o maior dígito hex, 15 (1111).",
      "10": "10 é o A.",
      "14": "14 é o E.",
      "16": "16 já precisa de dois dígitos em hex (10)."}),
    ("Uma Internet de 80 Mbit/s descarrega aproximadamente quantos MB por segundo?",
     "As velocidades de Internet são dadas em <b>bits</b> por segundo, mas os ficheiros medem-se em <b>bytes</b>. Como 1 byte = 8 bits, divide-se por 8: 80 Mbit/s ÷ 8 = <b>10 MB/s</b> (na prática um pouco menos, por causa dos cabeçalhos).",
     {"10": "Certo: 80 ÷ 8 = 10 MB/s.",
      "80": "Confundiu bits com bytes; 80 Mbit/s não são 80 MB/s.",
      "640": "Multiplicou por 8 em vez de dividir.",
      "8": "Dividiu por 10 em vez de dividir por 8."}),
    ("Quanto é 11000000 em decimal?",
     "Os dois bits ligados estão nas posições de valor <b>128</b> e <b>64</b>: 128 + 64 = <b>192</b>. Este valor aparece muito em máscaras (255.255.255.192 = /26) e no início de redes privadas 192.168.",
     {"192": "Certo: 128 + 64 = 192.",
      "128": "Contou só o primeiro bit (10000000).",
      "224": "224 seria 11100000 (três bits ligados).",
      "240": "240 seria 11110000 (quatro bits ligados)."}),
    ("Escreva 172 em binário (8 bits).",
     "Método da subtração: 172 ≥ 128 → 1 (resta 44); 64 não cabe → 0; 32 cabe → 1 (resta 12); 16 não → 0; 8 cabe → 1 (resta 4); 4 cabe → 1 (resta 0); 2 → 0; 1 → 0. Resultado: <b>10101100</b>. Verifique: 128+32+8+4 = 172."),
    ("Quantos bits tem um octeto?",
     "Um <b>octeto</b> tem 8 bits — o nome vem de “oito”. Um endereço IPv4 tem 4 octetos (4 × 8 = 32 bits), escritos em decimal separados por pontos, como 192.168.1.10.",
     {"8": "Certo: octeto = 8 bits, como um byte.",
      "4": "4 bits são um nibble (um dígito hex).",
      "16": "16 bits são dois octetos (um grupo do IPv6 tem 16 bits).",
      "32": "32 bits é o endereço IPv4 inteiro (4 octetos)."}),
    ("Qual é o binário de 224?",
     "224 = 128 + 64 + 32, ou seja, os três bits da esquerda ligados: <b>11100000</b>. Truque: os valores válidos de máscara são 128, 192, 224, 240, 248, 252, 254, 255 (vai-se ligando um bit de cada vez da esquerda para a direita).",
     {"11100000": "Certo: 128 + 64 + 32 = 224.",
      "11000000": "Isto é 192 (128 + 64).",
      "11110000": "Isto é 240 (128 + 64 + 32 + 16).",
      "11111000": "Isto é 248."}),
    ("Quanto é 00100101 em decimal?",
     "Bits ligados nas posições de valor 32, 4 e 1: 32 + 4 + 1 = <b>37</b>. Dica: escreva por cima de cada bit 128 64 32 16 8 4 2 1 e some só onde há 1."),
    ("O maior valor que cabe num octeto é 256.",
     "Falso. Um octeto tem 2⁸ = 256 combinações, mas começam no 0, por isso vão de <b>0 a 255</b>. Confusão comum: confundir o número de combinações (256) com o maior valor (255). É por isso que 192.168.1.256 não é um IP válido."),
    ("No método das divisões sucessivas por 2, como se lêem os restos?",
     "Divide-se o número por 2 repetidamente e anotam-se os restos (0 ou 1). O <b>último resto</b> é o bit mais significativo (o da esquerda), por isso lê-se <b>de baixo para cima</b>. Ex.: 10 → restos 0,1,0,1 → lido ao contrário: 1010.",
     {"De baixo para cima": "Certo: o último resto é o bit mais à esquerda.",
      "De cima para baixo": "Assim obtinha o número ao contrário (bits trocados de ordem).",
      "Só o primeiro resto": "Cada resto é um bit; precisa de todos.",
      "Somam-se todos": "Somar os restos dá o número de bits a 1, não o binário."}),
    ("Escreva 10 em binário com 8 bits.",
     "10 = 8 + 2 → bits de 8 e de 2 ligados: 1010. Com 8 bits acrescentam-se zeros à esquerda: <b>00001010</b>. Em IPs e máscaras escreve-se sempre o octeto completo com 8 bits."),
    ("Qual destes valores NÃO pode aparecer num octeto de máscara?",
     "Numa máscara, os bits a 1 têm de ser <b>contínuos a partir da esquerda</b>. Por isso os únicos valores possíveis num octeto são 0, 128, 192, 224, 240, 248, 252, 254 e 255. <b>250 = 11111010</b> tem um 0 no meio dos 1: não é válido.",
     {"250": "Certo: 11111010 tem um buraco — os 1 não são contínuos.",
      "252": "252 = 11111100: válido (/30 no último octeto).",
      "248": "248 = 11111000: válido (/29).",
      "254": "254 = 11111110: válido (/31)."}),
    ("Quanto é 11111100 em decimal?",
     "Seis bits ligados: 128+64+32+16+8+4 = <b>252</b>. Atalho: 255 − 3 (os dois bits a 0 valem 2+1) = 252. É o octeto da máscara /30 (255.255.255.252), usada em ligações ponto a ponto."),
    ("Um colega diz que o router da empresa “não é um computador porque não tem ecrã”. O que responde?",
     "Um router é um <b>computador embebido</b>: tem processador, memórias (RAM, NVRAM, flash, ROM), sistema operativo (IOS) e interfaces. Gere-se pela consola ou por SSH, por isso não precisa de ecrã nem teclado próprios.",
     {"É um computador embebido: tem CPU, memória e sistema operativo": "Certo: é um computador especializado em encaminhar pacotes.",
      "Tem razão": "Ter ecrã não define um computador; o que conta é processar dados com um programa.",
      "É apenas um cabo inteligente": "Um router toma decisões com software e tabelas; não é um cabo.",
      "Só os servidores são computadores": "PCs, telemóveis, routers e switches também são computadores."}),
    ("Qual destas ideias faz parte do desenho original da Internet?",
     "A Internet nasceu com duas ideias-chave: <b>comutação de pacotes</b> (dados em pedaços independentes) e <b>rede distribuída</b> (sem centro único), para continuar a funcionar mesmo que partes falhem.",
     {"Comutação de pacotes e rede distribuída": "Certo: pacotes que encontram caminhos alternativos, sem ponto central.",
      "Um controlador central único": "Seria um ponto único de falha — exatamente o que se quis evitar.",
      "Só cabos de cobre": "A Internet funciona sobre qualquer meio: cobre, fibra, rádio, satélite.",
      "Endereços com nomes, sem números": "Os endereços são números (IP); os nomes vêm do DNS, por cima."}),
    ("O endereço MAC é escrito em hexadecimal.",
     "Verdadeiro. O MAC tem 48 bits, escritos como 12 dígitos hexadecimais (ex.: 00:1A:2B:3C:4D:5E ou, na Cisco, 001a.2b3c.4d5e). Os primeiros 24 bits (OUI) identificam o fabricante. Confusão comum: o IPv4 é que se escreve em decimal com pontos."),
    ("Na “caixa” de Internet de casa, que função cria o Wi-Fi?",
     "A “caixa” do operador junta várias funções num só aparelho: router, switch, firewall, modem e <b>access point</b>. É o access point (AP) que emite o sinal Wi-Fi e liga os equipamentos sem fios à rede com cabo.",
     {"Access point": "Certo: o AP emite e recebe o sinal rádio Wi-Fi.",
      "Switch": "O switch liga equipamentos por cabo (as portas LAN atrás da caixa).",
      "Firewall": "A firewall filtra tráfego por segurança; não cria o sinal Wi-Fi.",
      "Cabo": "O cabo é o meio físico com fios, o contrário de Wi-Fi."}),
    ("Um switch serve para ligar equipamentos do mesmo local.",
     "Verdadeiro. O switch liga os equipamentos da mesma rede local (LAN) — PCs, impressoras, APs — e encaminha as tramas pelo endereço MAC. Confusão comum: para ligar redes diferentes (ex.: a loja à Internet) é preciso um router."),
    ("Que equipamento liga a rede da loja à rede do banco?",
     "Ligar <b>redes diferentes</b> é o papel do <b>router</b>: decide por onde enviar cada pacote com base no IP de destino. O switch só trabalha dentro da rede local da loja.",
     {"Router": "Certo: liga redes diferentes e encaminha entre elas.",
      "Switch": "O switch liga equipamentos dentro da mesma rede local.",
      "Impressora": "É um dispositivo final.",
      "Monitor": "É um periférico de saída do PC."}),
    ("Qual destes é um dispositivo intermediário?",
     "<b>Dispositivos intermediários</b> encaminham tráfego entre outros: switches, routers, access points, firewalls. <b>Dispositivos finais</b> são a origem ou o destino dos dados: PCs, telemóveis, impressoras, servidores.",
     {"Switch": "Certo: está no meio do caminho e encaminha tramas.",
      "Impressora de rede": "É um dispositivo final: recebe trabalhos de impressão.",
      "Servidor web": "É um dispositivo final: é o destino dos pedidos HTTP.",
      "Telemóvel": "É um dispositivo final: origem e destino de dados."}),
    ("Uma rede que cobre apenas um edifício chama-se…",
     "Classifica-se uma rede pelo alcance: <b>PAN</b> (pessoal, poucos metros), <b>LAN</b> (sala, piso, edifício), <b>MAN</b> (cidade) e <b>WAN</b> (países, continentes). Um edifício é tipicamente uma LAN.",
     {"LAN": "Certo: Local Area Network — rede local de um edifício.",
      "WAN": "WAN cobre grandes distâncias (cidades, países).",
      "MAN": "MAN cobre uma cidade ou área metropolitana.",
      "PAN": "PAN cobre poucos metros à volta de uma pessoa (ex.: Bluetooth)."}),
    ("Um computador pode ser cliente e servidor ao mesmo tempo.",
     "Verdadeiro. “Cliente” e “servidor” são papéis, não tipos de máquina. Um PC pode partilhar uma pasta (servidor de ficheiros) enquanto navega na web (cliente HTTP). Confusão comum: achar que servidor tem de ser uma máquina especial num bastidor."),
    ("O conjunto de regras que define como os dispositivos comunicam chama-se…",
     "Um <b>protocolo</b> é um conjunto de regras: formato das mensagens, ordem, significado e o que fazer em caso de erro. Exemplos: IP, TCP, HTTP, DHCP. Sem protocolos comuns, equipamentos de marcas diferentes não se entendiam.",
     {"Protocolo": "Certo: define formato, ordem e significado das mensagens.",
      "Topologia": "A topologia é a forma como os equipamentos estão ligados (estrela, malha…).",
      "Meio": "O meio é por onde passa o sinal (cobre, fibra, ar).",
      "Largura de banda": "É a capacidade da ligação (ex.: 1 Gbit/s), não as regras."}),
    ("Fibra ótica, cobre e Wi-Fi são exemplos de meios de transmissão.",
     "Verdadeiro. Os três grandes tipos de meio: <b>cobre</b> (impulsos elétricos, ex.: UTP), <b>fibra</b> (luz) e <b>sem fios</b> (ondas de rádio). Confusão comum: pensar que Wi-Fi “não tem meio” — o meio é o ar/espaço por onde viajam as ondas."),
    ("Quantas ligações tem uma malha completa com 6 routers?",
     "Numa malha completa, cada equipamento liga-se a todos os outros. Fórmula: <b>n × (n − 1) / 2</b>. Com 6: 6 × 5 / 2 = <b>15</b>. Divide-se por 2 porque a ligação A–B é a mesma que B–A.",
     {"15": "Certo: 6 × 5 / 2 = 15.",
      "12": "Não segue a fórmula; seria 6 × 2.",
      "30": "Esqueceu-se de dividir por 2 (contou cada ligação duas vezes).",
      "36": "6 × 6 contaria ligações de cada router a si próprio e repetidas."}),
    ("Em spine-leaf, cada leaf liga-se a…",
     "Na arquitetura <b>spine-leaf</b> (centros de dados), cada switch leaf liga-se a <b>todos os spines</b>, e nunca a outros leafs; spines também não se ligam entre si. Assim, quaisquer dois servidores estão sempre à mesma distância (leaf–spine–leaf).",
     {"Todos os spines": "Certo: cada leaf liga a todos os spines.",
      "Outro leaf": "Leafs não se ligam entre si em spine-leaf.",
      "Apenas um spine": "Ligar só a um spine criava ponto único de falha e caminhos desiguais.",
      "Ao router de Internet": "A saída para fora faz-se por leafs de fronteira (border leaf), não por todos."}),
    ("Que camada da arquitetura hierárquica liga os utilizadores finais?",
     "No modelo hierárquico de três camadas: <b>acesso</b> (onde se ligam PCs, telefones IP e APs), <b>distribuição</b> (junta os switches de acesso, aplica políticas e routing entre VLANs) e <b>núcleo</b> (transporte rápido entre distribuições).",
     {"Acesso": "Certo: é aqui que se ligam os dispositivos finais.",
      "Núcleo": "O núcleo só transporta tráfego rapidamente entre zonas; não liga utilizadores.",
      "Distribuição": "A distribuição agrega os switches de acesso.",
      "Spine": "Spine é do modelo spine-leaf de centros de dados, não do modelo hierárquico de campus."}),
    ("No núcleo colapsado, distribuição e núcleo estão nos mesmos equipamentos.",
     "Verdadeiro. No <b>núcleo colapsado</b> (arquitetura de duas camadas) os mesmos switches fazem distribuição e núcleo, poupando equipamento em campus pequenos e médios. Confusão comum: pensar que se elimina a camada de acesso — essa mantém-se."),
    ("Na topologia em estrela, se o cabo de um PC avariar…",
     "Na <b>estrela</b>, cada equipamento tem o seu próprio cabo até ao ponto central (switch). Se um cabo falha, <b>só esse PC</b> fica sem rede. O ponto fraco é o centro: se o switch avariar, todos caem.",
     {"Só esse PC fica sem rede": "Certo: cada host tem ligação independente ao switch.",
      "Toda a rede para": "Isso aconteceria se avariasse o switch central, não um cabo de PC.",
      "O switch reinicia": "O switch apenas vê a porta a ir abaixo; não reinicia.",
      "Formam-se loops": "Um cabo partido remove ligações; não cria loops."}),
    ("O que é uma CLI?",
     "<b>CLI — Command Line Interface</b>: uma interface de texto onde se escrevem comandos. É a forma principal de configurar routers e switches Cisco (via consola, Telnet ou SSH).",
     {"Uma interface onde se escrevem comandos": "Certo: Command Line Interface.",
      "Um tipo de cabo": "Os cabos são, por exemplo, UTP ou consola; CLI não é cabo.",
      "Um antivírus": "Um antivírus é software de segurança.",
      "Uma placa de rede": "A placa de rede é a NIC (hardware)."}),
    ("Como se chama o sistema operativo dos equipamentos Cisco?",
     "Os routers e switches Cisco correm o <b>Cisco IOS</b> (Internetwork Operating System), gerido pela CLI. Há variantes (IOS XE, NX-OS), mas os comandos do CCNA são os do IOS.",
     {"IOS": "Certo: Cisco IOS.",
      "Windows Server": "É o sistema da Microsoft para servidores.",
      "Android": "É o sistema de telemóveis da Google.",
      "Ubuntu": "É uma distribuição Linux."}),
    ("O Packet Tracer é gratuito para quem cria conta na Cisco Networking Academy.",
     "Verdadeiro. O Cisco Packet Tracer é um simulador gratuito: basta criar conta na Networking Academy (NetAcad). Confusão comum: confundi-lo com um emulador como o GNS3/CML, que corre imagens reais do IOS e exige mais recursos."),
    ("Que prompt indica o modo de configuração global?",
     "Os prompts do IOS mostram o modo: <code>R1&gt;</code> EXEC utilizador, <code>R1#</code> EXEC privilegiado, <code>R1(config)#</code> <b>configuração global</b> e <code>R1(config-if)#</code> configuração de interface. Entra-se no global com <code>configure terminal</code>.",
     {"R1(config)#": "Certo: (config)# é o modo de configuração global.",
      "R1>": "É o modo EXEC de utilizador: só comandos básicos de consulta.",
      "R1#": "É o modo EXEC privilegiado: show, copy, debug — mas ainda não configura.",
      "R1(config-if)#": "É o submodo de configuração de uma interface."}),
    ("Que comando passa de R1> para R1#?",
     "<code>enable</code> passa do modo EXEC de utilizador (&gt;) ao EXEC privilegiado (#). Pode abreviar-se (<code>en</code>) porque nenhum outro comando começa da mesma forma. Se existir <code>enable secret</code>, pede a palavra-passe. O contrário é <code>disable</code>."),
    ("Onde fica a running-config?",
     "A <b>running-config</b> (configuração ativa) está na <b>RAM</b> e cada comando altera-a imediatamente. A <b>startup-config</b> fica na NVRAM e é lida no arranque. Por isso, se não guardar (<code>copy run start</code>), perde as alterações ao reiniciar.",
     {"RAM": "Certo: memória volátil, perde-se sem guardar.",
      "NVRAM": "Na NVRAM fica a startup-config, não a running-config.",
      "Flash": "Na flash fica a imagem do IOS.",
      "ROM": "Na ROM ficam o bootstrap, o POST e o ROMMON."}),
    ("Que comando guarda a configuração ativa no arranque?",
     "<code>copy running-config startup-config</code> (abreviado <code>copy run start</code>) copia a configuração da RAM para a NVRAM, para sobreviver a um reinício. <code>write memory</code> (<code>wr</code>) faz o mesmo. Corre-se no modo EXEC privilegiado (#), ou com <code>do</code> nos modos de configuração."),
    ("No modo de configuração pode usar 'do show ip interface brief'.",
     "Verdadeiro. O prefixo <code>do</code> executa um comando do modo EXEC privilegiado (show, ping, copy) sem sair do modo de configuração. Confusão comum: escrever <code>show</code> sem <code>do</code> dentro de (config)# dá erro “Invalid input”."),
    ("Onde se configura o IP de gestão de um switch de camada 2?",
     "Um switch de camada 2 não encaminha pacotes IP, mas precisa de um IP para ser gerido (SSH, SNMP). Esse IP vai numa <b>SVI</b> — interface virtual de VLAN, ex.: <code>interface vlan 1</code> + <code>ip address</code> + <code>no shutdown</code>.",
     {"Na SVI (interface vlan)": "Certo: interface vlan X com ip address e no shutdown.",
      "Na porta Fa0/1": "As portas físicas de um switch L2 são portas de camada 2; não levam IP.",
      "Na consola": "A consola é uma porta de gestão série, sem IP.",
      "No PC": "O PC tem o seu próprio IP; o switch precisa do dele na SVI."}),
    ("Que comando define o gateway do switch para 192.168.1.1?",
     "<code>ip default-gateway 192.168.1.1</code>, no modo de configuração global, diz ao switch de camada 2 para onde enviar tráfego de gestão destinado a outras redes (ex.: SSH de um PC noutra VLAN). Num router usar-se-ia uma rota por defeito (<code>ip route 0.0.0.0 0.0.0.0 …</code>)."),
    ("Que quatro dados um PC precisa para navegar?",
     "Para navegar, um PC precisa de: <b>IP</b> (quem é), <b>máscara</b> (qual a sua rede), <b>gateway</b> (por onde sair) e <b>DNS</b> (traduzir nomes). Normalmente chegam todos por DHCP.",
     {"IP, máscara, gateway, DNS": "Certo: são os quatro parâmetros IP que o DHCP costuma entregar.",
      "MAC, porta, cabo, VLAN": "O MAC é de fábrica e porta/cabo/VLAN são da infraestrutura; não se configuram no PC para navegar.",
      "SSID, canal, banda, potência": "São parâmetros do Wi-Fi, não da configuração IP.",
      "Só o IP": "Sem máscara, gateway e DNS o PC não sai da rede local nem resolve nomes."}),
    ("A SVI vem ativa por defeito num switch Cisco.",
     "Falso. A <code>interface vlan 1</code> vem <b>administratively down</b>; é preciso <code>no shutdown</code>. E só fica up/up se existir pelo menos uma porta ativa nessa VLAN. Confusão comum: as portas físicas de um switch vêm ativas, mas a SVI não."),
    ("Na analogia da encomenda, a etiqueta com a morada corresponde a…",
     "Na analogia da encomenda, a morada na etiqueta é o <b>endereço IP</b>, que pertence à <b>camada de rede (camada 3)</b>. É com ele que os routers decidem o caminho, tal como os centros de distribuição usam a morada.",
     {"Camada de rede (IP)": "Certo: a morada = endereço IP da camada 3.",
      "Camada física": "A camada física corresponde ao camião/estrada — o transporte dos bits.",
      "Aplicação": "A aplicação corresponde ao conteúdo da encomenda.",
      "Cabo": "O cabo é o meio físico, não a morada."}),
    ("Um protocolo é um conjunto de regras de comunicação.",
     "Verdadeiro. Um protocolo define formato, ordem, significado e tempo das mensagens. Exemplo: o HTTP diz como o browser pede uma página e como o servidor responde. Confusão comum: achar que protocolo é um programa — é a regra; os programas implementam-na."),
]
